-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [parity_state_verif]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace parity_state_verif

/-- [parity_state_verif::ParityError]
    Source: 'src/lib.rs', lines 26:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive ParityError where
| ZeroDataBlocks : ParityError
| OrdinalRangeOverflow : ParityError
| WatermarkMovedBackwards : ParityError

/-- [parity_state_verif::{impl core::clone::Clone for parity_state_verif::ParityError}::clone]:
    Source: 'src/lib.rs', lines 25:9-25:14
    Visibility: public -/
def ParityError.Insts.CoreCloneClone.clone
  (self : ParityError) : Result ParityError := do
  ok self

/-- Trait implementation: [parity_state_verif::{impl core::clone::Clone for parity_state_verif::ParityError}]
    Source: 'src/lib.rs', lines 25:9-25:14 -/
@[reducible]
def ParityError.Insts.CoreCloneClone : core.clone.Clone ParityError := {
  clone := ParityError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_state_verif::{impl core::marker::Copy for parity_state_verif::ParityError}]
    Source: 'src/lib.rs', lines 25:16-25:20 -/
@[reducible]
def ParityError.Insts.CoreMarkerCopy : core.marker.Copy ParityError := {
  cloneInst := ParityError.Insts.CoreCloneClone
}

/-- [parity_state_verif::{impl core::fmt::Debug for parity_state_verif::ParityError}::fmt]:
    Source: 'src/lib.rs', lines 25:22-25:27
    Visibility: public -/
def ParityError.Insts.CoreFmtDebug.fmt
  (self : ParityError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | ParityError.ZeroDataBlocks =>
    core.fmt.Formatter.write_str f (toStr "ZeroDataBlocks")
  | ParityError.OrdinalRangeOverflow =>
    core.fmt.Formatter.write_str f (toStr "OrdinalRangeOverflow")
  | ParityError.WatermarkMovedBackwards =>
    core.fmt.Formatter.write_str f (toStr "WatermarkMovedBackwards")

/-- Trait implementation: [parity_state_verif::{impl core::fmt::Debug for parity_state_verif::ParityError}]
    Source: 'src/lib.rs', lines 25:22-25:27 -/
@[reducible]
def ParityError.Insts.CoreFmtDebug : core.fmt.Debug ParityError := {
  fmt := ParityError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_state_verif::{impl core::marker::StructuralPartialEq for parity_state_verif::ParityError}]
    Source: 'src/lib.rs', lines 25:29-25:38 -/
@[reducible]
def ParityError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ParityError := {
}

/-- [parity_state_verif::{impl core::cmp::PartialEq<parity_state_verif::ParityError> for parity_state_verif::ParityError}::eq]:
    Source: 'src/lib.rs', lines 25:29-25:38
    Visibility: public -/
def ParityError.Insts.CoreCmpPartialEqParityError.eq
  (self : ParityError) (other : ParityError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [parity_state_verif::{impl core::cmp::PartialEq<parity_state_verif::ParityError> for parity_state_verif::ParityError}]
    Source: 'src/lib.rs', lines 25:29-25:38 -/
@[reducible]
def ParityError.Insts.CoreCmpPartialEqParityError : core.cmp.PartialEq
  ParityError ParityError := {
  eq := ParityError.Insts.CoreCmpPartialEqParityError.eq
}

/-- [parity_state_verif::{impl core::cmp::Eq for parity_state_verif::ParityError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 25:40-25:42
    Visibility: public -/
def ParityError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ParityError) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_state_verif::{impl core::cmp::Eq for parity_state_verif::ParityError}]
    Source: 'src/lib.rs', lines 25:40-25:42 -/
@[reducible]
def ParityError.Insts.CoreCmpEq : core.cmp.Eq ParityError := {
  partialEqInst := ParityError.Insts.CoreCmpPartialEqParityError
  assert_fields_are_eq := ParityError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_state_verif::ObjectParityState]
    Source: 'src/lib.rs', lines 37:0-44:1
    Visibility: public -/
@[discriminant isize]
inductive ObjectParityState where
| Pending : ObjectParityState
| Partial : ObjectParityState
| Protected : ObjectParityState

/-- [parity_state_verif::{impl core::clone::Clone for parity_state_verif::ObjectParityState}::clone]:
    Source: 'src/lib.rs', lines 36:9-36:14
    Visibility: public -/
def ObjectParityState.Insts.CoreCloneClone.clone
  (self : ObjectParityState) : Result ObjectParityState := do
  ok self

/-- Trait implementation: [parity_state_verif::{impl core::clone::Clone for parity_state_verif::ObjectParityState}]
    Source: 'src/lib.rs', lines 36:9-36:14 -/
@[reducible]
def ObjectParityState.Insts.CoreCloneClone : core.clone.Clone ObjectParityState
  := {
  clone := ObjectParityState.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_state_verif::{impl core::marker::Copy for parity_state_verif::ObjectParityState}]
    Source: 'src/lib.rs', lines 36:16-36:20 -/
@[reducible]
def ObjectParityState.Insts.CoreMarkerCopy : core.marker.Copy ObjectParityState
  := {
  cloneInst := ObjectParityState.Insts.CoreCloneClone
}

/-- [parity_state_verif::{impl core::fmt::Debug for parity_state_verif::ObjectParityState}::fmt]:
    Source: 'src/lib.rs', lines 36:22-36:27
    Visibility: public -/
def ObjectParityState.Insts.CoreFmtDebug.fmt
  (self : ObjectParityState) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | ObjectParityState.Pending =>
    core.fmt.Formatter.write_str f (toStr "Pending")
  | ObjectParityState.Partial =>
    core.fmt.Formatter.write_str f (toStr "Partial")
  | ObjectParityState.Protected =>
    core.fmt.Formatter.write_str f (toStr "Protected")

/-- Trait implementation: [parity_state_verif::{impl core::fmt::Debug for parity_state_verif::ObjectParityState}]
    Source: 'src/lib.rs', lines 36:22-36:27 -/
@[reducible]
def ObjectParityState.Insts.CoreFmtDebug : core.fmt.Debug ObjectParityState
  := {
  fmt := ObjectParityState.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_state_verif::{impl core::marker::StructuralPartialEq for parity_state_verif::ObjectParityState}]
    Source: 'src/lib.rs', lines 36:29-36:38 -/
@[reducible]
def ObjectParityState.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ObjectParityState := {
}

/-- [parity_state_verif::{impl core::cmp::PartialEq<parity_state_verif::ObjectParityState> for parity_state_verif::ObjectParityState}::eq]:
    Source: 'src/lib.rs', lines 36:29-36:38
    Visibility: public -/
def ObjectParityState.Insts.CoreCmpPartialEqObjectParityState.eq
  (self : ObjectParityState) (other : ObjectParityState) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [parity_state_verif::{impl core::cmp::PartialEq<parity_state_verif::ObjectParityState> for parity_state_verif::ObjectParityState}]
    Source: 'src/lib.rs', lines 36:29-36:38 -/
@[reducible]
def ObjectParityState.Insts.CoreCmpPartialEqObjectParityState :
  core.cmp.PartialEq ObjectParityState ObjectParityState := {
  eq := ObjectParityState.Insts.CoreCmpPartialEqObjectParityState.eq
}

/-- [parity_state_verif::{impl core::cmp::Eq for parity_state_verif::ObjectParityState}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 36:40-36:42
    Visibility: public -/
def ObjectParityState.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ObjectParityState) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_state_verif::{impl core::cmp::Eq for parity_state_verif::ObjectParityState}]
    Source: 'src/lib.rs', lines 36:40-36:42 -/
@[reducible]
def ObjectParityState.Insts.CoreCmpEq : core.cmp.Eq ObjectParityState := {
  partialEqInst := ObjectParityState.Insts.CoreCmpPartialEqObjectParityState
  assert_fields_are_eq :=
    ObjectParityState.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_state_verif::ObjectParityStateUpdateRange]
    Source: 'src/lib.rs', lines 49:0-54:1
    Visibility: public -/
structure ObjectParityStateUpdateRange where
  old_highest_protected_ordinal : Std.U64
  new_highest_protected_ordinal : Std.U64

/-- [parity_state_verif::{impl core::clone::Clone for parity_state_verif::ObjectParityStateUpdateRange}::clone]:
    Source: 'src/lib.rs', lines 48:9-48:14
    Visibility: public -/
def ObjectParityStateUpdateRange.Insts.CoreCloneClone.clone
  (self : ObjectParityStateUpdateRange) :
  Result ObjectParityStateUpdateRange
  := do
  ok self

/-- Trait implementation: [parity_state_verif::{impl core::clone::Clone for parity_state_verif::ObjectParityStateUpdateRange}]
    Source: 'src/lib.rs', lines 48:9-48:14 -/
@[reducible]
def ObjectParityStateUpdateRange.Insts.CoreCloneClone : core.clone.Clone
  ObjectParityStateUpdateRange := {
  clone := ObjectParityStateUpdateRange.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_state_verif::{impl core::marker::Copy for parity_state_verif::ObjectParityStateUpdateRange}]
    Source: 'src/lib.rs', lines 48:16-48:20 -/
@[reducible]
def ObjectParityStateUpdateRange.Insts.CoreMarkerCopy : core.marker.Copy
  ObjectParityStateUpdateRange := {
  cloneInst := ObjectParityStateUpdateRange.Insts.CoreCloneClone
}

/-- [parity_state_verif::{impl core::fmt::Debug for parity_state_verif::ObjectParityStateUpdateRange}::fmt]:
    Source: 'src/lib.rs', lines 48:22-48:27
    Visibility: public -/
def ObjectParityStateUpdateRange.Insts.CoreFmtDebug.fmt
  (self : ObjectParityStateUpdateRange) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.old_highest_protected_ordinal
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64)
      self.new_highest_protected_ordinal
  core.fmt.Formatter.debug_struct_field2_finish f (toStr
    "ObjectParityStateUpdateRange") (toStr "old_highest_protected_ordinal") dyn
    (toStr "new_highest_protected_ordinal") dyn1

/-- Trait implementation: [parity_state_verif::{impl core::fmt::Debug for parity_state_verif::ObjectParityStateUpdateRange}]
    Source: 'src/lib.rs', lines 48:22-48:27 -/
@[reducible]
def ObjectParityStateUpdateRange.Insts.CoreFmtDebug : core.fmt.Debug
  ObjectParityStateUpdateRange := {
  fmt := ObjectParityStateUpdateRange.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_state_verif::{impl core::marker::StructuralPartialEq for parity_state_verif::ObjectParityStateUpdateRange}]
    Source: 'src/lib.rs', lines 48:29-48:38 -/
@[reducible]
def ObjectParityStateUpdateRange.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ObjectParityStateUpdateRange := {
}

/-- [parity_state_verif::{impl core::cmp::PartialEq<parity_state_verif::ObjectParityStateUpdateRange> for parity_state_verif::ObjectParityStateUpdateRange}::eq]:
    Source: 'src/lib.rs', lines 48:29-48:38
    Visibility: public -/
def
  ObjectParityStateUpdateRange.Insts.CoreCmpPartialEqObjectParityStateUpdateRange.eq
  (self : ObjectParityStateUpdateRange) (other : ObjectParityStateUpdateRange)
  :
  Result Bool
  := do
  if self.old_highest_protected_ordinal = other.old_highest_protected_ordinal
  then
    ok (self.new_highest_protected_ordinal =
      other.new_highest_protected_ordinal)
  else ok false

/-- Trait implementation: [parity_state_verif::{impl core::cmp::PartialEq<parity_state_verif::ObjectParityStateUpdateRange> for parity_state_verif::ObjectParityStateUpdateRange}]
    Source: 'src/lib.rs', lines 48:29-48:38 -/
@[reducible]
def
  ObjectParityStateUpdateRange.Insts.CoreCmpPartialEqObjectParityStateUpdateRange
  : core.cmp.PartialEq ObjectParityStateUpdateRange
  ObjectParityStateUpdateRange := {
  eq :=
    ObjectParityStateUpdateRange.Insts.CoreCmpPartialEqObjectParityStateUpdateRange.eq
}

/-- [parity_state_verif::{impl core::cmp::Eq for parity_state_verif::ObjectParityStateUpdateRange}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 48:40-48:42
    Visibility: public -/
def ObjectParityStateUpdateRange.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ObjectParityStateUpdateRange) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_state_verif::{impl core::cmp::Eq for parity_state_verif::ObjectParityStateUpdateRange}]
    Source: 'src/lib.rs', lines 48:40-48:42 -/
@[reducible]
def ObjectParityStateUpdateRange.Insts.CoreCmpEq : core.cmp.Eq
  ObjectParityStateUpdateRange := {
  partialEqInst :=
    ObjectParityStateUpdateRange.Insts.CoreCmpPartialEqObjectParityStateUpdateRange
  assert_fields_are_eq :=
    ObjectParityStateUpdateRange.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_state_verif::{parity_state_verif::ObjectParityStateUpdateRange}::from_watermark_advance]:
    Source: 'src/lib.rs', lines 59:4-73:5
    Visibility: public -/
def ObjectParityStateUpdateRange.from_watermark_advance
  (old_highest_protected_ordinal : Std.U64)
  (new_highest_protected_ordinal : Std.U64) :
  Result (core.result.Result (Option ObjectParityStateUpdateRange) ParityError)
  := do
  if new_highest_protected_ordinal < old_highest_protected_ordinal
  then ok (core.result.Result.Err ParityError.WatermarkMovedBackwards)
  else
    if new_highest_protected_ordinal = old_highest_protected_ordinal
    then ok (core.result.Result.Ok none)
    else
      ok (core.result.Result.Ok (some
        { old_highest_protected_ordinal, new_highest_protected_ordinal }))

/-- [parity_state_verif::{parity_state_verif::ObjectParityStateUpdateRange}::first_parity_data_ordinal_upper_exclusive]:
    Source: 'src/lib.rs', lines 76:4-78:5
    Visibility: public -/
def ObjectParityStateUpdateRange.first_parity_data_ordinal_upper_exclusive
  (self : ObjectParityStateUpdateRange) : Result Std.U64 := do
  ok self.new_highest_protected_ordinal

/-- [parity_state_verif::{parity_state_verif::ObjectParityStateUpdateRange}::ordinal_end_exclusive_lower_exclusive]:
    Source: 'src/lib.rs', lines 81:4-83:5
    Visibility: public -/
def ObjectParityStateUpdateRange.ordinal_end_exclusive_lower_exclusive
  (self : ObjectParityStateUpdateRange) : Result Std.U64 := do
  ok self.old_highest_protected_ordinal

/-- [parity_state_verif::{parity_state_verif::ObjectParityStateUpdateRange}::includes_object]:
    Source: 'src/lib.rs', lines 87:4-105:5
    Visibility: public -/
def ObjectParityStateUpdateRange.includes_object
  (self : ObjectParityStateUpdateRange) (first_parity_data_ordinal : Std.U64)
  (data_block_count : Std.U64) :
  Result (core.result.Result Bool ParityError)
  := do
  if data_block_count = 0#u64
  then ok (core.result.Result.Err ParityError.ZeroDataBlocks)
  else
    let o ← lift (U64.checked_add first_parity_data_ordinal data_block_count)
    match o with
    | none => ok (core.result.Result.Err ParityError.OrdinalRangeOverflow)
    | some end1 =>
      let i ←
        ObjectParityStateUpdateRange.first_parity_data_ordinal_upper_exclusive
          self
      if first_parity_data_ordinal < i
      then
        let i1 ←
          ObjectParityStateUpdateRange.ordinal_end_exclusive_lower_exclusive
            self
        ok (core.result.Result.Ok (end1 > i1))
      else ok (core.result.Result.Ok false)

/-- [parity_state_verif::{parity_state_verif::ObjectParityState}::from_ordinals]:
    Source: 'src/lib.rs', lines 131:4-153:5
    Visibility: public -/
def ObjectParityState.from_ordinals
  (first_parity_data_ordinal : Std.U64) (data_block_count : Std.U64)
  (highest_protected_ordinal : Std.U64) :
  Result (core.result.Result ObjectParityState ParityError)
  := do
  if data_block_count = 0#u64
  then ok (core.result.Result.Err ParityError.ZeroDataBlocks)
  else
    let o ← lift (U64.checked_add first_parity_data_ordinal data_block_count)
    match o with
    | none => ok (core.result.Result.Err ParityError.OrdinalRangeOverflow)
    | some end1 =>
      if end1 <= highest_protected_ordinal
      then ok (core.result.Result.Ok ObjectParityState.Protected)
      else
        if first_parity_data_ordinal >= highest_protected_ordinal
        then ok (core.result.Result.Ok ObjectParityState.Pending)
        else ok (core.result.Result.Ok ObjectParityState.Partial)

/-- [parity_state_verif::{parity_state_verif::ObjectParityStateUpdateRange}::recompute_object]:
    Source: 'src/lib.rs', lines 109:4-125:5
    Visibility: public -/
def ObjectParityStateUpdateRange.recompute_object
  (self : ObjectParityStateUpdateRange) (first_parity_data_ordinal : Std.U64)
  (data_block_count : Std.U64) :
  Result (core.result.Result (Option ObjectParityState) ParityError)
  := do
  let r ←
    ObjectParityStateUpdateRange.includes_object self first_parity_data_ordinal
      data_block_count
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val
    then
      let r1 ←
        ObjectParityState.from_ordinals first_parity_data_ordinal
          data_block_count self.new_highest_protected_ordinal
      match r1 with
      | core.result.Result.Ok state => ok (core.result.Result.Ok (some state))
      | core.result.Result.Err err => ok (core.result.Result.Err err)
    else ok (core.result.Result.Ok none)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Option ObjectParityState) (core.convert.FromSame ParityError) residual

end parity_state_verif
