-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aead_framing_verif]: function definitions
import Aeneas
import AeadFraming.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AeadFraming

/-- [aead_framing_verif::RAO_HEADER_LEN]
    Source: 'src/lib.rs', lines 11:0-11:36
    Visibility: public -/
@[global_simps, irreducible] def RAO_HEADER_LEN : Std.U64 := 128#u64

/-- [aead_framing_verif::RAO_FOOTER_LEN]
    Source: 'src/lib.rs', lines 12:0-12:35
    Visibility: public -/
@[global_simps, irreducible] def RAO_FOOTER_LEN : Std.U64 := 16#u64

/-- [aead_framing_verif::CHACHA20POLY1305_TAG_LEN]
    Source: 'src/lib.rs', lines 13:0-13:45
    Visibility: public -/
@[global_simps, irreducible] def CHACHA20POLY1305_TAG_LEN : Std.U64 := 16#u64

/-- [aead_framing_verif::CHUNK_SIZE_GRANULARITY]
    Source: 'src/lib.rs', lines 14:0-14:44
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_SIZE_GRANULARITY : Std.U64 := 512#u64

/-- [aead_framing_verif::{impl core::clone::Clone for aead_framing_verif::AeadFrameError}::clone]:
    Source: 'src/lib.rs', lines 16:9-16:14
    Visibility: public -/
def AeadFrameError.Insts.CoreCloneClone.clone
  (self : AeadFrameError) : Result AeadFrameError := do
  ok self

/-- Trait implementation: [aead_framing_verif::{impl core::clone::Clone for aead_framing_verif::AeadFrameError}]
    Source: 'src/lib.rs', lines 16:9-16:14 -/
@[reducible]
def AeadFrameError.Insts.CoreCloneClone : core.clone.Clone AeadFrameError := {
  clone := AeadFrameError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [aead_framing_verif::{impl core::marker::Copy for aead_framing_verif::AeadFrameError}]
    Source: 'src/lib.rs', lines 16:16-16:20 -/
@[reducible]
def AeadFrameError.Insts.CoreMarkerCopy : core.marker.Copy AeadFrameError := {
  cloneInst := AeadFrameError.Insts.CoreCloneClone
}

/-- [aead_framing_verif::{impl core::fmt::Debug for aead_framing_verif::AeadFrameError}::fmt]:
    Source: 'src/lib.rs', lines 16:22-16:27
    Visibility: public -/
def AeadFrameError.Insts.CoreFmtDebug.fmt
  (self : AeadFrameError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | AeadFrameError.InvalidChunkSize =>
    core.fmt.Formatter.write_str f (toStr "InvalidChunkSize")
  | AeadFrameError.InvalidMetadataField =>
    core.fmt.Formatter.write_str f (toStr "InvalidMetadataField")
  | AeadFrameError.SizeOverflow =>
    core.fmt.Formatter.write_str f (toStr "SizeOverflow")
  | AeadFrameError.PlaintextRangeOverflow =>
    core.fmt.Formatter.write_str f (toStr "PlaintextRangeOverflow")
  | AeadFrameError.EmptyRangeStartsPastEnd =>
    core.fmt.Formatter.write_str f (toStr "EmptyRangeStartsPastEnd")
  | AeadFrameError.PlaintextRangePastEnd =>
    core.fmt.Formatter.write_str f (toStr "PlaintextRangePastEnd")
  | AeadFrameError.UnexpectedEof =>
    core.fmt.Formatter.write_str f (toStr "UnexpectedEof")
  | AeadFrameError.TrailingData =>
    core.fmt.Formatter.write_str f (toStr "TrailingData")

/-- Trait implementation: [aead_framing_verif::{impl core::fmt::Debug for aead_framing_verif::AeadFrameError}]
    Source: 'src/lib.rs', lines 16:22-16:27 -/
@[reducible]
def AeadFrameError.Insts.CoreFmtDebug : core.fmt.Debug AeadFrameError := {
  fmt := AeadFrameError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [aead_framing_verif::{impl core::marker::StructuralPartialEq for aead_framing_verif::AeadFrameError}]
    Source: 'src/lib.rs', lines 16:29-16:38 -/
@[reducible]
def AeadFrameError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq AeadFrameError := {
}

/-- [aead_framing_verif::{impl core::cmp::PartialEq<aead_framing_verif::AeadFrameError> for aead_framing_verif::AeadFrameError}::eq]:
    Source: 'src/lib.rs', lines 16:29-16:38
    Visibility: public -/
def AeadFrameError.Insts.CoreCmpPartialEqAeadFrameError.eq
  (self : AeadFrameError) (other : AeadFrameError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [aead_framing_verif::{impl core::cmp::PartialEq<aead_framing_verif::AeadFrameError> for aead_framing_verif::AeadFrameError}]
    Source: 'src/lib.rs', lines 16:29-16:38 -/
@[reducible]
def AeadFrameError.Insts.CoreCmpPartialEqAeadFrameError : core.cmp.PartialEq
  AeadFrameError AeadFrameError := {
  eq := AeadFrameError.Insts.CoreCmpPartialEqAeadFrameError.eq
}

/-- [aead_framing_verif::{impl core::cmp::Eq for aead_framing_verif::AeadFrameError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 16:40-16:42
    Visibility: public -/
def AeadFrameError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : AeadFrameError) : Result Unit := do
  ok ()

/-- Trait implementation: [aead_framing_verif::{impl core::cmp::Eq for aead_framing_verif::AeadFrameError}]
    Source: 'src/lib.rs', lines 16:40-16:42 -/
@[reducible]
def AeadFrameError.Insts.CoreCmpEq : core.cmp.Eq AeadFrameError := {
  partialEqInst := AeadFrameError.Insts.CoreCmpPartialEqAeadFrameError
  assert_fields_are_eq := AeadFrameError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [aead_framing_verif::{impl core::clone::Clone for aead_framing_verif::RangePlan}::clone]:
    Source: 'src/lib.rs', lines 28:9-28:14
    Visibility: public -/
def RangePlan.Insts.CoreCloneClone.clone
  (self : RangePlan) : Result RangePlan := do
  ok self

/-- Trait implementation: [aead_framing_verif::{impl core::clone::Clone for aead_framing_verif::RangePlan}]
    Source: 'src/lib.rs', lines 28:9-28:14 -/
@[reducible]
def RangePlan.Insts.CoreCloneClone : core.clone.Clone RangePlan := {
  clone := RangePlan.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [aead_framing_verif::{impl core::marker::Copy for aead_framing_verif::RangePlan}]
    Source: 'src/lib.rs', lines 28:16-28:20 -/
@[reducible]
def RangePlan.Insts.CoreMarkerCopy : core.marker.Copy RangePlan := {
  cloneInst := RangePlan.Insts.CoreCloneClone
}

/-- [aead_framing_verif::{impl core::fmt::Debug for aead_framing_verif::RangePlan}::fmt]:
    Source: 'src/lib.rs', lines 28:22-28:27
    Visibility: public -/
def RangePlan.Insts.CoreFmtDebug.fmt
  (self : RangePlan) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.plaintext_end
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.first_chunk
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.last_chunk
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.fetched_chunk_count
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.stored_range_start
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.stored_range_len
  let dyn6 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.trim_start
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "plaintext_end", toStr "first_chunk", toStr "last_chunk", toStr
        "fetched_chunk_count", toStr "stored_range_start", toStr
        "stored_range_len", toStr "trim_start"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "RangePlan") s values

/-- Trait implementation: [aead_framing_verif::{impl core::fmt::Debug for aead_framing_verif::RangePlan}]
    Source: 'src/lib.rs', lines 28:22-28:27 -/
@[reducible]
def RangePlan.Insts.CoreFmtDebug : core.fmt.Debug RangePlan := {
  fmt := RangePlan.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [aead_framing_verif::{impl core::marker::StructuralPartialEq for aead_framing_verif::RangePlan}]
    Source: 'src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def RangePlan.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RangePlan := {
}

/-- [aead_framing_verif::{impl core::cmp::PartialEq<aead_framing_verif::RangePlan> for aead_framing_verif::RangePlan}::eq]:
    Source: 'src/lib.rs', lines 28:29-28:38
    Visibility: public -/
def RangePlan.Insts.CoreCmpPartialEqRangePlan.eq
  (self : RangePlan) (other : RangePlan) : Result Bool := do
  if self.plaintext_end = other.plaintext_end
  then
    if self.first_chunk = other.first_chunk
    then
      if self.last_chunk = other.last_chunk
      then
        if self.fetched_chunk_count = other.fetched_chunk_count
        then
          if self.stored_range_start = other.stored_range_start
          then
            if self.stored_range_len = other.stored_range_len
            then ok (self.trim_start = other.trim_start)
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [aead_framing_verif::{impl core::cmp::PartialEq<aead_framing_verif::RangePlan> for aead_framing_verif::RangePlan}]
    Source: 'src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def RangePlan.Insts.CoreCmpPartialEqRangePlan : core.cmp.PartialEq RangePlan
  RangePlan := {
  eq := RangePlan.Insts.CoreCmpPartialEqRangePlan.eq
}

/-- [aead_framing_verif::{impl core::cmp::Eq for aead_framing_verif::RangePlan}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 28:40-28:42
    Visibility: public -/
def RangePlan.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RangePlan) : Result Unit := do
  ok ()

/-- Trait implementation: [aead_framing_verif::{impl core::cmp::Eq for aead_framing_verif::RangePlan}]
    Source: 'src/lib.rs', lines 28:40-28:42 -/
@[reducible]
def RangePlan.Insts.CoreCmpEq : core.cmp.Eq RangePlan := {
  partialEqInst := RangePlan.Insts.CoreCmpPartialEqRangePlan
  assert_fields_are_eq := RangePlan.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [aead_framing_verif::{impl core::clone::Clone for aead_framing_verif::InspectGeometry}::clone]:
    Source: 'src/lib.rs', lines 39:9-39:14
    Visibility: public -/
def InspectGeometry.Insts.CoreCloneClone.clone
  (self : InspectGeometry) : Result InspectGeometry := do
  ok self

/-- Trait implementation: [aead_framing_verif::{impl core::clone::Clone for aead_framing_verif::InspectGeometry}]
    Source: 'src/lib.rs', lines 39:9-39:14 -/
@[reducible]
def InspectGeometry.Insts.CoreCloneClone : core.clone.Clone InspectGeometry
  := {
  clone := InspectGeometry.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [aead_framing_verif::{impl core::marker::Copy for aead_framing_verif::InspectGeometry}]
    Source: 'src/lib.rs', lines 39:16-39:20 -/
@[reducible]
def InspectGeometry.Insts.CoreMarkerCopy : core.marker.Copy InspectGeometry
  := {
  cloneInst := InspectGeometry.Insts.CoreCloneClone
}

/-- [aead_framing_verif::{impl core::fmt::Debug for aead_framing_verif::InspectGeometry}::fmt]:
    Source: 'src/lib.rs', lines 39:22-39:27
    Visibility: public -/
def InspectGeometry.Insts.CoreFmtDebug.fmt
  (self : InspectGeometry) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.stride
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.numerator
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.chunk_count
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.plaintext_size
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.footer_offset
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.expected_stored_size
  let dyn6 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.fill_len
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "stride", toStr "numerator", toStr "chunk_count", toStr
        "plaintext_size", toStr "footer_offset", toStr "expected_stored_size",
        toStr "fill_len"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "InspectGeometry") s
    values

/-- Trait implementation: [aead_framing_verif::{impl core::fmt::Debug for aead_framing_verif::InspectGeometry}]
    Source: 'src/lib.rs', lines 39:22-39:27 -/
@[reducible]
def InspectGeometry.Insts.CoreFmtDebug : core.fmt.Debug InspectGeometry := {
  fmt := InspectGeometry.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [aead_framing_verif::{impl core::marker::StructuralPartialEq for aead_framing_verif::InspectGeometry}]
    Source: 'src/lib.rs', lines 39:29-39:38 -/
@[reducible]
def InspectGeometry.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq InspectGeometry := {
}

/-- [aead_framing_verif::{impl core::cmp::PartialEq<aead_framing_verif::InspectGeometry> for aead_framing_verif::InspectGeometry}::eq]:
    Source: 'src/lib.rs', lines 39:29-39:38
    Visibility: public -/
def InspectGeometry.Insts.CoreCmpPartialEqInspectGeometry.eq
  (self : InspectGeometry) (other : InspectGeometry) : Result Bool := do
  if self.stride = other.stride
  then
    if self.numerator = other.numerator
    then
      if self.chunk_count = other.chunk_count
      then
        if self.plaintext_size = other.plaintext_size
        then
          if self.footer_offset = other.footer_offset
          then
            if self.expected_stored_size = other.expected_stored_size
            then ok (self.fill_len = other.fill_len)
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [aead_framing_verif::{impl core::cmp::PartialEq<aead_framing_verif::InspectGeometry> for aead_framing_verif::InspectGeometry}]
    Source: 'src/lib.rs', lines 39:29-39:38 -/
@[reducible]
def InspectGeometry.Insts.CoreCmpPartialEqInspectGeometry : core.cmp.PartialEq
  InspectGeometry InspectGeometry := {
  eq := InspectGeometry.Insts.CoreCmpPartialEqInspectGeometry.eq
}

/-- [aead_framing_verif::{impl core::cmp::Eq for aead_framing_verif::InspectGeometry}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 39:40-39:42
    Visibility: public -/
def InspectGeometry.Insts.CoreCmpEq.assert_fields_are_eq
  (self : InspectGeometry) : Result Unit := do
  ok ()

/-- Trait implementation: [aead_framing_verif::{impl core::cmp::Eq for aead_framing_verif::InspectGeometry}]
    Source: 'src/lib.rs', lines 39:40-39:42 -/
@[reducible]
def InspectGeometry.Insts.CoreCmpEq : core.cmp.Eq InspectGeometry := {
  partialEqInst := InspectGeometry.Insts.CoreCmpPartialEqInspectGeometry
  assert_fields_are_eq := InspectGeometry.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [aead_framing_verif::checked_add]:
    Source: 'src/lib.rs', lines 50:0-55:1
    Visibility: public -/
def checked_add
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let o ← lift (U64.checked_add a b)
  match o with
  | none => ok (core.result.Result.Err AeadFrameError.SizeOverflow)
  | some sum => ok (core.result.Result.Ok sum)

/-- [aead_framing_verif::checked_sub]:
    Source: 'src/lib.rs', lines 57:0-62:1
    Visibility: public -/
def checked_sub
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let o ← lift (U64.checked_sub a b)
  match o with
  | none => ok (core.result.Result.Err AeadFrameError.SizeOverflow)
  | some diff => ok (core.result.Result.Ok diff)

/-- [aead_framing_verif::checked_mul]:
    Source: 'src/lib.rs', lines 64:0-69:1
    Visibility: public -/
def checked_mul
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let o ← lift (U64.checked_mul a b)
  match o with
  | none => ok (core.result.Result.Err AeadFrameError.SizeOverflow)
  | some product => ok (core.result.Result.Ok product)

/-- [aead_framing_verif::validate_chunk_size]:
    Source: 'src/lib.rs', lines 71:0-76:1
    Visibility: public -/
def validate_chunk_size
  (chunk_size : Std.U64) :
  Result (core.result.Result Unit AeadFrameError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err AeadFrameError.InvalidChunkSize)
  else
    let i ← chunk_size % CHUNK_SIZE_GRANULARITY
    if i != 0#u64
    then ok (core.result.Result.Err AeadFrameError.InvalidChunkSize)
    else ok (core.result.Result.Ok ())

/-- [aead_framing_verif::chunk_count]:
    Source: 'src/lib.rs', lines 78:0-83:1
    Visibility: public -/
def chunk_count
  (plaintext_size : Std.U64) (chunk_size : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err AeadFrameError.InvalidMetadataField)
  else
    if plaintext_size = 0#u64
    then ok (core.result.Result.Err AeadFrameError.InvalidMetadataField)
    else
      let i ← plaintext_size % chunk_size
      if i != 0#u64
      then ok (core.result.Result.Err AeadFrameError.InvalidMetadataField)
      else let i1 ← plaintext_size / chunk_size
           ok (core.result.Result.Ok i1)

/-- [aead_framing_verif::payload_frame_len]:
    Source: 'src/lib.rs', lines 85:0-89:1
    Visibility: public -/
def payload_frame_len
  (plaintext_size : Std.U64) (chunk_size : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let r ← chunk_count plaintext_size chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← checked_mul CHACHA20POLY1305_TAG_LEN val
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      checked_add plaintext_size val1
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame AeadFrameError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame AeadFrameError) residual

/-- [aead_framing_verif::round_up]:
    Source: 'src/lib.rs', lines 91:0-101:1
    Visibility: public -/
def round_up
  (value : Std.U64) (multiple : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  if multiple = 0#u64
  then ok (core.result.Result.Err AeadFrameError.SizeOverflow)
  else
    let remainder ← value % multiple
    if remainder = 0#u64
    then ok (core.result.Result.Ok value)
    else let i ← multiple - remainder
         checked_add value i

/-- [aead_framing_verif::stored_size_from_parts]:
    Source: 'src/lib.rs', lines 103:0-113:1
    Visibility: public -/
def stored_size_from_parts
  (chunk_size : Std.U64) (metadata_frame_len : Std.U64)
  (plaintext_size : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let r ← payload_frame_len plaintext_size chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← checked_add RAO_HEADER_LEN metadata_frame_len
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r2 ← checked_add val1 val
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let r3 ← checked_add val2 RAO_FOOTER_LEN
        let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
        match cf3 with
        | core.ops.control_flow.ControlFlow.Continue val3 =>
          round_up val3 chunk_size
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame AeadFrameError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame AeadFrameError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame AeadFrameError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame AeadFrameError) residual

/-- [aead_framing_verif::expected_stored_size]:
    Source: 'src/lib.rs', lines 115:0-121:1
    Visibility: public -/
def expected_stored_size
  (chunk_size : Std.U64) (metadata_frame_len : Std.U64)
  (plaintext_size : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  stored_size_from_parts chunk_size metadata_frame_len plaintext_size

/-- [aead_framing_verif::cipher_offset]:
    Source: 'src/lib.rs', lines 123:0-132:1
    Visibility: public -/
def cipher_offset
  (metadata_frame_len : Std.U64) (chunk_size : Std.U64) (block_index : Std.U64)
  :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let r ← checked_add chunk_size CHACHA20POLY1305_TAG_LEN
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← checked_add RAO_HEADER_LEN metadata_frame_len
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let r2 ← checked_mul block_index val
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        checked_add val1 val2
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Std.U64 (core.convert.FromSame AeadFrameError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame AeadFrameError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame AeadFrameError) residual

/-- [aead_framing_verif::validate_range]:
    Source: 'src/lib.rs', lines 134:0-149:1
    Visibility: public -/
def validate_range
  (start : Std.U64) (len : Std.U64) (plaintext_size : Std.U64) :
  Result (core.result.Result Std.U64 AeadFrameError)
  := do
  let o ← lift (U64.checked_add start len)
  match o with
  | none => ok (core.result.Result.Err AeadFrameError.PlaintextRangeOverflow)
  | some end1 =>
    if len = 0#u64
    then
      if start > plaintext_size
      then ok (core.result.Result.Err AeadFrameError.EmptyRangeStartsPastEnd)
      else ok (core.result.Result.Ok end1)
    else
      if end1 > plaintext_size
      then ok (core.result.Result.Err AeadFrameError.PlaintextRangePastEnd)
      else ok (core.result.Result.Ok end1)

/-- [aead_framing_verif::nonempty_range_plan]:
    Source: 'src/lib.rs', lines 151:0-187:1
    Visibility: public -/
def nonempty_range_plan
  (metadata_frame_len : Std.U64) (chunk_size : Std.U64)
  (plaintext_size : Std.U64) (plaintext_start : Std.U64)
  (plaintext_len : Std.U64) :
  Result (core.result.Result RangePlan AeadFrameError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err AeadFrameError.InvalidChunkSize)
  else
    let r ← validate_range plaintext_start plaintext_len plaintext_size
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if plaintext_len = 0#u64
      then ok (core.result.Result.Err AeadFrameError.InvalidMetadataField)
      else
        let first_chunk ← plaintext_start / chunk_size
        let r1 ← checked_sub val 1#u64
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          let last_chunk ← val1 / chunk_size
          let r2 ← checked_sub last_chunk first_chunk
          let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue val2 =>
            let r3 ← checked_add val2 1#u64
            let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
            match cf3 with
            | core.ops.control_flow.ControlFlow.Continue val3 =>
              let r4 ← checked_add chunk_size CHACHA20POLY1305_TAG_LEN
              let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
              match cf4 with
              | core.ops.control_flow.ControlFlow.Continue val4 =>
                let r5 ←
                  cipher_offset metadata_frame_len chunk_size first_chunk
                let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                match cf5 with
                | core.ops.control_flow.ControlFlow.Continue val5 =>
                  let r6 ←
                    cipher_offset metadata_frame_len chunk_size last_chunk
                  let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                  match cf6 with
                  | core.ops.control_flow.ControlFlow.Continue val6 =>
                    let r7 ← checked_add val6 val4
                    let cf7 ← core.result.Result.Insts.CoreOpsTry.branch r7
                    match cf7 with
                    | core.ops.control_flow.ControlFlow.Continue val7 =>
                      let r8 ← checked_sub val7 val5
                      let cf8 ← core.result.Result.Insts.CoreOpsTry.branch r8
                      match cf8 with
                      | core.ops.control_flow.ControlFlow.Continue val8 =>
                        let trim_start ← plaintext_start % chunk_size
                        ok (core.result.Result.Ok
                          {
                            plaintext_end := val,
                            first_chunk,
                            last_chunk,
                            fetched_chunk_count := val3,
                            stored_range_start := val5,
                            stored_range_len := val8,
                            trim_start
                          })
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          RangePlan (core.convert.FromSame AeadFrameError)
                          residual
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        RangePlan (core.convert.FromSame AeadFrameError)
                        residual
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      RangePlan (core.convert.FromSame AeadFrameError) residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    RangePlan (core.convert.FromSame AeadFrameError) residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  RangePlan (core.convert.FromSame AeadFrameError) residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                RangePlan (core.convert.FromSame AeadFrameError) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              RangePlan (core.convert.FromSame AeadFrameError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            RangePlan (core.convert.FromSame AeadFrameError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        RangePlan (core.convert.FromSame AeadFrameError) residual

/-- [aead_framing_verif::inspect_geometry]:
    Source: 'src/lib.rs', lines 189:0-241:1
    Visibility: public -/
def inspect_geometry
  (stored_size_bytes : Std.U64) (metadata_frame_len : Std.U64)
  (chunk_size : Std.U64) :
  Result (core.result.Result InspectGeometry AeadFrameError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err AeadFrameError.InvalidChunkSize)
  else
    let i ← stored_size_bytes % chunk_size
    if i != 0#u64
    then ok (core.result.Result.Err AeadFrameError.TrailingData)
    else
      let r ← checked_add RAO_HEADER_LEN RAO_FOOTER_LEN
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let r1 ← checked_add val metadata_frame_len
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          if stored_size_bytes < val1
          then ok (core.result.Result.Err AeadFrameError.UnexpectedEof)
          else
            let r2 ← checked_add chunk_size CHACHA20POLY1305_TAG_LEN
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let i1 ← RAO_HEADER_LEN + RAO_FOOTER_LEN
              let o ← lift (U64.checked_sub stored_size_bytes i1)
              match o with
              | none =>
                ok (core.result.Result.Err AeadFrameError.UnexpectedEof)
              | some value =>
                let o1 ← lift (U64.checked_sub value metadata_frame_len)
                match o1 with
                | none =>
                  ok (core.result.Result.Err AeadFrameError.UnexpectedEof)
                | some value1 =>
                  let chunk_count1 ← value1 / val2
                  if chunk_count1 = 0#u64
                  then ok (core.result.Result.Err AeadFrameError.UnexpectedEof)
                  else
                    let r3 ← checked_mul chunk_count1 chunk_size
                    let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
                    match cf3 with
                    | core.ops.control_flow.ControlFlow.Continue val3 =>
                      let r4 ← checked_mul chunk_count1 val2
                      let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                      match cf4 with
                      | core.ops.control_flow.ControlFlow.Continue val4 =>
                        let r5 ←
                          checked_add RAO_HEADER_LEN metadata_frame_len
                        let cf5 ←
                          core.result.Result.Insts.CoreOpsTry.branch r5
                        match cf5 with
                        | core.ops.control_flow.ControlFlow.Continue val5 =>
                          let r6 ← checked_add val5 val4
                          let cf6 ←
                            core.result.Result.Insts.CoreOpsTry.branch r6
                          match cf6 with
                          | core.ops.control_flow.ControlFlow.Continue val6 =>
                            let r7 ← checked_add val6 RAO_FOOTER_LEN
                            let cf7 ←
                              core.result.Result.Insts.CoreOpsTry.branch r7
                            match cf7 with
                            | core.ops.control_flow.ControlFlow.Continue val7
                              =>
                              let r8 ← round_up val7 chunk_size
                              let cf8 ←
                                core.result.Result.Insts.CoreOpsTry.branch r8
                              match cf8 with
                              | core.ops.control_flow.ControlFlow.Continue val8
                                =>
                                if val8 != stored_size_bytes
                                then
                                  ok (core.result.Result.Err
                                    AeadFrameError.TrailingData)
                                else
                                  let r9 ← checked_sub val8 val7
                                  let cf9 ←
                                    core.result.Result.Insts.CoreOpsTry.branch
                                      r9
                                  match cf9 with
                                  | core.ops.control_flow.ControlFlow.Continue
                                    val9 =>
                                    ok (core.result.Result.Ok
                                      {
                                        stride := val2,
                                        numerator := value1,
                                        chunk_count := chunk_count1,
                                        plaintext_size := val3,
                                        footer_offset := val6,
                                        expected_stored_size := val8,
                                        fill_len := val9
                                      })
                                  | core.ops.control_flow.ControlFlow.Break
                                    residual =>
                                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                      InspectGeometry (core.convert.FromSame
                                      AeadFrameError) residual
                              | core.ops.control_flow.ControlFlow.Break
                                residual =>
                                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                  InspectGeometry (core.convert.FromSame
                                  AeadFrameError) residual
                            | core.ops.control_flow.ControlFlow.Break residual
                              =>
                              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                InspectGeometry (core.convert.FromSame
                                AeadFrameError) residual
                          | core.ops.control_flow.ControlFlow.Break residual =>
                            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                              InspectGeometry (core.convert.FromSame
                              AeadFrameError) residual
                        | core.ops.control_flow.ControlFlow.Break residual =>
                          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                            InspectGeometry (core.convert.FromSame
                            AeadFrameError) residual
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          InspectGeometry (core.convert.FromSame
                          AeadFrameError) residual
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        InspectGeometry (core.convert.FromSame AeadFrameError)
                        residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                InspectGeometry (core.convert.FromSame AeadFrameError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            InspectGeometry (core.convert.FromSame AeadFrameError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          InspectGeometry (core.convert.FromSame AeadFrameError) residual

end AeadFraming
