-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aead_framing_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AeadFraming

/-- [aead_framing_verif::AeadFrameError]
    Source: 'src/lib.rs', lines 17:0-26:1
    Visibility: public -/
@[discriminant isize]
inductive AeadFrameError where
| InvalidChunkSize : AeadFrameError
| InvalidMetadataField : AeadFrameError
| SizeOverflow : AeadFrameError
| PlaintextRangeOverflow : AeadFrameError
| EmptyRangeStartsPastEnd : AeadFrameError
| PlaintextRangePastEnd : AeadFrameError
| UnexpectedEof : AeadFrameError
| TrailingData : AeadFrameError

/-- [aead_framing_verif::RangePlan]
    Source: 'src/lib.rs', lines 29:0-37:1
    Visibility: public -/
structure RangePlan where
  plaintext_end : Std.U64
  first_chunk : Std.U64
  last_chunk : Std.U64
  fetched_chunk_count : Std.U64
  stored_range_start : Std.U64
  stored_range_len : Std.U64
  trim_start : Std.U64

/-- [aead_framing_verif::InspectGeometry]
    Source: 'src/lib.rs', lines 40:0-48:1
    Visibility: public -/
structure InspectGeometry where
  stride : Std.U64
  numerator : Std.U64
  chunk_count : Std.U64
  plaintext_size : Std.U64
  footer_offset : Std.U64
  expected_stored_size : Std.U64
  fill_len : Std.U64

end AeadFraming
