-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [parity_sidecar_layout_verif]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace parity_sidecar_layout_verif

/-- [parity_sidecar_layout_verif::SIDECAR_HEADER_LEN]
    Source: 'src/lib.rs', lines 10:0-10:41
    Visibility: public -/
@[global_simps, irreducible] def SIDECAR_HEADER_LEN : Std.U64 := 184#u64

/-- [parity_sidecar_layout_verif::SIDECAR_HEADER_CRC_OFFSET]
    Source: 'src/lib.rs', lines 11:0-11:48
    Visibility: public -/
@[global_simps, irreducible] def SIDECAR_HEADER_CRC_OFFSET : Std.U64 := 176#u64

/-- [parity_sidecar_layout_verif::SIDECAR_FOOTER_LEN]
    Source: 'src/lib.rs', lines 12:0-12:41
    Visibility: public -/
@[global_simps, irreducible] def SIDECAR_FOOTER_LEN : Std.U64 := 128#u64

/-- [parity_sidecar_layout_verif::SIDECAR_FOOTER_CRC_OFFSET]
    Source: 'src/lib.rs', lines 13:0-13:48
    Visibility: public -/
@[global_simps, irreducible] def SIDECAR_FOOTER_CRC_OFFSET : Std.U64 := 120#u64

/-- [parity_sidecar_layout_verif::PARITY_INDEX_ENTRY_LEN]
    Source: 'src/lib.rs', lines 14:0-14:43
    Visibility: public -/
@[global_simps, irreducible] def PARITY_INDEX_ENTRY_LEN : Std.U64 := 16#u64

/-- [parity_sidecar_layout_verif::DATA_CRC_ENTRY_LEN]
    Source: 'src/lib.rs', lines 15:0-15:38
    Visibility: public -/
@[global_simps, irreducible] def DATA_CRC_ENTRY_LEN : Std.U64 := 8#u64

/-- [parity_sidecar_layout_verif::TRAILING_CRC_LEN]
    Source: 'src/lib.rs', lines 16:0-16:36
    Visibility: public -/
@[global_simps, irreducible] def TRAILING_CRC_LEN : Std.U64 := 8#u64

/-- [parity_sidecar_layout_verif::MIN_HEADER_BLOCK_SIZE]
    Source: 'src/lib.rs', lines 18:0-18:44
    Visibility: public -/
@[global_simps, irreducible] def MIN_HEADER_BLOCK_SIZE : Std.U64 := 192#u64

/-- [parity_sidecar_layout_verif::LayoutError]
    Source: 'src/lib.rs', lines 21:0-25:1
    Visibility: public -/
@[discriminant isize]
inductive LayoutError where
| BlockTooSmall : LayoutError
| HeaderBlockCountZero : LayoutError
| ArithmeticOverflow : LayoutError

/-- [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::LayoutError}::clone]:
    Source: 'src/lib.rs', lines 20:9-20:14
    Visibility: public -/
def LayoutError.Insts.CoreCloneClone.clone
  (self : LayoutError) : Result LayoutError := do
  ok self

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::LayoutError}]
    Source: 'src/lib.rs', lines 20:9-20:14 -/
@[reducible]
def LayoutError.Insts.CoreCloneClone : core.clone.Clone LayoutError := {
  clone := LayoutError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::Copy for parity_sidecar_layout_verif::LayoutError}]
    Source: 'src/lib.rs', lines 20:16-20:20 -/
@[reducible]
def LayoutError.Insts.CoreMarkerCopy : core.marker.Copy LayoutError := {
  cloneInst := LayoutError.Insts.CoreCloneClone
}

/-- [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::LayoutError}::fmt]:
    Source: 'src/lib.rs', lines 20:22-20:27
    Visibility: public -/
def LayoutError.Insts.CoreFmtDebug.fmt
  (self : LayoutError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | LayoutError.BlockTooSmall =>
    core.fmt.Formatter.write_str f (toStr "BlockTooSmall")
  | LayoutError.HeaderBlockCountZero =>
    core.fmt.Formatter.write_str f (toStr "HeaderBlockCountZero")
  | LayoutError.ArithmeticOverflow =>
    core.fmt.Formatter.write_str f (toStr "ArithmeticOverflow")

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::LayoutError}]
    Source: 'src/lib.rs', lines 20:22-20:27 -/
@[reducible]
def LayoutError.Insts.CoreFmtDebug : core.fmt.Debug LayoutError := {
  fmt := LayoutError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::StructuralPartialEq for parity_sidecar_layout_verif::LayoutError}]
    Source: 'src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def LayoutError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq LayoutError := {
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::LayoutError> for parity_sidecar_layout_verif::LayoutError}::eq]:
    Source: 'src/lib.rs', lines 20:29-20:38
    Visibility: public -/
def LayoutError.Insts.CoreCmpPartialEqLayoutError.eq
  (self : LayoutError) (other : LayoutError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::LayoutError> for parity_sidecar_layout_verif::LayoutError}]
    Source: 'src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def LayoutError.Insts.CoreCmpPartialEqLayoutError : core.cmp.PartialEq
  LayoutError LayoutError := {
  eq := LayoutError.Insts.CoreCmpPartialEqLayoutError.eq
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::LayoutError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 20:40-20:42
    Visibility: public -/
def LayoutError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : LayoutError) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::LayoutError}]
    Source: 'src/lib.rs', lines 20:40-20:42 -/
@[reducible]
def LayoutError.Insts.CoreCmpEq : core.cmp.Eq LayoutError := {
  partialEqInst := LayoutError.Insts.CoreCmpPartialEqLayoutError
  assert_fields_are_eq := LayoutError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_sidecar_layout_verif::ByteRange]
    Source: 'src/lib.rs', lines 28:0-31:1
    Visibility: public -/
structure ByteRange where
  start : Std.U64
  «end» : Std.U64

/-- [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::ByteRange}::clone]:
    Source: 'src/lib.rs', lines 27:9-27:14
    Visibility: public -/
def ByteRange.Insts.CoreCloneClone.clone
  (self : ByteRange) : Result ByteRange := do
  ok self

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::ByteRange}]
    Source: 'src/lib.rs', lines 27:9-27:14 -/
@[reducible]
def ByteRange.Insts.CoreCloneClone : core.clone.Clone ByteRange := {
  clone := ByteRange.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::Copy for parity_sidecar_layout_verif::ByteRange}]
    Source: 'src/lib.rs', lines 27:16-27:20 -/
@[reducible]
def ByteRange.Insts.CoreMarkerCopy : core.marker.Copy ByteRange := {
  cloneInst := ByteRange.Insts.CoreCloneClone
}

/-- [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::ByteRange}::fmt]:
    Source: 'src/lib.rs', lines 27:22-27:27
    Visibility: public -/
def ByteRange.Insts.CoreFmtDebug.fmt
  (self : ByteRange) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.start
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.«end»
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "ByteRange") (toStr
    "start") dyn (toStr "end") dyn1

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::ByteRange}]
    Source: 'src/lib.rs', lines 27:22-27:27 -/
@[reducible]
def ByteRange.Insts.CoreFmtDebug : core.fmt.Debug ByteRange := {
  fmt := ByteRange.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::StructuralPartialEq for parity_sidecar_layout_verif::ByteRange}]
    Source: 'src/lib.rs', lines 27:29-27:38 -/
@[reducible]
def ByteRange.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ByteRange := {
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::ByteRange> for parity_sidecar_layout_verif::ByteRange}::eq]:
    Source: 'src/lib.rs', lines 27:29-27:38
    Visibility: public -/
def ByteRange.Insts.CoreCmpPartialEqByteRange.eq
  (self : ByteRange) (other : ByteRange) : Result Bool := do
  if self.start = other.start
  then ok (self.«end» = other.«end»)
  else ok false

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::ByteRange> for parity_sidecar_layout_verif::ByteRange}]
    Source: 'src/lib.rs', lines 27:29-27:38 -/
@[reducible]
def ByteRange.Insts.CoreCmpPartialEqByteRange : core.cmp.PartialEq ByteRange
  ByteRange := {
  eq := ByteRange.Insts.CoreCmpPartialEqByteRange.eq
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::ByteRange}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 27:40-27:42
    Visibility: public -/
def ByteRange.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ByteRange) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::ByteRange}]
    Source: 'src/lib.rs', lines 27:40-27:42 -/
@[reducible]
def ByteRange.Insts.CoreCmpEq : core.cmp.Eq ByteRange := {
  partialEqInst := ByteRange.Insts.CoreCmpPartialEqByteRange
  assert_fields_are_eq := ByteRange.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_sidecar_layout_verif::HeaderBlockLayout]
    Source: 'src/lib.rs', lines 34:0-65:1
    Visibility: public -/
structure HeaderBlockLayout where
  magic : ByteRange
  tape_uuid : ByteRange
  epoch_id : ByteRange
  k : ByteRange
  m : ByteRange
  stripes_per_epoch : ByteRange
  block_size : ByteRange
  schema_version : ByteRange
  protected_ordinal_start : ByteRange
  protected_ordinal_end_exclusive : ByteRange
  logical_shard_count : ByteRange
  real_data_shard_count : ByteRange
  parity_block_count : ByteRange
  data_crc_count : ByteRange
  shard_index_block_count : ByteRange
  inline_index_entry_bytes : ByteRange
  sidecar_total_block_count : ByteRange
  primary_header_start_block : ByteRange
  tail_header_start_block : ByteRange
  footer_block_index : ByteRange
  copy_kind : ByteRange
  copy_kind_reserved : ByteRange
  copy_generation : ByteRange
  canonical_metadata_hash : ByteRange
  header_reserved : ByteRange
  header_crc_field : ByteRange
  inline_index_payload : ByteRange
  header_crc_input : ByteRange
  block0_crc_input : ByteRange
  block0_crc_field : ByteRange

/-- [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::HeaderBlockLayout}::clone]:
    Source: 'src/lib.rs', lines 33:9-33:14
    Visibility: public -/
def HeaderBlockLayout.Insts.CoreCloneClone.clone
  (self : HeaderBlockLayout) : Result HeaderBlockLayout := do
  ok self

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::HeaderBlockLayout}]
    Source: 'src/lib.rs', lines 33:9-33:14 -/
@[reducible]
def HeaderBlockLayout.Insts.CoreCloneClone : core.clone.Clone HeaderBlockLayout
  := {
  clone := HeaderBlockLayout.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::Copy for parity_sidecar_layout_verif::HeaderBlockLayout}]
    Source: 'src/lib.rs', lines 33:16-33:20 -/
@[reducible]
def HeaderBlockLayout.Insts.CoreMarkerCopy : core.marker.Copy HeaderBlockLayout
  := {
  cloneInst := HeaderBlockLayout.Insts.CoreCloneClone
}

/-- [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::HeaderBlockLayout}::fmt]:
    Source: 'src/lib.rs', lines 33:22-33:27
    Visibility: public -/
def HeaderBlockLayout.Insts.CoreFmtDebug.fmt
  (self : HeaderBlockLayout) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.magic
  let dyn1 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.tape_uuid
  let dyn2 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.epoch_id
  let dyn3 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.k
  let dyn4 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.m
  let dyn5 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.stripes_per_epoch
  let dyn6 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.block_size
  let dyn7 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.schema_version
  let dyn8 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.protected_ordinal_start
  let dyn9 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.protected_ordinal_end_exclusive
  let dyn10 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.logical_shard_count
  let dyn11 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.real_data_shard_count
  let dyn12 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.parity_block_count
  let dyn13 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.data_crc_count
  let dyn14 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.shard_index_block_count
  let dyn15 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.inline_index_entry_bytes
  let dyn16 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.sidecar_total_block_count
  let dyn17 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.primary_header_start_block
  let dyn18 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.tail_header_start_block
  let dyn19 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.footer_block_index
  let dyn20 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.copy_kind
  let dyn21 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.copy_kind_reserved
  let dyn22 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.copy_generation
  let dyn23 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.canonical_metadata_hash
  let dyn24 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.header_reserved
  let dyn25 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.header_crc_field
  let dyn26 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.inline_index_payload
  let dyn27 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.header_crc_input
  let dyn28 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.block0_crc_input
  let dyn29 :=
    Dyn.mk _ (core.fmt.DebugShared ByteRange.Insts.CoreFmtDebug)
      self.block0_crc_field
  let values :=
    Array.to_slice
      (Array.make 30#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15, dyn16, dyn17, dyn18, dyn19, dyn20,
        dyn21, dyn22, dyn23, dyn24, dyn25, dyn26, dyn27, dyn28, dyn29
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 30#usize [
        toStr "magic", toStr "tape_uuid", toStr "epoch_id", toStr "k", toStr
        "m", toStr "stripes_per_epoch", toStr "block_size", toStr
        "schema_version", toStr "protected_ordinal_start", toStr
        "protected_ordinal_end_exclusive", toStr "logical_shard_count", toStr
        "real_data_shard_count", toStr "parity_block_count", toStr
        "data_crc_count", toStr "shard_index_block_count", toStr
        "inline_index_entry_bytes", toStr "sidecar_total_block_count", toStr
        "primary_header_start_block", toStr "tail_header_start_block", toStr
        "footer_block_index", toStr "copy_kind", toStr "copy_kind_reserved",
        toStr "copy_generation", toStr "canonical_metadata_hash", toStr
        "header_reserved", toStr "header_crc_field", toStr
        "inline_index_payload", toStr "header_crc_input", toStr
        "block0_crc_input", toStr "block0_crc_field"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "HeaderBlockLayout") s
    values

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::HeaderBlockLayout}]
    Source: 'src/lib.rs', lines 33:22-33:27 -/
@[reducible]
def HeaderBlockLayout.Insts.CoreFmtDebug : core.fmt.Debug HeaderBlockLayout
  := {
  fmt := HeaderBlockLayout.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::StructuralPartialEq for parity_sidecar_layout_verif::HeaderBlockLayout}]
    Source: 'src/lib.rs', lines 33:29-33:38 -/
@[reducible]
def HeaderBlockLayout.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq HeaderBlockLayout := {
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::HeaderBlockLayout> for parity_sidecar_layout_verif::HeaderBlockLayout}::eq]:
    Source: 'src/lib.rs', lines 33:29-33:38
    Visibility: public -/
def HeaderBlockLayout.Insts.CoreCmpPartialEqHeaderBlockLayout.eq
  (self : HeaderBlockLayout) (other : HeaderBlockLayout) : Result Bool := do
  let b ← ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.magic other.magic
  if b
  then
    let b1 ←
      ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.tape_uuid
        other.tape_uuid
    if b1
    then
      let b2 ←
        ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.epoch_id
          other.epoch_id
      if b2
      then
        let b3 ← ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.k other.k
        if b3
        then
          let b4 ←
            ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.m other.m
          if b4
          then
            let b5 ←
              ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                self.stripes_per_epoch other.stripes_per_epoch
            if b5
            then
              let b6 ←
                ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.block_size
                  other.block_size
              if b6
              then
                let b7 ←
                  ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                    self.schema_version other.schema_version
                if b7
                then
                  let b8 ←
                    ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                      self.protected_ordinal_start
                      other.protected_ordinal_start
                  if b8
                  then
                    let b9 ←
                      ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                        self.protected_ordinal_end_exclusive
                        other.protected_ordinal_end_exclusive
                    if b9
                    then
                      let b10 ←
                        ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                          self.logical_shard_count other.logical_shard_count
                      if b10
                      then
                        let b11 ←
                          ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                            self.real_data_shard_count
                            other.real_data_shard_count
                        if b11
                        then
                          let b12 ←
                            ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                              self.parity_block_count other.parity_block_count
                          if b12
                          then
                            let b13 ←
                              ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                self.data_crc_count other.data_crc_count
                            if b13
                            then
                              let b14 ←
                                ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                  self.shard_index_block_count
                                  other.shard_index_block_count
                              if b14
                              then
                                let b15 ←
                                  ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                    self.inline_index_entry_bytes
                                    other.inline_index_entry_bytes
                                if b15
                                then
                                  let b16 ←
                                    ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                      self.sidecar_total_block_count
                                      other.sidecar_total_block_count
                                  if b16
                                  then
                                    let b17 ←
                                      ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                        self.primary_header_start_block
                                        other.primary_header_start_block
                                    if b17
                                    then
                                      let b18 ←
                                        ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                          self.tail_header_start_block
                                          other.tail_header_start_block
                                      if b18
                                      then
                                        let b19 ←
                                          ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                            self.footer_block_index
                                            other.footer_block_index
                                        if b19
                                        then
                                          let b20 ←
                                            ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                              self.copy_kind other.copy_kind
                                          if b20
                                          then
                                            let b21 ←
                                              ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                self.copy_kind_reserved
                                                other.copy_kind_reserved
                                            if b21
                                            then
                                              let b22 ←
                                                ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                  self.copy_generation
                                                  other.copy_generation
                                              if b22
                                              then
                                                let b23 ←
                                                  ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                    self.canonical_metadata_hash
                                                    other.canonical_metadata_hash
                                                if b23
                                                then
                                                  let b24 ←
                                                    ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                      self.header_reserved
                                                      other.header_reserved
                                                  if b24
                                                  then
                                                    let b25 ←
                                                      ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                        self.header_crc_field
                                                        other.header_crc_field
                                                    if b25
                                                    then
                                                      let b26 ←
                                                        ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                          self.inline_index_payload
                                                          other.inline_index_payload
                                                      if b26
                                                      then
                                                        let b27 ←
                                                          ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                            self.header_crc_input
                                                            other.header_crc_input
                                                        if b27
                                                        then
                                                          let b28 ←
                                                            ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                              self.block0_crc_input
                                                              other.block0_crc_input
                                                          if b28
                                                          then
                                                            ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                                              self.block0_crc_field
                                                              other.block0_crc_field
                                                          else ok false
                                                        else ok false
                                                      else ok false
                                                    else ok false
                                                  else ok false
                                                else ok false
                                              else ok false
                                            else ok false
                                          else ok false
                                        else ok false
                                      else ok false
                                    else ok false
                                  else ok false
                                else ok false
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::HeaderBlockLayout> for parity_sidecar_layout_verif::HeaderBlockLayout}]
    Source: 'src/lib.rs', lines 33:29-33:38 -/
@[reducible]
def HeaderBlockLayout.Insts.CoreCmpPartialEqHeaderBlockLayout :
  core.cmp.PartialEq HeaderBlockLayout HeaderBlockLayout := {
  eq := HeaderBlockLayout.Insts.CoreCmpPartialEqHeaderBlockLayout.eq
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::HeaderBlockLayout}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 33:40-33:42
    Visibility: public -/
def HeaderBlockLayout.Insts.CoreCmpEq.assert_fields_are_eq
  (self : HeaderBlockLayout) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::HeaderBlockLayout}]
    Source: 'src/lib.rs', lines 33:40-33:42 -/
@[reducible]
def HeaderBlockLayout.Insts.CoreCmpEq : core.cmp.Eq HeaderBlockLayout := {
  partialEqInst := HeaderBlockLayout.Insts.CoreCmpPartialEqHeaderBlockLayout
  assert_fields_are_eq :=
    HeaderBlockLayout.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_sidecar_layout_verif::FooterBlockLayout]
    Source: 'src/lib.rs', lines 68:0-86:1
    Visibility: public -/
structure FooterBlockLayout where
  magic : ByteRange
  sidecar_footer_version : ByteRange
  reserved16 : ByteRange
  reserved32 : ByteRange
  tape_uuid : ByteRange
  epoch_id : ByteRange
  protected_ordinal_start : ByteRange
  protected_ordinal_end_exclusive : ByteRange
  sidecar_header_block_count : ByteRange
  parity_shard_block_count : ByteRange
  sidecar_total_block_count : ByteRange
  primary_header_start_block : ByteRange
  tail_header_start_block : ByteRange
  canonical_metadata_hash : ByteRange
  footer_crc_field : ByteRange
  footer_crc_input : ByteRange
  footer_padding : ByteRange

/-- [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::FooterBlockLayout}::clone]:
    Source: 'src/lib.rs', lines 67:9-67:14
    Visibility: public -/
def FooterBlockLayout.Insts.CoreCloneClone.clone
  (self : FooterBlockLayout) : Result FooterBlockLayout := do
  ok self

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::FooterBlockLayout}]
    Source: 'src/lib.rs', lines 67:9-67:14 -/
@[reducible]
def FooterBlockLayout.Insts.CoreCloneClone : core.clone.Clone FooterBlockLayout
  := {
  clone := FooterBlockLayout.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::Copy for parity_sidecar_layout_verif::FooterBlockLayout}]
    Source: 'src/lib.rs', lines 67:16-67:20 -/
@[reducible]
def FooterBlockLayout.Insts.CoreMarkerCopy : core.marker.Copy FooterBlockLayout
  := {
  cloneInst := FooterBlockLayout.Insts.CoreCloneClone
}

/-- [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::FooterBlockLayout}::fmt]:
    Source: 'src/lib.rs', lines 67:22-67:27
    Visibility: public -/
def FooterBlockLayout.Insts.CoreFmtDebug.fmt
  (self : FooterBlockLayout) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.magic
  let dyn1 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.sidecar_footer_version
  let dyn2 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.reserved16
  let dyn3 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.reserved32
  let dyn4 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.tape_uuid
  let dyn5 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.epoch_id
  let dyn6 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.protected_ordinal_start
  let dyn7 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.protected_ordinal_end_exclusive
  let dyn8 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.sidecar_header_block_count
  let dyn9 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.parity_shard_block_count
  let dyn10 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.sidecar_total_block_count
  let dyn11 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.primary_header_start_block
  let dyn12 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.tail_header_start_block
  let dyn13 :=
    Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.canonical_metadata_hash
  let dyn14 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.footer_crc_field
  let dyn15 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.footer_crc_input
  let dyn16 :=
    Dyn.mk _ (core.fmt.DebugShared ByteRange.Insts.CoreFmtDebug)
      self.footer_padding
  let values :=
    Array.to_slice
      (Array.make 17#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15, dyn16
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 17#usize [
        toStr "magic", toStr "sidecar_footer_version", toStr "reserved16",
        toStr "reserved32", toStr "tape_uuid", toStr "epoch_id", toStr
        "protected_ordinal_start", toStr "protected_ordinal_end_exclusive",
        toStr "sidecar_header_block_count", toStr "parity_shard_block_count",
        toStr "sidecar_total_block_count", toStr "primary_header_start_block",
        toStr "tail_header_start_block", toStr "canonical_metadata_hash", toStr
        "footer_crc_field", toStr "footer_crc_input", toStr "footer_padding"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "FooterBlockLayout") s
    values

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::FooterBlockLayout}]
    Source: 'src/lib.rs', lines 67:22-67:27 -/
@[reducible]
def FooterBlockLayout.Insts.CoreFmtDebug : core.fmt.Debug FooterBlockLayout
  := {
  fmt := FooterBlockLayout.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::StructuralPartialEq for parity_sidecar_layout_verif::FooterBlockLayout}]
    Source: 'src/lib.rs', lines 67:29-67:38 -/
@[reducible]
def FooterBlockLayout.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq FooterBlockLayout := {
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::FooterBlockLayout> for parity_sidecar_layout_verif::FooterBlockLayout}::eq]:
    Source: 'src/lib.rs', lines 67:29-67:38
    Visibility: public -/
def FooterBlockLayout.Insts.CoreCmpPartialEqFooterBlockLayout.eq
  (self : FooterBlockLayout) (other : FooterBlockLayout) : Result Bool := do
  let b ← ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.magic other.magic
  if b
  then
    let b1 ←
      ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.sidecar_footer_version
        other.sidecar_footer_version
    if b1
    then
      let b2 ←
        ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.reserved16
          other.reserved16
      if b2
      then
        let b3 ←
          ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.reserved32
            other.reserved32
        if b3
        then
          let b4 ←
            ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.tape_uuid
              other.tape_uuid
          if b4
          then
            let b5 ←
              ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.epoch_id
                other.epoch_id
            if b5
            then
              let b6 ←
                ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                  self.protected_ordinal_start other.protected_ordinal_start
              if b6
              then
                let b7 ←
                  ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                    self.protected_ordinal_end_exclusive
                    other.protected_ordinal_end_exclusive
                if b7
                then
                  let b8 ←
                    ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                      self.sidecar_header_block_count
                      other.sidecar_header_block_count
                  if b8
                  then
                    let b9 ←
                      ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                        self.parity_shard_block_count
                        other.parity_shard_block_count
                    if b9
                    then
                      let b10 ←
                        ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                          self.sidecar_total_block_count
                          other.sidecar_total_block_count
                      if b10
                      then
                        let b11 ←
                          ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                            self.primary_header_start_block
                            other.primary_header_start_block
                        if b11
                        then
                          let b12 ←
                            ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                              self.tail_header_start_block
                              other.tail_header_start_block
                          if b12
                          then
                            let b13 ←
                              ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                self.canonical_metadata_hash
                                other.canonical_metadata_hash
                            if b13
                            then
                              let b14 ←
                                ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                  self.footer_crc_field other.footer_crc_field
                              if b14
                              then
                                let b15 ←
                                  ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                    self.footer_crc_input
                                    other.footer_crc_input
                                if b15
                                then
                                  ByteRange.Insts.CoreCmpPartialEqByteRange.eq
                                    self.footer_padding other.footer_padding
                                else ok false
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::FooterBlockLayout> for parity_sidecar_layout_verif::FooterBlockLayout}]
    Source: 'src/lib.rs', lines 67:29-67:38 -/
@[reducible]
def FooterBlockLayout.Insts.CoreCmpPartialEqFooterBlockLayout :
  core.cmp.PartialEq FooterBlockLayout FooterBlockLayout := {
  eq := FooterBlockLayout.Insts.CoreCmpPartialEqFooterBlockLayout.eq
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::FooterBlockLayout}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 67:40-67:42
    Visibility: public -/
def FooterBlockLayout.Insts.CoreCmpEq.assert_fields_are_eq
  (self : FooterBlockLayout) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::FooterBlockLayout}]
    Source: 'src/lib.rs', lines 67:40-67:42 -/
@[reducible]
def FooterBlockLayout.Insts.CoreCmpEq : core.cmp.Eq FooterBlockLayout := {
  partialEqInst := FooterBlockLayout.Insts.CoreCmpPartialEqFooterBlockLayout
  assert_fields_are_eq :=
    FooterBlockLayout.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_sidecar_layout_verif::SpillBlockLayout]
    Source: 'src/lib.rs', lines 89:0-93:1
    Visibility: public -/
structure SpillBlockLayout where
  index_payload : ByteRange
  trailing_crc_input : ByteRange
  trailing_crc_field : ByteRange

/-- [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::SpillBlockLayout}::clone]:
    Source: 'src/lib.rs', lines 88:9-88:14
    Visibility: public -/
def SpillBlockLayout.Insts.CoreCloneClone.clone
  (self : SpillBlockLayout) : Result SpillBlockLayout := do
  ok self

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::SpillBlockLayout}]
    Source: 'src/lib.rs', lines 88:9-88:14 -/
@[reducible]
def SpillBlockLayout.Insts.CoreCloneClone : core.clone.Clone SpillBlockLayout
  := {
  clone := SpillBlockLayout.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::Copy for parity_sidecar_layout_verif::SpillBlockLayout}]
    Source: 'src/lib.rs', lines 88:16-88:20 -/
@[reducible]
def SpillBlockLayout.Insts.CoreMarkerCopy : core.marker.Copy SpillBlockLayout
  := {
  cloneInst := SpillBlockLayout.Insts.CoreCloneClone
}

/-- [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::SpillBlockLayout}::fmt]:
    Source: 'src/lib.rs', lines 88:22-88:27
    Visibility: public -/
def SpillBlockLayout.Insts.CoreFmtDebug.fmt
  (self : SpillBlockLayout) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.index_payload
  let dyn1 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.trailing_crc_input
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared ByteRange.Insts.CoreFmtDebug)
      self.trailing_crc_field
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "SpillBlockLayout")
    (toStr "index_payload") dyn (toStr "trailing_crc_input") dyn1 (toStr
    "trailing_crc_field") dyn2

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::SpillBlockLayout}]
    Source: 'src/lib.rs', lines 88:22-88:27 -/
@[reducible]
def SpillBlockLayout.Insts.CoreFmtDebug : core.fmt.Debug SpillBlockLayout := {
  fmt := SpillBlockLayout.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::StructuralPartialEq for parity_sidecar_layout_verif::SpillBlockLayout}]
    Source: 'src/lib.rs', lines 88:29-88:38 -/
@[reducible]
def SpillBlockLayout.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq SpillBlockLayout := {
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::SpillBlockLayout> for parity_sidecar_layout_verif::SpillBlockLayout}::eq]:
    Source: 'src/lib.rs', lines 88:29-88:38
    Visibility: public -/
def SpillBlockLayout.Insts.CoreCmpPartialEqSpillBlockLayout.eq
  (self : SpillBlockLayout) (other : SpillBlockLayout) : Result Bool := do
  let b ←
    ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.index_payload
      other.index_payload
  if b
  then
    let b1 ←
      ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.trailing_crc_input
        other.trailing_crc_input
    if b1
    then
      ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.trailing_crc_field
        other.trailing_crc_field
    else ok false
  else ok false

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::SpillBlockLayout> for parity_sidecar_layout_verif::SpillBlockLayout}]
    Source: 'src/lib.rs', lines 88:29-88:38 -/
@[reducible]
def SpillBlockLayout.Insts.CoreCmpPartialEqSpillBlockLayout :
  core.cmp.PartialEq SpillBlockLayout SpillBlockLayout := {
  eq := SpillBlockLayout.Insts.CoreCmpPartialEqSpillBlockLayout.eq
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::SpillBlockLayout}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 88:40-88:42
    Visibility: public -/
def SpillBlockLayout.Insts.CoreCmpEq.assert_fields_are_eq
  (self : SpillBlockLayout) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::SpillBlockLayout}]
    Source: 'src/lib.rs', lines 88:40-88:42 -/
@[reducible]
def SpillBlockLayout.Insts.CoreCmpEq : core.cmp.Eq SpillBlockLayout := {
  partialEqInst := SpillBlockLayout.Insts.CoreCmpPartialEqSpillBlockLayout
  assert_fields_are_eq := SpillBlockLayout.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_sidecar_layout_verif::SidecarTapeFileLayout]
    Source: 'src/lib.rs', lines 96:0-102:1
    Visibility: public -/
structure SidecarTapeFileLayout where
  primary_header_copy : ByteRange
  parity_shards : ByteRange
  tail_header_copy : ByteRange
  footer_block_index : Std.U64
  sidecar_total_block_count : Std.U64

/-- [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::SidecarTapeFileLayout}::clone]:
    Source: 'src/lib.rs', lines 95:9-95:14
    Visibility: public -/
def SidecarTapeFileLayout.Insts.CoreCloneClone.clone
  (self : SidecarTapeFileLayout) : Result SidecarTapeFileLayout := do
  ok self

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::clone::Clone for parity_sidecar_layout_verif::SidecarTapeFileLayout}]
    Source: 'src/lib.rs', lines 95:9-95:14 -/
@[reducible]
def SidecarTapeFileLayout.Insts.CoreCloneClone : core.clone.Clone
  SidecarTapeFileLayout := {
  clone := SidecarTapeFileLayout.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::Copy for parity_sidecar_layout_verif::SidecarTapeFileLayout}]
    Source: 'src/lib.rs', lines 95:16-95:20 -/
@[reducible]
def SidecarTapeFileLayout.Insts.CoreMarkerCopy : core.marker.Copy
  SidecarTapeFileLayout := {
  cloneInst := SidecarTapeFileLayout.Insts.CoreCloneClone
}

/-- [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::SidecarTapeFileLayout}::fmt]:
    Source: 'src/lib.rs', lines 95:22-95:27
    Visibility: public -/
def SidecarTapeFileLayout.Insts.CoreFmtDebug.fmt
  (self : SidecarTapeFileLayout) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.primary_header_copy
  let dyn1 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.parity_shards
  let dyn2 := Dyn.mk _ ByteRange.Insts.CoreFmtDebug self.tail_header_copy
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.footer_block_index
  let dyn4 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64)
      self.sidecar_total_block_count
  core.fmt.Formatter.debug_struct_field5_finish f (toStr
    "SidecarTapeFileLayout") (toStr "primary_header_copy") dyn (toStr
    "parity_shards") dyn1 (toStr "tail_header_copy") dyn2 (toStr
    "footer_block_index") dyn3 (toStr "sidecar_total_block_count") dyn4

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::fmt::Debug for parity_sidecar_layout_verif::SidecarTapeFileLayout}]
    Source: 'src/lib.rs', lines 95:22-95:27 -/
@[reducible]
def SidecarTapeFileLayout.Insts.CoreFmtDebug : core.fmt.Debug
  SidecarTapeFileLayout := {
  fmt := SidecarTapeFileLayout.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::marker::StructuralPartialEq for parity_sidecar_layout_verif::SidecarTapeFileLayout}]
    Source: 'src/lib.rs', lines 95:29-95:38 -/
@[reducible]
def SidecarTapeFileLayout.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq SidecarTapeFileLayout := {
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::SidecarTapeFileLayout> for parity_sidecar_layout_verif::SidecarTapeFileLayout}::eq]:
    Source: 'src/lib.rs', lines 95:29-95:38
    Visibility: public -/
def SidecarTapeFileLayout.Insts.CoreCmpPartialEqSidecarTapeFileLayout.eq
  (self : SidecarTapeFileLayout) (other : SidecarTapeFileLayout) :
  Result Bool
  := do
  if self.footer_block_index = other.footer_block_index
  then
    if self.sidecar_total_block_count = other.sidecar_total_block_count
    then
      let b ←
        ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.primary_header_copy
          other.primary_header_copy
      if b
      then
        let b1 ←
          ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.parity_shards
            other.parity_shards
        if b1
        then
          ByteRange.Insts.CoreCmpPartialEqByteRange.eq self.tail_header_copy
            other.tail_header_copy
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::PartialEq<parity_sidecar_layout_verif::SidecarTapeFileLayout> for parity_sidecar_layout_verif::SidecarTapeFileLayout}]
    Source: 'src/lib.rs', lines 95:29-95:38 -/
@[reducible]
def SidecarTapeFileLayout.Insts.CoreCmpPartialEqSidecarTapeFileLayout :
  core.cmp.PartialEq SidecarTapeFileLayout SidecarTapeFileLayout := {
  eq := SidecarTapeFileLayout.Insts.CoreCmpPartialEqSidecarTapeFileLayout.eq
}

/-- [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::SidecarTapeFileLayout}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 95:40-95:42
    Visibility: public -/
def SidecarTapeFileLayout.Insts.CoreCmpEq.assert_fields_are_eq
  (self : SidecarTapeFileLayout) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_sidecar_layout_verif::{impl core::cmp::Eq for parity_sidecar_layout_verif::SidecarTapeFileLayout}]
    Source: 'src/lib.rs', lines 95:40-95:42 -/
@[reducible]
def SidecarTapeFileLayout.Insts.CoreCmpEq : core.cmp.Eq SidecarTapeFileLayout
  := {
  partialEqInst :=
    SidecarTapeFileLayout.Insts.CoreCmpPartialEqSidecarTapeFileLayout
  assert_fields_are_eq :=
    SidecarTapeFileLayout.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_sidecar_layout_verif::range]:
    Source: 'src/lib.rs', lines 104:0-106:1
    Visibility: public -/
def range (start : Std.U64) (end1 : Std.U64) : Result ByteRange := do
  ok { start, «end» := end1 }

/-- [parity_sidecar_layout_verif::checked_add]:
    Source: 'src/lib.rs', lines 108:0-113:1
    Visibility: public -/
def checked_add
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 LayoutError)
  := do
  let o ← lift (U64.checked_add a b)
  match o with
  | none => ok (core.result.Result.Err LayoutError.ArithmeticOverflow)
  | some sum => ok (core.result.Result.Ok sum)

/-- [parity_sidecar_layout_verif::checked_sub]:
    Source: 'src/lib.rs', lines 115:0-120:1
    Visibility: public -/
def checked_sub
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 LayoutError)
  := do
  let o ← lift (U64.checked_sub a b)
  match o with
  | none => ok (core.result.Result.Err LayoutError.ArithmeticOverflow)
  | some diff => ok (core.result.Result.Ok diff)

/-- [parity_sidecar_layout_verif::header_block_layout]:
    Source: 'src/lib.rs', lines 122:0-161:1
    Visibility: public -/
def header_block_layout
  (block_size : Std.U64) :
  Result (core.result.Result HeaderBlockLayout LayoutError)
  := do
  if block_size < MIN_HEADER_BLOCK_SIZE
  then ok (core.result.Result.Err LayoutError.BlockTooSmall)
  else
    let r ← checked_sub block_size TRAILING_CRC_LEN
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let br ← range 0#u64 8#u64
      let br1 ← range 8#u64 24#u64
      let br2 ← range 24#u64 32#u64
      let br3 ← range 32#u64 34#u64
      let br4 ← range 34#u64 36#u64
      let br5 ← range 36#u64 40#u64
      let br6 ← range 40#u64 44#u64
      let br7 ← range 44#u64 48#u64
      let br8 ← range 48#u64 56#u64
      let br9 ← range 56#u64 64#u64
      let br10 ← range 64#u64 72#u64
      let br11 ← range 72#u64 80#u64
      let br12 ← range 80#u64 84#u64
      let br13 ← range 84#u64 88#u64
      let br14 ← range 88#u64 92#u64
      let br15 ← range 92#u64 96#u64
      let br16 ← range 96#u64 104#u64
      let br17 ← range 104#u64 112#u64
      let br18 ← range 112#u64 120#u64
      let br19 ← range 120#u64 128#u64
      let br20 ← range 128#u64 130#u64
      let br21 ← range 130#u64 132#u64
      let br22 ← range 132#u64 136#u64
      let br23 ← range 136#u64 168#u64
      let br24 ← range 168#u64 SIDECAR_HEADER_CRC_OFFSET
      let br25 ← range SIDECAR_HEADER_CRC_OFFSET SIDECAR_HEADER_LEN
      let br26 ← range SIDECAR_HEADER_LEN val
      let br27 ← range 0#u64 SIDECAR_HEADER_CRC_OFFSET
      let br28 ← range 0#u64 val
      let br29 ← range val block_size
      ok (core.result.Result.Ok
        {
          magic := br,
          tape_uuid := br1,
          epoch_id := br2,
          k := br3,
          m := br4,
          stripes_per_epoch := br5,
          block_size := br6,
          schema_version := br7,
          protected_ordinal_start := br8,
          protected_ordinal_end_exclusive := br9,
          logical_shard_count := br10,
          real_data_shard_count := br11,
          parity_block_count := br12,
          data_crc_count := br13,
          shard_index_block_count := br14,
          inline_index_entry_bytes := br15,
          sidecar_total_block_count := br16,
          primary_header_start_block := br17,
          tail_header_start_block := br18,
          footer_block_index := br19,
          copy_kind := br20,
          copy_kind_reserved := br21,
          copy_generation := br22,
          canonical_metadata_hash := br23,
          header_reserved := br24,
          header_crc_field := br25,
          inline_index_payload := br26,
          header_crc_input := br27,
          block0_crc_input := br28,
          block0_crc_field := br29
        })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        HeaderBlockLayout (core.convert.FromSame LayoutError) residual

/-- [parity_sidecar_layout_verif::footer_block_layout]:
    Source: 'src/lib.rs', lines 163:0-187:1
    Visibility: public -/
def footer_block_layout
  (block_size : Std.U64) :
  Result (core.result.Result FooterBlockLayout LayoutError)
  := do
  if block_size < SIDECAR_FOOTER_LEN
  then ok (core.result.Result.Err LayoutError.BlockTooSmall)
  else
    let br ← range 0#u64 8#u64
    let br1 ← range 8#u64 10#u64
    let br2 ← range 10#u64 12#u64
    let br3 ← range 12#u64 16#u64
    let br4 ← range 16#u64 32#u64
    let br5 ← range 32#u64 40#u64
    let br6 ← range 40#u64 48#u64
    let br7 ← range 48#u64 56#u64
    let br8 ← range 56#u64 60#u64
    let br9 ← range 60#u64 64#u64
    let br10 ← range 64#u64 72#u64
    let br11 ← range 72#u64 80#u64
    let br12 ← range 80#u64 88#u64
    let br13 ← range 88#u64 SIDECAR_FOOTER_CRC_OFFSET
    let br14 ← range SIDECAR_FOOTER_CRC_OFFSET SIDECAR_FOOTER_LEN
    let br15 ← range 0#u64 SIDECAR_FOOTER_CRC_OFFSET
    let br16 ← range SIDECAR_FOOTER_LEN block_size
    ok (core.result.Result.Ok
      {
        magic := br,
        sidecar_footer_version := br1,
        reserved16 := br2,
        reserved32 := br3,
        tape_uuid := br4,
        epoch_id := br5,
        protected_ordinal_start := br6,
        protected_ordinal_end_exclusive := br7,
        sidecar_header_block_count := br8,
        parity_shard_block_count := br9,
        sidecar_total_block_count := br10,
        primary_header_start_block := br11,
        tail_header_start_block := br12,
        canonical_metadata_hash := br13,
        footer_crc_field := br14,
        footer_crc_input := br15,
        footer_padding := br16
      })

/-- [parity_sidecar_layout_verif::spill_block_layout]:
    Source: 'src/lib.rs', lines 189:0-200:1
    Visibility: public -/
def spill_block_layout
  (block_size : Std.U64) :
  Result (core.result.Result SpillBlockLayout LayoutError)
  := do
  if block_size < TRAILING_CRC_LEN
  then ok (core.result.Result.Err LayoutError.BlockTooSmall)
  else
    let r ← checked_sub block_size TRAILING_CRC_LEN
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let br ← range 0#u64 val
      let br1 ← range val block_size
      ok (core.result.Result.Ok
        {
          index_payload := br,
          trailing_crc_input := br,
          trailing_crc_field := br1
        })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        SpillBlockLayout (core.convert.FromSame LayoutError) residual

/-- [parity_sidecar_layout_verif::sidecar_tape_file_layout]:
    Source: 'src/lib.rs', lines 202:0-226:1
    Visibility: public -/
def sidecar_tape_file_layout
  (shard_index_block_count : Std.U64) (parity_block_count : Std.U64) :
  Result (core.result.Result SidecarTapeFileLayout LayoutError)
  := do
  if shard_index_block_count = 0#u64
  then ok (core.result.Result.Err LayoutError.HeaderBlockCountZero)
  else
    let r ← checked_add shard_index_block_count parity_block_count
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let r1 ← checked_add val shard_index_block_count
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let r2 ← checked_add val1 1#u64
        let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let br ← range 0#u64 shard_index_block_count
          let br1 ← range shard_index_block_count val
          let br2 ← range val val1
          ok (core.result.Result.Ok
            {
              primary_header_copy := br,
              parity_shards := br1,
              tail_header_copy := br2,
              footer_block_index := val1,
              sidecar_total_block_count := val2
            })
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            SidecarTapeFileLayout (core.convert.FromSame LayoutError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          SidecarTapeFileLayout (core.convert.FromSame LayoutError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        SidecarTapeFileLayout (core.convert.FromSame LayoutError) residual

end parity_sidecar_layout_verif
