-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_metadata_verif]: function definitions
import Aeneas
import RaoMetadata.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoMetadata

/-- [rao_metadata_verif::KEY_METADATA_VERSION]
    Source: 'src/lib.rs', lines 17:0-17:40
    Visibility: public -/
@[global_simps, irreducible] def KEY_METADATA_VERSION : Std.U64 := 0#u64

/-- [rao_metadata_verif::KEY_PLAINTEXT_SIZE]
    Source: 'src/lib.rs', lines 18:0-18:38
    Visibility: public -/
@[global_simps, irreducible] def KEY_PLAINTEXT_SIZE : Std.U64 := 1#u64

/-- [rao_metadata_verif::KEY_PLAINTEXT_DIGEST_ALG]
    Source: 'src/lib.rs', lines 19:0-19:44
    Visibility: public -/
@[global_simps, irreducible] def KEY_PLAINTEXT_DIGEST_ALG : Std.U64 := 2#u64

/-- [rao_metadata_verif::KEY_PLAINTEXT_DIGEST]
    Source: 'src/lib.rs', lines 20:0-20:40
    Visibility: public -/
@[global_simps, irreducible] def KEY_PLAINTEXT_DIGEST : Std.U64 := 3#u64

/-- [rao_metadata_verif::METADATA_VERSION]
    Source: 'src/lib.rs', lines 22:0-22:36
    Visibility: public -/
@[global_simps, irreducible] def METADATA_VERSION : Std.U64 := 1#u64

/-- [rao_metadata_verif::REQUIRED_MAP_LEN]
    Source: 'src/lib.rs', lines 23:0-23:36
    Visibility: public -/
@[global_simps, irreducible] def REQUIRED_MAP_LEN : Std.U64 := 4#u64

/-- [rao_metadata_verif::DIGEST_BYTE_LEN]
    Source: 'src/lib.rs', lines 24:0-24:36
    Visibility: public -/
@[global_simps, irreducible] def DIGEST_BYTE_LEN : Std.U64 := 32#u64

/-- [rao_metadata_verif::CHACHA20POLY1305_TAG_LEN]
    Source: 'src/lib.rs', lines 25:0-25:45
    Visibility: public -/
@[global_simps, irreducible] def CHACHA20POLY1305_TAG_LEN : Std.U64 := 16#u64

/-- [rao_metadata_verif::CHUNK_SIZE_GRANULARITY]
    Source: 'src/lib.rs', lines 26:0-26:44
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_SIZE_GRANULARITY : Std.U64 := 512#u64

/-- [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::RaoMetadataError}::clone]:
    Source: 'src/lib.rs', lines 28:9-28:14
    Visibility: public -/
def RaoMetadataError.Insts.CoreCloneClone.clone
  (self : RaoMetadataError) : Result RaoMetadataError := do
  ok self

/-- Trait implementation: [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::RaoMetadataError}]
    Source: 'src/lib.rs', lines 28:9-28:14 -/
@[reducible]
def RaoMetadataError.Insts.CoreCloneClone : core.clone.Clone RaoMetadataError
  := {
  clone := RaoMetadataError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::Copy for rao_metadata_verif::RaoMetadataError}]
    Source: 'src/lib.rs', lines 28:16-28:20 -/
@[reducible]
def RaoMetadataError.Insts.CoreMarkerCopy : core.marker.Copy RaoMetadataError
  := {
  cloneInst := RaoMetadataError.Insts.CoreCloneClone
}

/-- [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::RaoMetadataError}::fmt]:
    Source: 'src/lib.rs', lines 28:22-28:27
    Visibility: public -/
def RaoMetadataError.Insts.CoreFmtDebug.fmt
  (self : RaoMetadataError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | RaoMetadataError.InvalidChunkSize =>
    core.fmt.Formatter.write_str f (toStr "InvalidChunkSize")
  | RaoMetadataError.InvalidMetadataField =>
    core.fmt.Formatter.write_str f (toStr "InvalidMetadataField")
  | RaoMetadataError.InvalidCborEncoding =>
    core.fmt.Formatter.write_str f (toStr "InvalidCborEncoding")
  | RaoMetadataError.MissingRequiredMetadataField =>
    core.fmt.Formatter.write_str f (toStr "MissingRequiredMetadataField")

/-- Trait implementation: [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::RaoMetadataError}]
    Source: 'src/lib.rs', lines 28:22-28:27 -/
@[reducible]
def RaoMetadataError.Insts.CoreFmtDebug : core.fmt.Debug RaoMetadataError := {
  fmt := RaoMetadataError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::StructuralPartialEq for rao_metadata_verif::RaoMetadataError}]
    Source: 'src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def RaoMetadataError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RaoMetadataError := {
}

/-- [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::RaoMetadataError> for rao_metadata_verif::RaoMetadataError}::eq]:
    Source: 'src/lib.rs', lines 28:29-28:38
    Visibility: public -/
def RaoMetadataError.Insts.CoreCmpPartialEqRaoMetadataError.eq
  (self : RaoMetadataError) (other : RaoMetadataError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::RaoMetadataError> for rao_metadata_verif::RaoMetadataError}]
    Source: 'src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def RaoMetadataError.Insts.CoreCmpPartialEqRaoMetadataError :
  core.cmp.PartialEq RaoMetadataError RaoMetadataError := {
  eq := RaoMetadataError.Insts.CoreCmpPartialEqRaoMetadataError.eq
}

/-- [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::RaoMetadataError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 28:40-28:42
    Visibility: public -/
def RaoMetadataError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RaoMetadataError) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::RaoMetadataError}]
    Source: 'src/lib.rs', lines 28:40-28:42 -/
@[reducible]
def RaoMetadataError.Insts.CoreCmpEq : core.cmp.Eq RaoMetadataError := {
  partialEqInst := RaoMetadataError.Insts.CoreCmpPartialEqRaoMetadataError
  assert_fields_are_eq := RaoMetadataError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::DigestWords}::clone]:
    Source: 'src/lib.rs', lines 36:9-36:14
    Visibility: public -/
def DigestWords.Insts.CoreCloneClone.clone
  (self : DigestWords) : Result DigestWords := do
  ok self

/-- Trait implementation: [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::DigestWords}]
    Source: 'src/lib.rs', lines 36:9-36:14 -/
@[reducible]
def DigestWords.Insts.CoreCloneClone : core.clone.Clone DigestWords := {
  clone := DigestWords.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::Copy for rao_metadata_verif::DigestWords}]
    Source: 'src/lib.rs', lines 36:16-36:20 -/
@[reducible]
def DigestWords.Insts.CoreMarkerCopy : core.marker.Copy DigestWords := {
  cloneInst := DigestWords.Insts.CoreCloneClone
}

/-- [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::DigestWords}::fmt]:
    Source: 'src/lib.rs', lines 36:22-36:27
    Visibility: public -/
def DigestWords.Insts.CoreFmtDebug.fmt
  (self : DigestWords) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.w0
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.w1
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.w2
  let dyn3 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.w3
  core.fmt.Formatter.debug_struct_field4_finish f (toStr "DigestWords") (toStr
    "w0") dyn (toStr "w1") dyn1 (toStr "w2") dyn2 (toStr "w3") dyn3

/-- Trait implementation: [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::DigestWords}]
    Source: 'src/lib.rs', lines 36:22-36:27 -/
@[reducible]
def DigestWords.Insts.CoreFmtDebug : core.fmt.Debug DigestWords := {
  fmt := DigestWords.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::StructuralPartialEq for rao_metadata_verif::DigestWords}]
    Source: 'src/lib.rs', lines 36:29-36:38 -/
@[reducible]
def DigestWords.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq DigestWords := {
}

/-- [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::DigestWords> for rao_metadata_verif::DigestWords}::eq]:
    Source: 'src/lib.rs', lines 36:29-36:38
    Visibility: public -/
def DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
  (self : DigestWords) (other : DigestWords) : Result Bool := do
  if self.w0 = other.w0
  then
    if self.w1 = other.w1
    then if self.w2 = other.w2
         then ok (self.w3 = other.w3)
         else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::DigestWords> for rao_metadata_verif::DigestWords}]
    Source: 'src/lib.rs', lines 36:29-36:38 -/
@[reducible]
def DigestWords.Insts.CoreCmpPartialEqDigestWords : core.cmp.PartialEq
  DigestWords DigestWords := {
  eq := DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
}

/-- [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::DigestWords}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 36:40-36:42
    Visibility: public -/
def DigestWords.Insts.CoreCmpEq.assert_fields_are_eq
  (self : DigestWords) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::DigestWords}]
    Source: 'src/lib.rs', lines 36:40-36:42 -/
@[reducible]
def DigestWords.Insts.CoreCmpEq : core.cmp.Eq DigestWords := {
  partialEqInst := DigestWords.Insts.CoreCmpPartialEqDigestWords
  assert_fields_are_eq := DigestWords.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::MetadataCore}::clone]:
    Source: 'src/lib.rs', lines 44:9-44:14
    Visibility: public -/
def MetadataCore.Insts.CoreCloneClone.clone
  (self : MetadataCore) : Result MetadataCore := do
  ok self

/-- Trait implementation: [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 44:9-44:14 -/
@[reducible]
def MetadataCore.Insts.CoreCloneClone : core.clone.Clone MetadataCore := {
  clone := MetadataCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::Copy for rao_metadata_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 44:16-44:20 -/
@[reducible]
def MetadataCore.Insts.CoreMarkerCopy : core.marker.Copy MetadataCore := {
  cloneInst := MetadataCore.Insts.CoreCloneClone
}

/-- [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::MetadataCore}::fmt]:
    Source: 'src/lib.rs', lines 44:22-44:27
    Visibility: public -/
def MetadataCore.Insts.CoreFmtDebug.fmt
  (self : MetadataCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.plaintext_size
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared DigestWords.Insts.CoreFmtDebug) self.digest
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "MetadataCore") (toStr
    "plaintext_size") dyn (toStr "digest") dyn1

/-- Trait implementation: [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 44:22-44:27 -/
@[reducible]
def MetadataCore.Insts.CoreFmtDebug : core.fmt.Debug MetadataCore := {
  fmt := MetadataCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::StructuralPartialEq for rao_metadata_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 44:29-44:38 -/
@[reducible]
def MetadataCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq MetadataCore := {
}

/-- [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::MetadataCore> for rao_metadata_verif::MetadataCore}::eq]:
    Source: 'src/lib.rs', lines 44:29-44:38
    Visibility: public -/
def MetadataCore.Insts.CoreCmpPartialEqMetadataCore.eq
  (self : MetadataCore) (other : MetadataCore) : Result Bool := do
  if self.plaintext_size = other.plaintext_size
  then
    DigestWords.Insts.CoreCmpPartialEqDigestWords.eq self.digest other.digest
  else ok false

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::MetadataCore> for rao_metadata_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 44:29-44:38 -/
@[reducible]
def MetadataCore.Insts.CoreCmpPartialEqMetadataCore : core.cmp.PartialEq
  MetadataCore MetadataCore := {
  eq := MetadataCore.Insts.CoreCmpPartialEqMetadataCore.eq
}

/-- [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::MetadataCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 44:40-44:42
    Visibility: public -/
def MetadataCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : MetadataCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 44:40-44:42 -/
@[reducible]
def MetadataCore.Insts.CoreCmpEq : core.cmp.Eq MetadataCore := {
  partialEqInst := MetadataCore.Insts.CoreCmpPartialEqMetadataCore
  assert_fields_are_eq := MetadataCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::MetadataCborCore}::clone]:
    Source: 'src/lib.rs', lines 50:9-50:14
    Visibility: public -/
def MetadataCborCore.Insts.CoreCloneClone.clone
  (self : MetadataCborCore) : Result MetadataCborCore := do
  ok self

/-- Trait implementation: [rao_metadata_verif::{impl core::clone::Clone for rao_metadata_verif::MetadataCborCore}]
    Source: 'src/lib.rs', lines 50:9-50:14 -/
@[reducible]
def MetadataCborCore.Insts.CoreCloneClone : core.clone.Clone MetadataCborCore
  := {
  clone := MetadataCborCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::Copy for rao_metadata_verif::MetadataCborCore}]
    Source: 'src/lib.rs', lines 50:16-50:20 -/
@[reducible]
def MetadataCborCore.Insts.CoreMarkerCopy : core.marker.Copy MetadataCborCore
  := {
  cloneInst := MetadataCborCore.Insts.CoreCloneClone
}

/-- [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::MetadataCborCore}::fmt]:
    Source: 'src/lib.rs', lines 50:22-50:27
    Visibility: public -/
def MetadataCborCore.Insts.CoreFmtDebug.fmt
  (self : MetadataCborCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.map_len
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.key_metadata_version
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.metadata_version
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.key_plaintext_size
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.plaintext_size
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.key_plaintext_digest_alg
  let dyn6 := Dyn.mk _ core.fmt.DebugBool self.digest_alg_sha256
  let dyn7 := Dyn.mk _ core.fmt.DebugU64 self.key_plaintext_digest
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.digest_byte_len
  let dyn9 := Dyn.mk _ DigestWords.Insts.CoreFmtDebug self.digest
  let dyn10 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.trailing_data
  let values :=
    Array.to_slice
      (Array.make 11#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 11#usize [
        toStr "map_len", toStr "key_metadata_version", toStr
        "metadata_version", toStr "key_plaintext_size", toStr "plaintext_size",
        toStr "key_plaintext_digest_alg", toStr "digest_alg_sha256", toStr
        "key_plaintext_digest", toStr "digest_byte_len", toStr "digest", toStr
        "trailing_data"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "MetadataCborCore") s
    values

/-- Trait implementation: [rao_metadata_verif::{impl core::fmt::Debug for rao_metadata_verif::MetadataCborCore}]
    Source: 'src/lib.rs', lines 50:22-50:27 -/
@[reducible]
def MetadataCborCore.Insts.CoreFmtDebug : core.fmt.Debug MetadataCborCore := {
  fmt := MetadataCborCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_metadata_verif::{impl core::marker::StructuralPartialEq for rao_metadata_verif::MetadataCborCore}]
    Source: 'src/lib.rs', lines 50:29-50:38 -/
@[reducible]
def MetadataCborCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq MetadataCborCore := {
}

/-- [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::MetadataCborCore> for rao_metadata_verif::MetadataCborCore}::eq]:
    Source: 'src/lib.rs', lines 50:29-50:38
    Visibility: public -/
def MetadataCborCore.Insts.CoreCmpPartialEqMetadataCborCore.eq
  (self : MetadataCborCore) (other : MetadataCborCore) : Result Bool := do
  if self.map_len = other.map_len
  then
    if self.key_metadata_version = other.key_metadata_version
    then
      if self.metadata_version = other.metadata_version
      then
        if self.key_plaintext_size = other.key_plaintext_size
        then
          if self.plaintext_size = other.plaintext_size
          then
            if self.key_plaintext_digest_alg = other.key_plaintext_digest_alg
            then
              if self.digest_alg_sha256 = other.digest_alg_sha256
              then
                if self.key_plaintext_digest = other.key_plaintext_digest
                then
                  if self.digest_byte_len = other.digest_byte_len
                  then
                    if self.trailing_data = other.trailing_data
                    then
                      DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
                        self.digest other.digest
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::PartialEq<rao_metadata_verif::MetadataCborCore> for rao_metadata_verif::MetadataCborCore}]
    Source: 'src/lib.rs', lines 50:29-50:38 -/
@[reducible]
def MetadataCborCore.Insts.CoreCmpPartialEqMetadataCborCore :
  core.cmp.PartialEq MetadataCborCore MetadataCborCore := {
  eq := MetadataCborCore.Insts.CoreCmpPartialEqMetadataCborCore.eq
}

/-- [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::MetadataCborCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 50:40-50:42
    Visibility: public -/
def MetadataCborCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : MetadataCborCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_metadata_verif::{impl core::cmp::Eq for rao_metadata_verif::MetadataCborCore}]
    Source: 'src/lib.rs', lines 50:40-50:42 -/
@[reducible]
def MetadataCborCore.Insts.CoreCmpEq : core.cmp.Eq MetadataCborCore := {
  partialEqInst := MetadataCborCore.Insts.CoreCmpPartialEqMetadataCborCore
  assert_fields_are_eq := MetadataCborCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_metadata_verif::checked_add]:
    Source: 'src/lib.rs', lines 65:0-70:1
    Visibility: public -/
def checked_add
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 RaoMetadataError)
  := do
  let o ← lift (U64.checked_add a b)
  match o with
  | none => ok (core.result.Result.Err RaoMetadataError.InvalidMetadataField)
  | some sum => ok (core.result.Result.Ok sum)

/-- [rao_metadata_verif::checked_mul]:
    Source: 'src/lib.rs', lines 72:0-77:1
    Visibility: public -/
def checked_mul
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 RaoMetadataError)
  := do
  let o ← lift (U64.checked_mul a b)
  match o with
  | none => ok (core.result.Result.Err RaoMetadataError.InvalidMetadataField)
  | some product => ok (core.result.Result.Ok product)

/-- [rao_metadata_verif::validate_chunk_size]:
    Source: 'src/lib.rs', lines 79:0-84:1
    Visibility: public -/
def validate_chunk_size
  (chunk_size : Std.U64) :
  Result (core.result.Result Unit RaoMetadataError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err RaoMetadataError.InvalidChunkSize)
  else
    let i ← chunk_size % CHUNK_SIZE_GRANULARITY
    if i != 0#u64
    then ok (core.result.Result.Err RaoMetadataError.InvalidChunkSize)
    else ok (core.result.Result.Ok ())

/-- [rao_metadata_verif::validate_metadata_core]:
    Source: 'src/lib.rs', lines 86:0-98:1
    Visibility: public -/
def validate_metadata_core
  (metadata : MetadataCore) (chunk_size : Std.U64) :
  Result (core.result.Result Unit RaoMetadataError)
  := do
  let r ← validate_chunk_size chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if metadata.plaintext_size = 0#u64
    then ok (core.result.Result.Err RaoMetadataError.InvalidMetadataField)
    else
      let i ← metadata.plaintext_size % chunk_size
      if i != 0#u64
      then ok (core.result.Result.Err RaoMetadataError.InvalidMetadataField)
      else
        let chunk_count ← metadata.plaintext_size / chunk_size
        let r1 ← checked_mul CHACHA20POLY1305_TAG_LEN chunk_count
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let r2 ← checked_add metadata.plaintext_size val
          let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            ok (core.result.Result.Ok ())
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Unit (core.convert.FromSame RaoMetadataError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Unit (core.convert.FromSame RaoMetadataError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoMetadataError) residual

/-- [rao_metadata_verif::encode_metadata_core]:
    Source: 'src/lib.rs', lines 100:0-118:1
    Visibility: public -/
def encode_metadata_core
  (metadata : MetadataCore) (chunk_size : Std.U64) :
  Result (core.result.Result MetadataCborCore RaoMetadataError)
  := do
  let r ← validate_metadata_core metadata chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    ok (core.result.Result.Ok
      {
        map_len := REQUIRED_MAP_LEN,
        key_metadata_version := KEY_METADATA_VERSION,
        metadata_version := METADATA_VERSION,
        key_plaintext_size := KEY_PLAINTEXT_SIZE,
        plaintext_size := metadata.plaintext_size,
        key_plaintext_digest_alg := KEY_PLAINTEXT_DIGEST_ALG,
        digest_alg_sha256 := true,
        key_plaintext_digest := KEY_PLAINTEXT_DIGEST,
        digest_byte_len := DIGEST_BYTE_LEN,
        digest := metadata.digest,
        trailing_data := false
      })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      MetadataCborCore (core.convert.FromSame RaoMetadataError) residual

/-- [rao_metadata_verif::decode_metadata_core]:
    Source: 'src/lib.rs', lines 120:0-153:1
    Visibility: public -/
def decode_metadata_core
  (wire : MetadataCborCore) (chunk_size : Std.U64) :
  Result (core.result.Result MetadataCore RaoMetadataError)
  := do
  if wire.trailing_data
  then ok (core.result.Result.Err RaoMetadataError.InvalidCborEncoding)
  else
    if wire.map_len != REQUIRED_MAP_LEN
    then
      ok (core.result.Result.Err RaoMetadataError.MissingRequiredMetadataField)
    else
      if wire.key_metadata_version != KEY_METADATA_VERSION
      then ok (core.result.Result.Err RaoMetadataError.InvalidCborEncoding)
      else
        if wire.key_plaintext_size != KEY_PLAINTEXT_SIZE
        then ok (core.result.Result.Err RaoMetadataError.InvalidCborEncoding)
        else
          if wire.key_plaintext_digest_alg != KEY_PLAINTEXT_DIGEST_ALG
          then ok (core.result.Result.Err RaoMetadataError.InvalidCborEncoding)
          else
            if wire.key_plaintext_digest != KEY_PLAINTEXT_DIGEST
            then
              ok (core.result.Result.Err RaoMetadataError.InvalidCborEncoding)
            else
              if wire.metadata_version != METADATA_VERSION
              then
                ok (core.result.Result.Err
                  RaoMetadataError.InvalidMetadataField)
              else
                if wire.digest_alg_sha256
                then
                  if wire.digest_byte_len != DIGEST_BYTE_LEN
                  then
                    ok (core.result.Result.Err
                      RaoMetadataError.InvalidMetadataField)
                  else
                    let r ←
                      validate_metadata_core
                        {
                          plaintext_size := wire.plaintext_size,
                          digest := wire.digest
                        } chunk_size
                    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
                    match cf with
                    | core.ops.control_flow.ControlFlow.Continue _ =>
                      ok (core.result.Result.Ok
                        {
                          plaintext_size := wire.plaintext_size,
                          digest := wire.digest
                        })
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        MetadataCore (core.convert.FromSame RaoMetadataError)
                        residual
                else
                  ok (core.result.Result.Err
                    RaoMetadataError.InvalidMetadataField)

end RaoMetadata
