-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_metadata_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoMetadata

/-- [rao_metadata_verif::RaoMetadataError]
    Source: 'src/lib.rs', lines 29:0-34:1
    Visibility: public -/
@[discriminant isize]
inductive RaoMetadataError where
| InvalidChunkSize : RaoMetadataError
| InvalidMetadataField : RaoMetadataError
| InvalidCborEncoding : RaoMetadataError
| MissingRequiredMetadataField : RaoMetadataError

/-- [rao_metadata_verif::DigestWords]
    Source: 'src/lib.rs', lines 37:0-42:1
    Visibility: public -/
structure DigestWords where
  w0 : Std.U64
  w1 : Std.U64
  w2 : Std.U64
  w3 : Std.U64

/-- [rao_metadata_verif::MetadataCore]
    Source: 'src/lib.rs', lines 45:0-48:1
    Visibility: public -/
structure MetadataCore where
  plaintext_size : Std.U64
  digest : DigestWords

/-- [rao_metadata_verif::MetadataCborCore]
    Source: 'src/lib.rs', lines 51:0-63:1
    Visibility: public -/
structure MetadataCborCore where
  map_len : Std.U64
  key_metadata_version : Std.U64
  metadata_version : Std.U64
  key_plaintext_size : Std.U64
  plaintext_size : Std.U64
  key_plaintext_digest_alg : Std.U64
  digest_alg_sha256 : Bool
  key_plaintext_digest : Std.U64
  digest_byte_len : Std.U64
  digest : DigestWords
  trailing_data : Bool

end RaoMetadata
