-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [parity_capacity_verif]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace parity_capacity_verif

/-- [parity_capacity_verif::CapacityReserveCause]
    Source: 'src/lib.rs', lines 11:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive CapacityReserveCause where
| TapeCapacity : CapacityReserveCause
| ParitySpoolCapacity : CapacityReserveCause

/-- [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityReserveCause}::clone]:
    Source: 'src/lib.rs', lines 10:9-10:14
    Visibility: public -/
def CapacityReserveCause.Insts.CoreCloneClone.clone
  (self : CapacityReserveCause) : Result CapacityReserveCause := do
  ok self

/-- Trait implementation: [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityReserveCause}]
    Source: 'src/lib.rs', lines 10:9-10:14 -/
@[reducible]
def CapacityReserveCause.Insts.CoreCloneClone : core.clone.Clone
  CapacityReserveCause := {
  clone := CapacityReserveCause.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::Copy for parity_capacity_verif::CapacityReserveCause}]
    Source: 'src/lib.rs', lines 10:16-10:20 -/
@[reducible]
def CapacityReserveCause.Insts.CoreMarkerCopy : core.marker.Copy
  CapacityReserveCause := {
  cloneInst := CapacityReserveCause.Insts.CoreCloneClone
}

/-- [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityReserveCause}::fmt]:
    Source: 'src/lib.rs', lines 10:22-10:27
    Visibility: public -/
def CapacityReserveCause.Insts.CoreFmtDebug.fmt
  (self : CapacityReserveCause) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | CapacityReserveCause.TapeCapacity =>
    core.fmt.Formatter.write_str f (toStr "TapeCapacity")
  | CapacityReserveCause.ParitySpoolCapacity =>
    core.fmt.Formatter.write_str f (toStr "ParitySpoolCapacity")

/-- Trait implementation: [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityReserveCause}]
    Source: 'src/lib.rs', lines 10:22-10:27 -/
@[reducible]
def CapacityReserveCause.Insts.CoreFmtDebug : core.fmt.Debug
  CapacityReserveCause := {
  fmt := CapacityReserveCause.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::StructuralPartialEq for parity_capacity_verif::CapacityReserveCause}]
    Source: 'src/lib.rs', lines 10:29-10:38 -/
@[reducible]
def CapacityReserveCause.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CapacityReserveCause := {
}

/-- [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityReserveCause> for parity_capacity_verif::CapacityReserveCause}::eq]:
    Source: 'src/lib.rs', lines 10:29-10:38
    Visibility: public -/
def CapacityReserveCause.Insts.CoreCmpPartialEqCapacityReserveCause.eq
  (self : CapacityReserveCause) (other : CapacityReserveCause) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityReserveCause> for parity_capacity_verif::CapacityReserveCause}]
    Source: 'src/lib.rs', lines 10:29-10:38 -/
@[reducible]
def CapacityReserveCause.Insts.CoreCmpPartialEqCapacityReserveCause :
  core.cmp.PartialEq CapacityReserveCause CapacityReserveCause := {
  eq := CapacityReserveCause.Insts.CoreCmpPartialEqCapacityReserveCause.eq
}

/-- [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityReserveCause}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 10:40-10:42
    Visibility: public -/
def CapacityReserveCause.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CapacityReserveCause) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityReserveCause}]
    Source: 'src/lib.rs', lines 10:40-10:42 -/
@[reducible]
def CapacityReserveCause.Insts.CoreCmpEq : core.cmp.Eq CapacityReserveCause
  := {
  partialEqInst :=
    CapacityReserveCause.Insts.CoreCmpPartialEqCapacityReserveCause
  assert_fields_are_eq :=
    CapacityReserveCause.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_capacity_verif::CapacityError]
    Source: 'src/lib.rs', lines 17:0-25:1
    Visibility: public -/
@[discriminant isize]
inductive CapacityError where
| BlockSizeZero : CapacityError
| DataShardsPerEpochZero : CapacityError
| CurrentEpochFillOutsideOpenEpoch : CapacityError
| ArithmeticOverflow : CapacityError
| ObjectTooLargeForEmptyTape : CapacityError
| CapacityReserveExceededTape : CapacityError
| CapacityReserveExceededSpool : CapacityError

/-- [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityError}::clone]:
    Source: 'src/lib.rs', lines 16:9-16:14
    Visibility: public -/
def CapacityError.Insts.CoreCloneClone.clone
  (self : CapacityError) : Result CapacityError := do
  ok self

/-- Trait implementation: [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityError}]
    Source: 'src/lib.rs', lines 16:9-16:14 -/
@[reducible]
def CapacityError.Insts.CoreCloneClone : core.clone.Clone CapacityError := {
  clone := CapacityError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::Copy for parity_capacity_verif::CapacityError}]
    Source: 'src/lib.rs', lines 16:16-16:20 -/
@[reducible]
def CapacityError.Insts.CoreMarkerCopy : core.marker.Copy CapacityError := {
  cloneInst := CapacityError.Insts.CoreCloneClone
}

/-- [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityError}::fmt]:
    Source: 'src/lib.rs', lines 16:22-16:27
    Visibility: public -/
def CapacityError.Insts.CoreFmtDebug.fmt
  (self : CapacityError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | CapacityError.BlockSizeZero =>
    core.fmt.Formatter.write_str f (toStr "BlockSizeZero")
  | CapacityError.DataShardsPerEpochZero =>
    core.fmt.Formatter.write_str f (toStr "DataShardsPerEpochZero")
  | CapacityError.CurrentEpochFillOutsideOpenEpoch =>
    core.fmt.Formatter.write_str f (toStr "CurrentEpochFillOutsideOpenEpoch")
  | CapacityError.ArithmeticOverflow =>
    core.fmt.Formatter.write_str f (toStr "ArithmeticOverflow")
  | CapacityError.ObjectTooLargeForEmptyTape =>
    core.fmt.Formatter.write_str f (toStr "ObjectTooLargeForEmptyTape")
  | CapacityError.CapacityReserveExceededTape =>
    core.fmt.Formatter.write_str f (toStr "CapacityReserveExceededTape")
  | CapacityError.CapacityReserveExceededSpool =>
    core.fmt.Formatter.write_str f (toStr "CapacityReserveExceededSpool")

/-- Trait implementation: [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityError}]
    Source: 'src/lib.rs', lines 16:22-16:27 -/
@[reducible]
def CapacityError.Insts.CoreFmtDebug : core.fmt.Debug CapacityError := {
  fmt := CapacityError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::StructuralPartialEq for parity_capacity_verif::CapacityError}]
    Source: 'src/lib.rs', lines 16:29-16:38 -/
@[reducible]
def CapacityError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CapacityError := {
}

/-- [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityError> for parity_capacity_verif::CapacityError}::eq]:
    Source: 'src/lib.rs', lines 16:29-16:38
    Visibility: public -/
def CapacityError.Insts.CoreCmpPartialEqCapacityError.eq
  (self : CapacityError) (other : CapacityError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityError> for parity_capacity_verif::CapacityError}]
    Source: 'src/lib.rs', lines 16:29-16:38 -/
@[reducible]
def CapacityError.Insts.CoreCmpPartialEqCapacityError : core.cmp.PartialEq
  CapacityError CapacityError := {
  eq := CapacityError.Insts.CoreCmpPartialEqCapacityError.eq
}

/-- [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 16:40-16:42
    Visibility: public -/
def CapacityError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CapacityError) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityError}]
    Source: 'src/lib.rs', lines 16:40-16:42 -/
@[reducible]
def CapacityError.Insts.CoreCmpEq : core.cmp.Eq CapacityError := {
  partialEqInst := CapacityError.Insts.CoreCmpPartialEqCapacityError
  assert_fields_are_eq := CapacityError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_capacity_verif::CapacityReserveInput]
    Source: 'src/lib.rs', lines 28:0-45:1
    Visibility: public -/
structure CapacityReserveInput where
  projected_object_blocks : Std.U64
  block_size_bytes : Std.U64
  current_epoch_fill_blocks : Std.U64
  data_shards_per_epoch : Std.U64
  parity_shards_per_epoch : Std.U64
  sidecar_index_block_count : Std.U64
  object_filemark_blocks : Std.U64
  sidecar_filemark_blocks : Std.U64
  bootstrap_filemark_blocks : Std.U64
  pending_completed_sidecars : Std.U64
  remaining_bootstrap_count : Std.U64
  safety_margin_blocks : Std.U64
  remaining_tape_blocks : Std.U64
  empty_tape_usable_blocks : Std.U64
  pending_completed_epoch_parity_bytes : Std.U64
  remaining_spool_bytes : Std.U64

/-- [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityReserveInput}::clone]:
    Source: 'src/lib.rs', lines 27:9-27:14
    Visibility: public -/
def CapacityReserveInput.Insts.CoreCloneClone.clone
  (self : CapacityReserveInput) : Result CapacityReserveInput := do
  ok self

/-- Trait implementation: [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityReserveInput}]
    Source: 'src/lib.rs', lines 27:9-27:14 -/
@[reducible]
def CapacityReserveInput.Insts.CoreCloneClone : core.clone.Clone
  CapacityReserveInput := {
  clone := CapacityReserveInput.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::Copy for parity_capacity_verif::CapacityReserveInput}]
    Source: 'src/lib.rs', lines 27:16-27:20 -/
@[reducible]
def CapacityReserveInput.Insts.CoreMarkerCopy : core.marker.Copy
  CapacityReserveInput := {
  cloneInst := CapacityReserveInput.Insts.CoreCloneClone
}

/-- [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityReserveInput}::fmt]:
    Source: 'src/lib.rs', lines 27:22-27:27
    Visibility: public -/
def CapacityReserveInput.Insts.CoreFmtDebug.fmt
  (self : CapacityReserveInput) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.projected_object_blocks
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.block_size_bytes
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.current_epoch_fill_blocks
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.data_shards_per_epoch
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.parity_shards_per_epoch
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.sidecar_index_block_count
  let dyn6 := Dyn.mk _ core.fmt.DebugU64 self.object_filemark_blocks
  let dyn7 := Dyn.mk _ core.fmt.DebugU64 self.sidecar_filemark_blocks
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.bootstrap_filemark_blocks
  let dyn9 := Dyn.mk _ core.fmt.DebugU64 self.pending_completed_sidecars
  let dyn10 := Dyn.mk _ core.fmt.DebugU64 self.remaining_bootstrap_count
  let dyn11 := Dyn.mk _ core.fmt.DebugU64 self.safety_margin_blocks
  let dyn12 := Dyn.mk _ core.fmt.DebugU64 self.remaining_tape_blocks
  let dyn13 := Dyn.mk _ core.fmt.DebugU64 self.empty_tape_usable_blocks
  let dyn14 :=
    Dyn.mk _ core.fmt.DebugU64 self.pending_completed_epoch_parity_bytes
  let dyn15 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64)
      self.remaining_spool_bytes
  let values :=
    Array.to_slice
      (Array.make 16#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 16#usize [
        toStr "projected_object_blocks", toStr "block_size_bytes", toStr
        "current_epoch_fill_blocks", toStr "data_shards_per_epoch", toStr
        "parity_shards_per_epoch", toStr "sidecar_index_block_count", toStr
        "object_filemark_blocks", toStr "sidecar_filemark_blocks", toStr
        "bootstrap_filemark_blocks", toStr "pending_completed_sidecars", toStr
        "remaining_bootstrap_count", toStr "safety_margin_blocks", toStr
        "remaining_tape_blocks", toStr "empty_tape_usable_blocks", toStr
        "pending_completed_epoch_parity_bytes", toStr "remaining_spool_bytes"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr
    "CapacityReserveInput") s values

/-- Trait implementation: [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityReserveInput}]
    Source: 'src/lib.rs', lines 27:22-27:27 -/
@[reducible]
def CapacityReserveInput.Insts.CoreFmtDebug : core.fmt.Debug
  CapacityReserveInput := {
  fmt := CapacityReserveInput.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::StructuralPartialEq for parity_capacity_verif::CapacityReserveInput}]
    Source: 'src/lib.rs', lines 27:29-27:38 -/
@[reducible]
def CapacityReserveInput.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CapacityReserveInput := {
}

/-- [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityReserveInput> for parity_capacity_verif::CapacityReserveInput}::eq]:
    Source: 'src/lib.rs', lines 27:29-27:38
    Visibility: public -/
def CapacityReserveInput.Insts.CoreCmpPartialEqCapacityReserveInput.eq
  (self : CapacityReserveInput) (other : CapacityReserveInput) :
  Result Bool
  := do
  if self.projected_object_blocks = other.projected_object_blocks
  then
    if self.block_size_bytes = other.block_size_bytes
    then
      if self.current_epoch_fill_blocks = other.current_epoch_fill_blocks
      then
        if self.data_shards_per_epoch = other.data_shards_per_epoch
        then
          if self.parity_shards_per_epoch = other.parity_shards_per_epoch
          then
            if self.sidecar_index_block_count = other.sidecar_index_block_count
            then
              if self.object_filemark_blocks = other.object_filemark_blocks
              then
                if self.sidecar_filemark_blocks = other.sidecar_filemark_blocks
                then
                  if self.bootstrap_filemark_blocks =
                    other.bootstrap_filemark_blocks
                  then
                    if self.pending_completed_sidecars =
                      other.pending_completed_sidecars
                    then
                      if self.remaining_bootstrap_count =
                        other.remaining_bootstrap_count
                      then
                        if self.safety_margin_blocks =
                          other.safety_margin_blocks
                        then
                          if self.remaining_tape_blocks =
                            other.remaining_tape_blocks
                          then
                            if self.empty_tape_usable_blocks =
                              other.empty_tape_usable_blocks
                            then
                              if self.pending_completed_epoch_parity_bytes =
                                other.pending_completed_epoch_parity_bytes
                              then
                                ok (self.remaining_spool_bytes =
                                  other.remaining_spool_bytes)
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityReserveInput> for parity_capacity_verif::CapacityReserveInput}]
    Source: 'src/lib.rs', lines 27:29-27:38 -/
@[reducible]
def CapacityReserveInput.Insts.CoreCmpPartialEqCapacityReserveInput :
  core.cmp.PartialEq CapacityReserveInput CapacityReserveInput := {
  eq := CapacityReserveInput.Insts.CoreCmpPartialEqCapacityReserveInput.eq
}

/-- [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityReserveInput}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 27:40-27:42
    Visibility: public -/
def CapacityReserveInput.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CapacityReserveInput) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityReserveInput}]
    Source: 'src/lib.rs', lines 27:40-27:42 -/
@[reducible]
def CapacityReserveInput.Insts.CoreCmpEq : core.cmp.Eq CapacityReserveInput
  := {
  partialEqInst :=
    CapacityReserveInput.Insts.CoreCmpPartialEqCapacityReserveInput
  assert_fields_are_eq :=
    CapacityReserveInput.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_capacity_verif::TapeReserveReport]
    Source: 'src/lib.rs', lines 48:0-55:1
    Visibility: public -/
structure TapeReserveReport where
  epochs_completed_by_object : Std.U64
  final_partial_sidecar_needed : Bool
  sidecar_tape_file_blocks : Std.U64
  bootstrap_tape_file_blocks : Std.U64
  reserve_after_object_blocks : Std.U64
  required_tape_blocks : Std.U64

/-- [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::TapeReserveReport}::clone]:
    Source: 'src/lib.rs', lines 47:9-47:14
    Visibility: public -/
def TapeReserveReport.Insts.CoreCloneClone.clone
  (self : TapeReserveReport) : Result TapeReserveReport := do
  ok self

/-- Trait implementation: [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::TapeReserveReport}]
    Source: 'src/lib.rs', lines 47:9-47:14 -/
@[reducible]
def TapeReserveReport.Insts.CoreCloneClone : core.clone.Clone TapeReserveReport
  := {
  clone := TapeReserveReport.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::Copy for parity_capacity_verif::TapeReserveReport}]
    Source: 'src/lib.rs', lines 47:16-47:20 -/
@[reducible]
def TapeReserveReport.Insts.CoreMarkerCopy : core.marker.Copy TapeReserveReport
  := {
  cloneInst := TapeReserveReport.Insts.CoreCloneClone
}

/-- [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::TapeReserveReport}::fmt]:
    Source: 'src/lib.rs', lines 47:22-47:27
    Visibility: public -/
def TapeReserveReport.Insts.CoreFmtDebug.fmt
  (self : TapeReserveReport) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.epochs_completed_by_object
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.final_partial_sidecar_needed
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.sidecar_tape_file_blocks
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.bootstrap_tape_file_blocks
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.reserve_after_object_blocks
  let dyn5 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.required_tape_blocks
  let values :=
    Array.to_slice (Array.make 6#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5 ])
  let s ←
    lift (Array.to_slice
      (Array.make 6#usize [
        toStr "epochs_completed_by_object", toStr
        "final_partial_sidecar_needed", toStr "sidecar_tape_file_blocks", toStr
        "bootstrap_tape_file_blocks", toStr "reserve_after_object_blocks",
        toStr "required_tape_blocks"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "TapeReserveReport") s
    values

/-- Trait implementation: [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::TapeReserveReport}]
    Source: 'src/lib.rs', lines 47:22-47:27 -/
@[reducible]
def TapeReserveReport.Insts.CoreFmtDebug : core.fmt.Debug TapeReserveReport
  := {
  fmt := TapeReserveReport.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::StructuralPartialEq for parity_capacity_verif::TapeReserveReport}]
    Source: 'src/lib.rs', lines 47:29-47:38 -/
@[reducible]
def TapeReserveReport.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq TapeReserveReport := {
}

/-- [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::TapeReserveReport> for parity_capacity_verif::TapeReserveReport}::eq]:
    Source: 'src/lib.rs', lines 47:29-47:38
    Visibility: public -/
def TapeReserveReport.Insts.CoreCmpPartialEqTapeReserveReport.eq
  (self : TapeReserveReport) (other : TapeReserveReport) : Result Bool := do
  if self.epochs_completed_by_object = other.epochs_completed_by_object
  then
    if self.final_partial_sidecar_needed = other.final_partial_sidecar_needed
    then
      if self.sidecar_tape_file_blocks = other.sidecar_tape_file_blocks
      then
        if self.bootstrap_tape_file_blocks = other.bootstrap_tape_file_blocks
        then
          if self.reserve_after_object_blocks =
            other.reserve_after_object_blocks
          then ok (self.required_tape_blocks = other.required_tape_blocks)
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::TapeReserveReport> for parity_capacity_verif::TapeReserveReport}]
    Source: 'src/lib.rs', lines 47:29-47:38 -/
@[reducible]
def TapeReserveReport.Insts.CoreCmpPartialEqTapeReserveReport :
  core.cmp.PartialEq TapeReserveReport TapeReserveReport := {
  eq := TapeReserveReport.Insts.CoreCmpPartialEqTapeReserveReport.eq
}

/-- [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::TapeReserveReport}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 47:40-47:42
    Visibility: public -/
def TapeReserveReport.Insts.CoreCmpEq.assert_fields_are_eq
  (self : TapeReserveReport) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::TapeReserveReport}]
    Source: 'src/lib.rs', lines 47:40-47:42 -/
@[reducible]
def TapeReserveReport.Insts.CoreCmpEq : core.cmp.Eq TapeReserveReport := {
  partialEqInst := TapeReserveReport.Insts.CoreCmpPartialEqTapeReserveReport
  assert_fields_are_eq :=
    TapeReserveReport.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_capacity_verif::CapacityReserveReport]
    Source: 'src/lib.rs', lines 58:0-66:1
    Visibility: public -/
structure CapacityReserveReport where
  epochs_completed_by_object : Std.U64
  final_partial_sidecar_needed : Bool
  sidecar_tape_file_blocks : Std.U64
  bootstrap_tape_file_blocks : Std.U64
  reserve_after_object_blocks : Std.U64
  required_tape_blocks : Std.U64
  required_spool_bytes : Std.U64

/-- [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityReserveReport}::clone]:
    Source: 'src/lib.rs', lines 57:9-57:14
    Visibility: public -/
def CapacityReserveReport.Insts.CoreCloneClone.clone
  (self : CapacityReserveReport) : Result CapacityReserveReport := do
  ok self

/-- Trait implementation: [parity_capacity_verif::{impl core::clone::Clone for parity_capacity_verif::CapacityReserveReport}]
    Source: 'src/lib.rs', lines 57:9-57:14 -/
@[reducible]
def CapacityReserveReport.Insts.CoreCloneClone : core.clone.Clone
  CapacityReserveReport := {
  clone := CapacityReserveReport.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::Copy for parity_capacity_verif::CapacityReserveReport}]
    Source: 'src/lib.rs', lines 57:16-57:20 -/
@[reducible]
def CapacityReserveReport.Insts.CoreMarkerCopy : core.marker.Copy
  CapacityReserveReport := {
  cloneInst := CapacityReserveReport.Insts.CoreCloneClone
}

/-- [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityReserveReport}::fmt]:
    Source: 'src/lib.rs', lines 57:22-57:27
    Visibility: public -/
def CapacityReserveReport.Insts.CoreFmtDebug.fmt
  (self : CapacityReserveReport) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.epochs_completed_by_object
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.final_partial_sidecar_needed
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.sidecar_tape_file_blocks
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.bootstrap_tape_file_blocks
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.reserve_after_object_blocks
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.required_tape_blocks
  let dyn6 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.required_spool_bytes
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "epochs_completed_by_object", toStr
        "final_partial_sidecar_needed", toStr "sidecar_tape_file_blocks", toStr
        "bootstrap_tape_file_blocks", toStr "reserve_after_object_blocks",
        toStr "required_tape_blocks", toStr "required_spool_bytes"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr
    "CapacityReserveReport") s values

/-- Trait implementation: [parity_capacity_verif::{impl core::fmt::Debug for parity_capacity_verif::CapacityReserveReport}]
    Source: 'src/lib.rs', lines 57:22-57:27 -/
@[reducible]
def CapacityReserveReport.Insts.CoreFmtDebug : core.fmt.Debug
  CapacityReserveReport := {
  fmt := CapacityReserveReport.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_capacity_verif::{impl core::marker::StructuralPartialEq for parity_capacity_verif::CapacityReserveReport}]
    Source: 'src/lib.rs', lines 57:29-57:38 -/
@[reducible]
def CapacityReserveReport.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CapacityReserveReport := {
}

/-- [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityReserveReport> for parity_capacity_verif::CapacityReserveReport}::eq]:
    Source: 'src/lib.rs', lines 57:29-57:38
    Visibility: public -/
def CapacityReserveReport.Insts.CoreCmpPartialEqCapacityReserveReport.eq
  (self : CapacityReserveReport) (other : CapacityReserveReport) :
  Result Bool
  := do
  if self.epochs_completed_by_object = other.epochs_completed_by_object
  then
    if self.final_partial_sidecar_needed = other.final_partial_sidecar_needed
    then
      if self.sidecar_tape_file_blocks = other.sidecar_tape_file_blocks
      then
        if self.bootstrap_tape_file_blocks = other.bootstrap_tape_file_blocks
        then
          if self.reserve_after_object_blocks =
            other.reserve_after_object_blocks
          then
            if self.required_tape_blocks = other.required_tape_blocks
            then ok (self.required_spool_bytes = other.required_spool_bytes)
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::PartialEq<parity_capacity_verif::CapacityReserveReport> for parity_capacity_verif::CapacityReserveReport}]
    Source: 'src/lib.rs', lines 57:29-57:38 -/
@[reducible]
def CapacityReserveReport.Insts.CoreCmpPartialEqCapacityReserveReport :
  core.cmp.PartialEq CapacityReserveReport CapacityReserveReport := {
  eq := CapacityReserveReport.Insts.CoreCmpPartialEqCapacityReserveReport.eq
}

/-- [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityReserveReport}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 57:40-57:42
    Visibility: public -/
def CapacityReserveReport.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CapacityReserveReport) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_capacity_verif::{impl core::cmp::Eq for parity_capacity_verif::CapacityReserveReport}]
    Source: 'src/lib.rs', lines 57:40-57:42 -/
@[reducible]
def CapacityReserveReport.Insts.CoreCmpEq : core.cmp.Eq CapacityReserveReport
  := {
  partialEqInst :=
    CapacityReserveReport.Insts.CoreCmpPartialEqCapacityReserveReport
  assert_fields_are_eq :=
    CapacityReserveReport.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_capacity_verif::checked_add]:
    Source: 'src/lib.rs', lines 68:0-73:1
    Visibility: public -/
def checked_add
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 CapacityError)
  := do
  let o ← lift (U64.checked_add a b)
  match o with
  | none => ok (core.result.Result.Err CapacityError.ArithmeticOverflow)
  | some sum => ok (core.result.Result.Ok sum)

/-- [parity_capacity_verif::checked_mul]:
    Source: 'src/lib.rs', lines 75:0-80:1
    Visibility: public -/
def checked_mul
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 CapacityError)
  := do
  let o ← lift (U64.checked_mul a b)
  match o with
  | none => ok (core.result.Result.Err CapacityError.ArithmeticOverflow)
  | some product => ok (core.result.Result.Ok product)

/-- [parity_capacity_verif::block_count_per_bootstrap]:
    Source: 'src/lib.rs', lines 82:0-84:1
    Visibility: public -/
def block_count_per_bootstrap : Result Std.U64 := do
  ok 1#u64

/-- [parity_capacity_verif::compute_tape_reserve]:
    Source: 'src/lib.rs', lines 86:0-140:1
    Visibility: public -/
def compute_tape_reserve
  (input : CapacityReserveInput) :
  Result (core.result.Result TapeReserveReport CapacityError)
  := do
  if input.block_size_bytes = 0#u64
  then ok (core.result.Result.Err CapacityError.BlockSizeZero)
  else
    if input.data_shards_per_epoch = 0#u64
    then ok (core.result.Result.Err CapacityError.DataShardsPerEpochZero)
    else
      if input.current_epoch_fill_blocks >= input.data_shards_per_epoch
      then
        ok (core.result.Result.Err
          CapacityError.CurrentEpochFillOutsideOpenEpoch)
      else
        let r ← checked_mul 2#u64 input.sidecar_index_block_count
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let r1 ← checked_add val 1#u64
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            let r2 ← checked_add val1 input.parity_shards_per_epoch
            let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
            match cf2 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let r3 ← checked_add val2 input.sidecar_filemark_blocks
              let cf3 ← core.result.Result.Insts.CoreOpsTry.branch r3
              match cf3 with
              | core.ops.control_flow.ControlFlow.Continue val3 =>
                let i ← block_count_per_bootstrap
                let r4 ← checked_add i input.bootstrap_filemark_blocks
                let cf4 ← core.result.Result.Insts.CoreOpsTry.branch r4
                match cf4 with
                | core.ops.control_flow.ControlFlow.Continue val4 =>
                  let r5 ←
                    checked_add input.current_epoch_fill_blocks
                      input.projected_object_blocks
                  let cf5 ← core.result.Result.Insts.CoreOpsTry.branch r5
                  match cf5 with
                  | core.ops.control_flow.ControlFlow.Continue val5 =>
                    let epochs_completed_by_object ←
                      val5 / input.data_shards_per_epoch
                    let i1 ← val5 % input.data_shards_per_epoch
                    let r6 ←
                      checked_mul input.pending_completed_sidecars val3
                    let cf6 ← core.result.Result.Insts.CoreOpsTry.branch r6
                    match cf6 with
                    | core.ops.control_flow.ControlFlow.Continue val6 =>
                      let r7 ← checked_mul epochs_completed_by_object val3
                      let cf7 ← core.result.Result.Insts.CoreOpsTry.branch r7
                      match cf7 with
                      | core.ops.control_flow.ControlFlow.Continue val7 =>
                        let (final_partial_sidecar_needed,
                          final_partial_sidecar_blocks) ←
                          if i1 != 0#u64
                          then ok (true, val3)
                          else ok (false, 0#u64)
                        let r8 ←
                          checked_mul input.remaining_bootstrap_count val4
                        let cf8 ←
                          core.result.Result.Insts.CoreOpsTry.branch r8
                        match cf8 with
                        | core.ops.control_flow.ControlFlow.Continue val8 =>
                          let r9 ←
                            checked_add input.object_filemark_blocks val6
                          let cf9 ←
                            core.result.Result.Insts.CoreOpsTry.branch r9
                          match cf9 with
                          | core.ops.control_flow.ControlFlow.Continue val9 =>
                            let r10 ← checked_add val9 val7
                            let cf10 ←
                              core.result.Result.Insts.CoreOpsTry.branch r10
                            match cf10 with
                            | core.ops.control_flow.ControlFlow.Continue val10
                              =>
                              let r11 ←
                                checked_add val10 final_partial_sidecar_blocks
                              let cf11 ←
                                core.result.Result.Insts.CoreOpsTry.branch r11
                              match cf11 with
                              | core.ops.control_flow.ControlFlow.Continue
                                val11 =>
                                let r12 ← checked_add val11 val8
                                let cf12 ←
                                  core.result.Result.Insts.CoreOpsTry.branch
                                    r12
                                match cf12 with
                                | core.ops.control_flow.ControlFlow.Continue
                                  val12 =>
                                  let r13 ←
                                    checked_add val12
                                      input.safety_margin_blocks
                                  let cf13 ←
                                    core.result.Result.Insts.CoreOpsTry.branch
                                      r13
                                  match cf13 with
                                  | core.ops.control_flow.ControlFlow.Continue
                                    val13 =>
                                    let r14 ←
                                      checked_add input.projected_object_blocks
                                        val13
                                    let cf14 ←
                                      core.result.Result.Insts.CoreOpsTry.branch
                                        r14
                                    match cf14 with
                                    |
                                      core.ops.control_flow.ControlFlow.Continue
                                      val14 =>
                                      ok (core.result.Result.Ok
                                        {
                                          epochs_completed_by_object,
                                          final_partial_sidecar_needed,
                                          sidecar_tape_file_blocks := val3,
                                          bootstrap_tape_file_blocks := val4,
                                          reserve_after_object_blocks := val13,
                                          required_tape_blocks := val14
                                        })
                                    | core.ops.control_flow.ControlFlow.Break
                                      residual =>
                                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                        TapeReserveReport
                                        (core.convert.FromSame CapacityError)
                                        residual
                                  | core.ops.control_flow.ControlFlow.Break
                                    residual =>
                                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                      TapeReserveReport (core.convert.FromSame
                                      CapacityError) residual
                                | core.ops.control_flow.ControlFlow.Break
                                  residual =>
                                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                    TapeReserveReport (core.convert.FromSame
                                    CapacityError) residual
                              | core.ops.control_flow.ControlFlow.Break
                                residual =>
                                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                  TapeReserveReport (core.convert.FromSame
                                  CapacityError) residual
                            | core.ops.control_flow.ControlFlow.Break residual
                              =>
                              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                TapeReserveReport (core.convert.FromSame
                                CapacityError) residual
                          | core.ops.control_flow.ControlFlow.Break residual =>
                            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                              TapeReserveReport (core.convert.FromSame
                              CapacityError) residual
                        | core.ops.control_flow.ControlFlow.Break residual =>
                          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                            TapeReserveReport (core.convert.FromSame
                            CapacityError) residual
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                          TapeReserveReport (core.convert.FromSame
                          CapacityError) residual
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                        TapeReserveReport (core.convert.FromSame CapacityError)
                        residual
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                      TapeReserveReport (core.convert.FromSame CapacityError)
                      residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                    TapeReserveReport (core.convert.FromSame CapacityError)
                    residual
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  TapeReserveReport (core.convert.FromSame CapacityError)
                  residual
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                TapeReserveReport (core.convert.FromSame CapacityError)
                residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              TapeReserveReport (core.convert.FromSame CapacityError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            TapeReserveReport (core.convert.FromSame CapacityError) residual

/-- [parity_capacity_verif::compute_spool_reserve]:
    Source: 'src/lib.rs', lines 142:0-154:1
    Visibility: public -/
def compute_spool_reserve
  (input : CapacityReserveInput) (epochs_completed_by_object : Std.U64)
  (sidecar_tape_file_blocks : Std.U64) :
  Result (core.result.Result Std.U64 CapacityError)
  := do
  let r ← checked_mul sidecar_tape_file_blocks input.block_size_bytes
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← checked_mul epochs_completed_by_object val
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      checked_add input.pending_completed_epoch_parity_bytes val1
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U64 (core.convert.FromSame CapacityError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame CapacityError) residual

/-- [parity_capacity_verif::evaluate]:
    Source: 'src/lib.rs', lines 156:0-186:1
    Visibility: public -/
def evaluate
  (input : CapacityReserveInput) :
  Result (core.result.Result CapacityReserveReport CapacityError)
  := do
  let r ← compute_tape_reserve input
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if input.empty_tape_usable_blocks < val.required_tape_blocks
    then ok (core.result.Result.Err CapacityError.ObjectTooLargeForEmptyTape)
    else
      if input.remaining_tape_blocks < val.required_tape_blocks
      then
        ok (core.result.Result.Err CapacityError.CapacityReserveExceededTape)
      else
        let r1 ←
          compute_spool_reserve input val.epochs_completed_by_object
            val.sidecar_tape_file_blocks
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          if input.remaining_spool_bytes < val1
          then
            ok (core.result.Result.Err
              CapacityError.CapacityReserveExceededSpool)
          else
            ok (core.result.Result.Ok
              {
                epochs_completed_by_object := val.epochs_completed_by_object,
                final_partial_sidecar_needed :=
                  val.final_partial_sidecar_needed,
                sidecar_tape_file_blocks := val.sidecar_tape_file_blocks,
                bootstrap_tape_file_blocks := val.bootstrap_tape_file_blocks,
                reserve_after_object_blocks := val.reserve_after_object_blocks,
                required_tape_blocks := val.required_tape_blocks,
                required_spool_bytes := val1
              })
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            CapacityReserveReport (core.convert.FromSame CapacityError)
            residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      CapacityReserveReport (core.convert.FromSame CapacityError) residual

end parity_capacity_verif
