-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_manifest_verif]: function definitions
import Aeneas
import RaoManifest.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoManifest

/-- [rao_manifest_verif::CHUNK_SIZE_GRANULARITY]
    Source: 'src/lib.rs', lines 18:0-18:44
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_SIZE_GRANULARITY : Std.U64 := 512#u64

/-- [rao_manifest_verif::SCHEMA_VERSION]
    Source: 'src/lib.rs', lines 19:0-19:34
    Visibility: public -/
@[global_simps, irreducible] def SCHEMA_VERSION : Std.U64 := 1#u64

/-- [rao_manifest_verif::ROOT_MAP_LEN]
    Source: 'src/lib.rs', lines 20:0-20:32
    Visibility: public -/
@[global_simps, irreducible] def ROOT_MAP_LEN : Std.U64 := 7#u64

/-- [rao_manifest_verif::FILE_ENTRIES_LEN_ONE]
    Source: 'src/lib.rs', lines 21:0-21:40
    Visibility: public -/
@[global_simps, irreducible] def FILE_ENTRIES_LEN_ONE : Std.U64 := 1#u64

/-- [rao_manifest_verif::FILE_ENTRY_REGULAR_MAP_LEN]
    Source: 'src/lib.rs', lines 22:0-22:46
    Visibility: public -/
@[global_simps, irreducible] def FILE_ENTRY_REGULAR_MAP_LEN : Std.U64 := 8#u64

/-- [rao_manifest_verif::DIGEST_BYTE_LEN]
    Source: 'src/lib.rs', lines 23:0-23:36
    Visibility: public -/
@[global_simps, irreducible] def DIGEST_BYTE_LEN : Std.U64 := 32#u64

/-- [rao_manifest_verif::ROOT_KEY_OBJECT_ID]
    Source: 'src/lib.rs', lines 25:0-25:38
    Visibility: public -/
@[global_simps, irreducible] def ROOT_KEY_OBJECT_ID : Std.U64 := 0#u64

/-- [rao_manifest_verif::ROOT_KEY_CHUNK_SIZE]
    Source: 'src/lib.rs', lines 26:0-26:39
    Visibility: public -/
@[global_simps, irreducible] def ROOT_KEY_CHUNK_SIZE : Std.U64 := 1#u64

/-- [rao_manifest_verif::ROOT_KEY_FILE_ENTRIES]
    Source: 'src/lib.rs', lines 27:0-27:41
    Visibility: public -/
@[global_simps, irreducible] def ROOT_KEY_FILE_ENTRIES : Std.U64 := 2#u64

/-- [rao_manifest_verif::ROOT_KEY_SCHEMA_VERSION]
    Source: 'src/lib.rs', lines 28:0-28:43
    Visibility: public -/
@[global_simps, irreducible] def ROOT_KEY_SCHEMA_VERSION : Std.U64 := 3#u64

/-- [rao_manifest_verif::ROOT_KEY_OBJECT_METADATA]
    Source: 'src/lib.rs', lines 29:0-29:44
    Visibility: public -/
@[global_simps, irreducible] def ROOT_KEY_OBJECT_METADATA : Std.U64 := 4#u64

/-- [rao_manifest_verif::ROOT_KEY_CALLER_OBJECT_ID]
    Source: 'src/lib.rs', lines 30:0-30:45
    Visibility: public -/
@[global_simps, irreducible] def ROOT_KEY_CALLER_OBJECT_ID : Std.U64 := 5#u64

/-- [rao_manifest_verif::ROOT_KEY_EXTERNAL_REFERENCES]
    Source: 'src/lib.rs', lines 31:0-31:48
    Visibility: public -/
@[global_simps, irreducible]
def ROOT_KEY_EXTERNAL_REFERENCES : Std.U64 := 6#u64

/-- [rao_manifest_verif::FILE_KEY_PATH]
    Source: 'src/lib.rs', lines 33:0-33:33
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_PATH : Std.U64 := 0#u64

/-- [rao_manifest_verif::FILE_KEY_FILE_ID]
    Source: 'src/lib.rs', lines 34:0-34:36
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_FILE_ID : Std.U64 := 1#u64

/-- [rao_manifest_verif::FILE_KEY_EXECUTABLE]
    Source: 'src/lib.rs', lines 35:0-35:39
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_EXECUTABLE : Std.U64 := 2#u64

/-- [rao_manifest_verif::FILE_KEY_SIZE_BYTES]
    Source: 'src/lib.rs', lines 36:0-36:39
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_SIZE_BYTES : Std.U64 := 3#u64

/-- [rao_manifest_verif::FILE_KEY_CHUNK_COUNT]
    Source: 'src/lib.rs', lines 37:0-37:40
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_CHUNK_COUNT : Std.U64 := 4#u64

/-- [rao_manifest_verif::FILE_KEY_FILE_SHA256]
    Source: 'src/lib.rs', lines 38:0-38:40
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_FILE_SHA256 : Std.U64 := 5#u64

/-- [rao_manifest_verif::FILE_KEY_FIRST_CHUNK_LBA]
    Source: 'src/lib.rs', lines 39:0-39:44
    Visibility: public -/
@[global_simps, irreducible] def FILE_KEY_FIRST_CHUNK_LBA : Std.U64 := 6#u64

/-- [rao_manifest_verif::FILE_KEY_METADATA_PRESERVATION_DATA]
    Source: 'src/lib.rs', lines 40:0-40:55
    Visibility: public -/
@[global_simps, irreducible]
def FILE_KEY_METADATA_PRESERVATION_DATA : Std.U64 := 7#u64

/-- [rao_manifest_verif::EXECUTABLE_NULL]
    Source: 'src/lib.rs', lines 42:0-42:34
    Visibility: public -/
@[global_simps, irreducible] def EXECUTABLE_NULL : Std.U8 := 0#u8

/-- [rao_manifest_verif::EXECUTABLE_FALSE]
    Source: 'src/lib.rs', lines 43:0-43:35
    Visibility: public -/
@[global_simps, irreducible] def EXECUTABLE_FALSE : Std.U8 := 1#u8

/-- [rao_manifest_verif::EXECUTABLE_TRUE]
    Source: 'src/lib.rs', lines 44:0-44:34
    Visibility: public -/
@[global_simps, irreducible] def EXECUTABLE_TRUE : Std.U8 := 2#u8

/-- [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::RaoManifestError}::clone]:
    Source: 'src/lib.rs', lines 46:9-46:14
    Visibility: public -/
def RaoManifestError.Insts.CoreCloneClone.clone
  (self : RaoManifestError) : Result RaoManifestError := do
  ok self

/-- Trait implementation: [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::RaoManifestError}]
    Source: 'src/lib.rs', lines 46:9-46:14 -/
@[reducible]
def RaoManifestError.Insts.CoreCloneClone : core.clone.Clone RaoManifestError
  := {
  clone := RaoManifestError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::Copy for rao_manifest_verif::RaoManifestError}]
    Source: 'src/lib.rs', lines 46:16-46:20 -/
@[reducible]
def RaoManifestError.Insts.CoreMarkerCopy : core.marker.Copy RaoManifestError
  := {
  cloneInst := RaoManifestError.Insts.CoreCloneClone
}

/-- [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::RaoManifestError}::fmt]:
    Source: 'src/lib.rs', lines 46:22-46:27
    Visibility: public -/
def RaoManifestError.Insts.CoreFmtDebug.fmt
  (self : RaoManifestError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | RaoManifestError.InvalidChunkSize =>
    core.fmt.Formatter.write_str f (toStr "InvalidChunkSize")
  | RaoManifestError.InvalidManifestField =>
    core.fmt.Formatter.write_str f (toStr "InvalidManifestField")
  | RaoManifestError.InvalidCborEncoding =>
    core.fmt.Formatter.write_str f (toStr "InvalidCborEncoding")
  | RaoManifestError.MissingRequiredManifestField =>
    core.fmt.Formatter.write_str f (toStr "MissingRequiredManifestField")

/-- Trait implementation: [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::RaoManifestError}]
    Source: 'src/lib.rs', lines 46:22-46:27 -/
@[reducible]
def RaoManifestError.Insts.CoreFmtDebug : core.fmt.Debug RaoManifestError := {
  fmt := RaoManifestError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::StructuralPartialEq for rao_manifest_verif::RaoManifestError}]
    Source: 'src/lib.rs', lines 46:29-46:38 -/
@[reducible]
def RaoManifestError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RaoManifestError := {
}

/-- [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::RaoManifestError> for rao_manifest_verif::RaoManifestError}::eq]:
    Source: 'src/lib.rs', lines 46:29-46:38
    Visibility: public -/
def RaoManifestError.Insts.CoreCmpPartialEqRaoManifestError.eq
  (self : RaoManifestError) (other : RaoManifestError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::RaoManifestError> for rao_manifest_verif::RaoManifestError}]
    Source: 'src/lib.rs', lines 46:29-46:38 -/
@[reducible]
def RaoManifestError.Insts.CoreCmpPartialEqRaoManifestError :
  core.cmp.PartialEq RaoManifestError RaoManifestError := {
  eq := RaoManifestError.Insts.CoreCmpPartialEqRaoManifestError.eq
}

/-- [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::RaoManifestError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 46:40-46:42
    Visibility: public -/
def RaoManifestError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RaoManifestError) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::RaoManifestError}]
    Source: 'src/lib.rs', lines 46:40-46:42 -/
@[reducible]
def RaoManifestError.Insts.CoreCmpEq : core.cmp.Eq RaoManifestError := {
  partialEqInst := RaoManifestError.Insts.CoreCmpPartialEqRaoManifestError
  assert_fields_are_eq := RaoManifestError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::DigestWords}::clone]:
    Source: 'src/lib.rs', lines 54:9-54:14
    Visibility: public -/
def DigestWords.Insts.CoreCloneClone.clone
  (self : DigestWords) : Result DigestWords := do
  ok self

/-- Trait implementation: [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::DigestWords}]
    Source: 'src/lib.rs', lines 54:9-54:14 -/
@[reducible]
def DigestWords.Insts.CoreCloneClone : core.clone.Clone DigestWords := {
  clone := DigestWords.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::Copy for rao_manifest_verif::DigestWords}]
    Source: 'src/lib.rs', lines 54:16-54:20 -/
@[reducible]
def DigestWords.Insts.CoreMarkerCopy : core.marker.Copy DigestWords := {
  cloneInst := DigestWords.Insts.CoreCloneClone
}

/-- [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::DigestWords}::fmt]:
    Source: 'src/lib.rs', lines 54:22-54:27
    Visibility: public -/
def DigestWords.Insts.CoreFmtDebug.fmt
  (self : DigestWords) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.w0
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.w1
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.w2
  let dyn3 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.w3
  core.fmt.Formatter.debug_struct_field4_finish f (toStr "DigestWords") (toStr
    "w0") dyn (toStr "w1") dyn1 (toStr "w2") dyn2 (toStr "w3") dyn3

/-- Trait implementation: [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::DigestWords}]
    Source: 'src/lib.rs', lines 54:22-54:27 -/
@[reducible]
def DigestWords.Insts.CoreFmtDebug : core.fmt.Debug DigestWords := {
  fmt := DigestWords.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::StructuralPartialEq for rao_manifest_verif::DigestWords}]
    Source: 'src/lib.rs', lines 54:29-54:38 -/
@[reducible]
def DigestWords.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq DigestWords := {
}

/-- [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::DigestWords> for rao_manifest_verif::DigestWords}::eq]:
    Source: 'src/lib.rs', lines 54:29-54:38
    Visibility: public -/
def DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
  (self : DigestWords) (other : DigestWords) : Result Bool := do
  if self.w0 = other.w0
  then
    if self.w1 = other.w1
    then if self.w2 = other.w2
         then ok (self.w3 = other.w3)
         else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::DigestWords> for rao_manifest_verif::DigestWords}]
    Source: 'src/lib.rs', lines 54:29-54:38 -/
@[reducible]
def DigestWords.Insts.CoreCmpPartialEqDigestWords : core.cmp.PartialEq
  DigestWords DigestWords := {
  eq := DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
}

/-- [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::DigestWords}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 54:40-54:42
    Visibility: public -/
def DigestWords.Insts.CoreCmpEq.assert_fields_are_eq
  (self : DigestWords) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::DigestWords}]
    Source: 'src/lib.rs', lines 54:40-54:42 -/
@[reducible]
def DigestWords.Insts.CoreCmpEq : core.cmp.Eq DigestWords := {
  partialEqInst := DigestWords.Insts.CoreCmpPartialEqDigestWords
  assert_fields_are_eq := DigestWords.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::RegularFileCore}::clone]:
    Source: 'src/lib.rs', lines 62:9-62:14
    Visibility: public -/
def RegularFileCore.Insts.CoreCloneClone.clone
  (self : RegularFileCore) : Result RegularFileCore := do
  ok self

/-- Trait implementation: [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::RegularFileCore}]
    Source: 'src/lib.rs', lines 62:9-62:14 -/
@[reducible]
def RegularFileCore.Insts.CoreCloneClone : core.clone.Clone RegularFileCore
  := {
  clone := RegularFileCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::Copy for rao_manifest_verif::RegularFileCore}]
    Source: 'src/lib.rs', lines 62:16-62:20 -/
@[reducible]
def RegularFileCore.Insts.CoreMarkerCopy : core.marker.Copy RegularFileCore
  := {
  cloneInst := RegularFileCore.Insts.CoreCloneClone
}

/-- [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::RegularFileCore}::fmt]:
    Source: 'src/lib.rs', lines 62:22-62:27
    Visibility: public -/
def RegularFileCore.Insts.CoreFmtDebug.fmt
  (self : RegularFileCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.path_id
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.file_id
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.size_bytes
  let dyn3 := Dyn.mk _ DigestWords.Insts.CoreFmtDebug self.file_sha256
  let dyn4 := Dyn.mk _ core.fmt.DebugBool self.first_chunk_lba_present
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.first_chunk_lba
  let dyn6 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU8) self.executable_tag
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "path_id", toStr "file_id", toStr "size_bytes", toStr
        "file_sha256", toStr "first_chunk_lba_present", toStr
        "first_chunk_lba", toStr "executable_tag"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "RegularFileCore") s
    values

/-- Trait implementation: [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::RegularFileCore}]
    Source: 'src/lib.rs', lines 62:22-62:27 -/
@[reducible]
def RegularFileCore.Insts.CoreFmtDebug : core.fmt.Debug RegularFileCore := {
  fmt := RegularFileCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::StructuralPartialEq for rao_manifest_verif::RegularFileCore}]
    Source: 'src/lib.rs', lines 62:29-62:38 -/
@[reducible]
def RegularFileCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RegularFileCore := {
}

/-- [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::RegularFileCore> for rao_manifest_verif::RegularFileCore}::eq]:
    Source: 'src/lib.rs', lines 62:29-62:38
    Visibility: public -/
def RegularFileCore.Insts.CoreCmpPartialEqRegularFileCore.eq
  (self : RegularFileCore) (other : RegularFileCore) : Result Bool := do
  if self.path_id = other.path_id
  then
    if self.file_id = other.file_id
    then
      if self.size_bytes = other.size_bytes
      then
        if self.first_chunk_lba_present = other.first_chunk_lba_present
        then
          if self.first_chunk_lba = other.first_chunk_lba
          then
            if self.executable_tag = other.executable_tag
            then
              DigestWords.Insts.CoreCmpPartialEqDigestWords.eq self.file_sha256
                other.file_sha256
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::RegularFileCore> for rao_manifest_verif::RegularFileCore}]
    Source: 'src/lib.rs', lines 62:29-62:38 -/
@[reducible]
def RegularFileCore.Insts.CoreCmpPartialEqRegularFileCore : core.cmp.PartialEq
  RegularFileCore RegularFileCore := {
  eq := RegularFileCore.Insts.CoreCmpPartialEqRegularFileCore.eq
}

/-- [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::RegularFileCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 62:40-62:42
    Visibility: public -/
def RegularFileCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RegularFileCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::RegularFileCore}]
    Source: 'src/lib.rs', lines 62:40-62:42 -/
@[reducible]
def RegularFileCore.Insts.CoreCmpEq : core.cmp.Eq RegularFileCore := {
  partialEqInst := RegularFileCore.Insts.CoreCmpPartialEqRegularFileCore
  assert_fields_are_eq := RegularFileCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::ManifestCore}::clone]:
    Source: 'src/lib.rs', lines 73:9-73:14
    Visibility: public -/
def ManifestCore.Insts.CoreCloneClone.clone
  (self : ManifestCore) : Result ManifestCore := do
  ok self

/-- Trait implementation: [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::ManifestCore}]
    Source: 'src/lib.rs', lines 73:9-73:14 -/
@[reducible]
def ManifestCore.Insts.CoreCloneClone : core.clone.Clone ManifestCore := {
  clone := ManifestCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::Copy for rao_manifest_verif::ManifestCore}]
    Source: 'src/lib.rs', lines 73:16-73:20 -/
@[reducible]
def ManifestCore.Insts.CoreMarkerCopy : core.marker.Copy ManifestCore := {
  cloneInst := ManifestCore.Insts.CoreCloneClone
}

/-- [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::ManifestCore}::fmt]:
    Source: 'src/lib.rs', lines 73:22-73:27
    Visibility: public -/
def ManifestCore.Insts.CoreFmtDebug.fmt
  (self : ManifestCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.object_id
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.caller_object_id
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.chunk_size
  let dyn3 :=
    Dyn.mk _ (core.fmt.DebugShared RegularFileCore.Insts.CoreFmtDebug)
      self.file
  core.fmt.Formatter.debug_struct_field4_finish f (toStr "ManifestCore") (toStr
    "object_id") dyn (toStr "caller_object_id") dyn1 (toStr "chunk_size") dyn2
    (toStr "file") dyn3

/-- Trait implementation: [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::ManifestCore}]
    Source: 'src/lib.rs', lines 73:22-73:27 -/
@[reducible]
def ManifestCore.Insts.CoreFmtDebug : core.fmt.Debug ManifestCore := {
  fmt := ManifestCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::StructuralPartialEq for rao_manifest_verif::ManifestCore}]
    Source: 'src/lib.rs', lines 73:29-73:38 -/
@[reducible]
def ManifestCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ManifestCore := {
}

/-- [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::ManifestCore> for rao_manifest_verif::ManifestCore}::eq]:
    Source: 'src/lib.rs', lines 73:29-73:38
    Visibility: public -/
def ManifestCore.Insts.CoreCmpPartialEqManifestCore.eq
  (self : ManifestCore) (other : ManifestCore) : Result Bool := do
  if self.object_id = other.object_id
  then
    if self.caller_object_id = other.caller_object_id
    then
      if self.chunk_size = other.chunk_size
      then
        RegularFileCore.Insts.CoreCmpPartialEqRegularFileCore.eq self.file
          other.file
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::ManifestCore> for rao_manifest_verif::ManifestCore}]
    Source: 'src/lib.rs', lines 73:29-73:38 -/
@[reducible]
def ManifestCore.Insts.CoreCmpPartialEqManifestCore : core.cmp.PartialEq
  ManifestCore ManifestCore := {
  eq := ManifestCore.Insts.CoreCmpPartialEqManifestCore.eq
}

/-- [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::ManifestCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 73:40-73:42
    Visibility: public -/
def ManifestCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ManifestCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::ManifestCore}]
    Source: 'src/lib.rs', lines 73:40-73:42 -/
@[reducible]
def ManifestCore.Insts.CoreCmpEq : core.cmp.Eq ManifestCore := {
  partialEqInst := ManifestCore.Insts.CoreCmpPartialEqManifestCore
  assert_fields_are_eq := ManifestCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::RegularFileWireCore}::clone]:
    Source: 'src/lib.rs', lines 81:9-81:14
    Visibility: public -/
def RegularFileWireCore.Insts.CoreCloneClone.clone
  (self : RegularFileWireCore) : Result RegularFileWireCore := do
  ok self

/-- Trait implementation: [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::RegularFileWireCore}]
    Source: 'src/lib.rs', lines 81:9-81:14 -/
@[reducible]
def RegularFileWireCore.Insts.CoreCloneClone : core.clone.Clone
  RegularFileWireCore := {
  clone := RegularFileWireCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::Copy for rao_manifest_verif::RegularFileWireCore}]
    Source: 'src/lib.rs', lines 81:16-81:20 -/
@[reducible]
def RegularFileWireCore.Insts.CoreMarkerCopy : core.marker.Copy
  RegularFileWireCore := {
  cloneInst := RegularFileWireCore.Insts.CoreCloneClone
}

/-- [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::RegularFileWireCore}::fmt]:
    Source: 'src/lib.rs', lines 81:22-81:27
    Visibility: public -/
def RegularFileWireCore.Insts.CoreFmtDebug.fmt
  (self : RegularFileWireCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.map_len
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.key_path
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.path_id
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.key_file_id
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.file_id
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.key_executable
  let dyn6 := Dyn.mk _ core.fmt.DebugU8 self.executable_tag
  let dyn7 := Dyn.mk _ core.fmt.DebugU64 self.key_size_bytes
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.size_bytes
  let dyn9 := Dyn.mk _ core.fmt.DebugU64 self.key_chunk_count
  let dyn10 := Dyn.mk _ core.fmt.DebugU64 self.chunk_count
  let dyn11 := Dyn.mk _ core.fmt.DebugU64 self.key_file_sha256
  let dyn12 := Dyn.mk _ core.fmt.DebugU64 self.file_sha256_len
  let dyn13 := Dyn.mk _ DigestWords.Insts.CoreFmtDebug self.file_sha256
  let dyn14 := Dyn.mk _ core.fmt.DebugU64 self.key_first_chunk_lba
  let dyn15 := Dyn.mk _ core.fmt.DebugBool self.first_chunk_lba_is_null
  let dyn16 := Dyn.mk _ core.fmt.DebugU64 self.first_chunk_lba
  let dyn17 := Dyn.mk _ core.fmt.DebugU64 self.key_metadata_preservation_data
  let dyn18 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool)
      self.metadata_preservation_data_empty
  let values :=
    Array.to_slice
      (Array.make 19#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15, dyn16, dyn17, dyn18
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 19#usize [
        toStr "map_len", toStr "key_path", toStr "path_id", toStr
        "key_file_id", toStr "file_id", toStr "key_executable", toStr
        "executable_tag", toStr "key_size_bytes", toStr "size_bytes", toStr
        "key_chunk_count", toStr "chunk_count", toStr "key_file_sha256", toStr
        "file_sha256_len", toStr "file_sha256", toStr "key_first_chunk_lba",
        toStr "first_chunk_lba_is_null", toStr "first_chunk_lba", toStr
        "key_metadata_preservation_data", toStr
        "metadata_preservation_data_empty"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "RegularFileWireCore")
    s values

/-- Trait implementation: [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::RegularFileWireCore}]
    Source: 'src/lib.rs', lines 81:22-81:27 -/
@[reducible]
def RegularFileWireCore.Insts.CoreFmtDebug : core.fmt.Debug RegularFileWireCore
  := {
  fmt := RegularFileWireCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::StructuralPartialEq for rao_manifest_verif::RegularFileWireCore}]
    Source: 'src/lib.rs', lines 81:29-81:38 -/
@[reducible]
def RegularFileWireCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RegularFileWireCore := {
}

/-- [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::RegularFileWireCore> for rao_manifest_verif::RegularFileWireCore}::eq]:
    Source: 'src/lib.rs', lines 81:29-81:38
    Visibility: public -/
def RegularFileWireCore.Insts.CoreCmpPartialEqRegularFileWireCore.eq
  (self : RegularFileWireCore) (other : RegularFileWireCore) :
  Result Bool
  := do
  if self.map_len = other.map_len
  then
    if self.key_path = other.key_path
    then
      if self.path_id = other.path_id
      then
        if self.key_file_id = other.key_file_id
        then
          if self.file_id = other.file_id
          then
            if self.key_executable = other.key_executable
            then
              if self.executable_tag = other.executable_tag
              then
                if self.key_size_bytes = other.key_size_bytes
                then
                  if self.size_bytes = other.size_bytes
                  then
                    if self.key_chunk_count = other.key_chunk_count
                    then
                      if self.chunk_count = other.chunk_count
                      then
                        if self.key_file_sha256 = other.key_file_sha256
                        then
                          if self.file_sha256_len = other.file_sha256_len
                          then
                            if self.key_first_chunk_lba =
                              other.key_first_chunk_lba
                            then
                              if self.first_chunk_lba_is_null =
                                other.first_chunk_lba_is_null
                              then
                                if self.first_chunk_lba = other.first_chunk_lba
                                then
                                  if self.key_metadata_preservation_data =
                                    other.key_metadata_preservation_data
                                  then
                                    if self.metadata_preservation_data_empty =
                                      other.metadata_preservation_data_empty
                                    then
                                      DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
                                        self.file_sha256 other.file_sha256
                                    else ok false
                                  else ok false
                                else ok false
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::RegularFileWireCore> for rao_manifest_verif::RegularFileWireCore}]
    Source: 'src/lib.rs', lines 81:29-81:38 -/
@[reducible]
def RegularFileWireCore.Insts.CoreCmpPartialEqRegularFileWireCore :
  core.cmp.PartialEq RegularFileWireCore RegularFileWireCore := {
  eq := RegularFileWireCore.Insts.CoreCmpPartialEqRegularFileWireCore.eq
}

/-- [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::RegularFileWireCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 81:40-81:42
    Visibility: public -/
def RegularFileWireCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RegularFileWireCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::RegularFileWireCore}]
    Source: 'src/lib.rs', lines 81:40-81:42 -/
@[reducible]
def RegularFileWireCore.Insts.CoreCmpEq : core.cmp.Eq RegularFileWireCore := {
  partialEqInst :=
    RegularFileWireCore.Insts.CoreCmpPartialEqRegularFileWireCore
  assert_fields_are_eq :=
    RegularFileWireCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::ManifestWireCore}::clone]:
    Source: 'src/lib.rs', lines 104:9-104:14
    Visibility: public -/
def ManifestWireCore.Insts.CoreCloneClone.clone
  (self : ManifestWireCore) : Result ManifestWireCore := do
  ok self

/-- Trait implementation: [rao_manifest_verif::{impl core::clone::Clone for rao_manifest_verif::ManifestWireCore}]
    Source: 'src/lib.rs', lines 104:9-104:14 -/
@[reducible]
def ManifestWireCore.Insts.CoreCloneClone : core.clone.Clone ManifestWireCore
  := {
  clone := ManifestWireCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::Copy for rao_manifest_verif::ManifestWireCore}]
    Source: 'src/lib.rs', lines 104:16-104:20 -/
@[reducible]
def ManifestWireCore.Insts.CoreMarkerCopy : core.marker.Copy ManifestWireCore
  := {
  cloneInst := ManifestWireCore.Insts.CoreCloneClone
}

/-- [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::ManifestWireCore}::fmt]:
    Source: 'src/lib.rs', lines 104:22-104:27
    Visibility: public -/
def ManifestWireCore.Insts.CoreFmtDebug.fmt
  (self : ManifestWireCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.root_map_len
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.key_object_id
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.object_id
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.key_chunk_size
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.chunk_size
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.key_file_entries
  let dyn6 := Dyn.mk _ core.fmt.DebugU64 self.file_entries_len
  let dyn7 := Dyn.mk _ RegularFileWireCore.Insts.CoreFmtDebug self.file
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.key_schema_version
  let dyn9 := Dyn.mk _ core.fmt.DebugU64 self.schema_version
  let dyn10 := Dyn.mk _ core.fmt.DebugU64 self.key_object_metadata
  let dyn11 := Dyn.mk _ core.fmt.DebugBool self.object_metadata_empty
  let dyn12 := Dyn.mk _ core.fmt.DebugU64 self.key_caller_object_id
  let dyn13 := Dyn.mk _ core.fmt.DebugU64 self.caller_object_id
  let dyn14 := Dyn.mk _ core.fmt.DebugU64 self.key_external_references
  let dyn15 := Dyn.mk _ core.fmt.DebugBool self.external_references_empty
  let dyn16 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.trailing_data
  let values :=
    Array.to_slice
      (Array.make 17#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15, dyn16
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 17#usize [
        toStr "root_map_len", toStr "key_object_id", toStr "object_id", toStr
        "key_chunk_size", toStr "chunk_size", toStr "key_file_entries", toStr
        "file_entries_len", toStr "file", toStr "key_schema_version", toStr
        "schema_version", toStr "key_object_metadata", toStr
        "object_metadata_empty", toStr "key_caller_object_id", toStr
        "caller_object_id", toStr "key_external_references", toStr
        "external_references_empty", toStr "trailing_data"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "ManifestWireCore") s
    values

/-- Trait implementation: [rao_manifest_verif::{impl core::fmt::Debug for rao_manifest_verif::ManifestWireCore}]
    Source: 'src/lib.rs', lines 104:22-104:27 -/
@[reducible]
def ManifestWireCore.Insts.CoreFmtDebug : core.fmt.Debug ManifestWireCore := {
  fmt := ManifestWireCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_manifest_verif::{impl core::marker::StructuralPartialEq for rao_manifest_verif::ManifestWireCore}]
    Source: 'src/lib.rs', lines 104:29-104:38 -/
@[reducible]
def ManifestWireCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ManifestWireCore := {
}

/-- [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::ManifestWireCore> for rao_manifest_verif::ManifestWireCore}::eq]:
    Source: 'src/lib.rs', lines 104:29-104:38
    Visibility: public -/
def ManifestWireCore.Insts.CoreCmpPartialEqManifestWireCore.eq
  (self : ManifestWireCore) (other : ManifestWireCore) : Result Bool := do
  if self.root_map_len = other.root_map_len
  then
    if self.key_object_id = other.key_object_id
    then
      if self.object_id = other.object_id
      then
        if self.key_chunk_size = other.key_chunk_size
        then
          if self.chunk_size = other.chunk_size
          then
            if self.key_file_entries = other.key_file_entries
            then
              if self.file_entries_len = other.file_entries_len
              then
                if self.key_schema_version = other.key_schema_version
                then
                  if self.schema_version = other.schema_version
                  then
                    if self.key_object_metadata = other.key_object_metadata
                    then
                      if self.object_metadata_empty =
                        other.object_metadata_empty
                      then
                        if self.key_caller_object_id =
                          other.key_caller_object_id
                        then
                          if self.caller_object_id = other.caller_object_id
                          then
                            if self.key_external_references =
                              other.key_external_references
                            then
                              if self.external_references_empty =
                                other.external_references_empty
                              then
                                if self.trailing_data = other.trailing_data
                                then
                                  RegularFileWireCore.Insts.CoreCmpPartialEqRegularFileWireCore.eq
                                    self.file other.file
                                else ok false
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::PartialEq<rao_manifest_verif::ManifestWireCore> for rao_manifest_verif::ManifestWireCore}]
    Source: 'src/lib.rs', lines 104:29-104:38 -/
@[reducible]
def ManifestWireCore.Insts.CoreCmpPartialEqManifestWireCore :
  core.cmp.PartialEq ManifestWireCore ManifestWireCore := {
  eq := ManifestWireCore.Insts.CoreCmpPartialEqManifestWireCore.eq
}

/-- [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::ManifestWireCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 104:40-104:42
    Visibility: public -/
def ManifestWireCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ManifestWireCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_manifest_verif::{impl core::cmp::Eq for rao_manifest_verif::ManifestWireCore}]
    Source: 'src/lib.rs', lines 104:40-104:42 -/
@[reducible]
def ManifestWireCore.Insts.CoreCmpEq : core.cmp.Eq ManifestWireCore := {
  partialEqInst := ManifestWireCore.Insts.CoreCmpPartialEqManifestWireCore
  assert_fields_are_eq := ManifestWireCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_manifest_verif::checked_add]:
    Source: 'src/lib.rs', lines 125:0-130:1
    Visibility: public -/
def checked_add
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 RaoManifestError)
  := do
  let o ← lift (U64.checked_add a b)
  match o with
  | none => ok (core.result.Result.Err RaoManifestError.InvalidManifestField)
  | some sum => ok (core.result.Result.Ok sum)

/-- [rao_manifest_verif::validate_chunk_size]:
    Source: 'src/lib.rs', lines 132:0-137:1
    Visibility: public -/
def validate_chunk_size
  (chunk_size : Std.U64) :
  Result (core.result.Result Unit RaoManifestError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err RaoManifestError.InvalidChunkSize)
  else
    let i ← chunk_size % CHUNK_SIZE_GRANULARITY
    if i != 0#u64
    then ok (core.result.Result.Err RaoManifestError.InvalidChunkSize)
    else ok (core.result.Result.Ok ())

/-- [rao_manifest_verif::chunk_count_core]:
    Source: 'src/lib.rs', lines 139:0-146:1
    Visibility: public -/
def chunk_count_core
  (size_bytes : Std.U64) (chunk_size : Std.U64) :
  Result (core.result.Result Std.U64 RaoManifestError)
  := do
  let r ← validate_chunk_size chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if size_bytes = 0#u64
    then ok (core.result.Result.Ok 0#u64)
    else
      let i ← size_bytes - 1#u64
      let chunks_minus_one ← i / chunk_size
      checked_add chunks_minus_one 1#u64
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame RaoManifestError) residual

/-- [rao_manifest_verif::validate_regular_file_core]:
    Source: 'src/lib.rs', lines 148:0-168:1
    Visibility: public -/
def validate_regular_file_core
  (file : RegularFileCore) (chunk_size : Std.U64) :
  Result (core.result.Result Unit RaoManifestError)
  := do
  let r ← validate_chunk_size chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if file.path_id = 0#u64
    then ok (core.result.Result.Err RaoManifestError.InvalidManifestField)
    else
      if file.file_id = 0#u64
      then ok (core.result.Result.Err RaoManifestError.InvalidManifestField)
      else
        if file.executable_tag > EXECUTABLE_TRUE
        then ok (core.result.Result.Err RaoManifestError.InvalidManifestField)
        else
          let r1 ← chunk_count_core file.size_bytes chunk_size
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            if file.size_bytes = 0#u64
            then
              if file.first_chunk_lba_present
              then
                ok (core.result.Result.Err
                  RaoManifestError.InvalidManifestField)
              else
                if file.first_chunk_lba != 0#u64
                then
                  ok (core.result.Result.Err
                    RaoManifestError.InvalidManifestField)
                else ok (core.result.Result.Ok ())
            else
              if file.first_chunk_lba_present
              then ok (core.result.Result.Ok ())
              else
                ok (core.result.Result.Err
                  RaoManifestError.InvalidManifestField)
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Unit (core.convert.FromSame RaoManifestError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoManifestError) residual

/-- [rao_manifest_verif::validate_manifest_core]:
    Source: 'src/lib.rs', lines 170:0-177:1
    Visibility: public -/
def validate_manifest_core
  (manifest : ManifestCore) :
  Result (core.result.Result Unit RaoManifestError)
  := do
  let r ← validate_chunk_size manifest.chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if manifest.object_id = 0#u64
    then ok (core.result.Result.Err RaoManifestError.InvalidManifestField)
    else
      let r1 ← validate_regular_file_core manifest.file manifest.chunk_size
      let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        ok (core.result.Result.Ok ())
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame RaoManifestError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoManifestError) residual

/-- [rao_manifest_verif::encode_regular_file_core]:
    Source: 'src/lib.rs', lines 179:0-206:1
    Visibility: public -/
def encode_regular_file_core
  (file : RegularFileCore) (chunk_size : Std.U64) :
  Result (core.result.Result RegularFileWireCore RaoManifestError)
  := do
  let r ← validate_regular_file_core file chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let r1 ← chunk_count_core file.size_bytes chunk_size
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val =>
      ok (core.result.Result.Ok
        {
          map_len := FILE_ENTRY_REGULAR_MAP_LEN,
          key_path := FILE_KEY_PATH,
          path_id := file.path_id,
          key_file_id := FILE_KEY_FILE_ID,
          file_id := file.file_id,
          key_executable := FILE_KEY_EXECUTABLE,
          executable_tag := file.executable_tag,
          key_size_bytes := FILE_KEY_SIZE_BYTES,
          size_bytes := file.size_bytes,
          key_chunk_count := FILE_KEY_CHUNK_COUNT,
          chunk_count := val,
          key_file_sha256 := FILE_KEY_FILE_SHA256,
          file_sha256_len := DIGEST_BYTE_LEN,
          file_sha256 := file.file_sha256,
          key_first_chunk_lba := FILE_KEY_FIRST_CHUNK_LBA,
          first_chunk_lba_is_null := (¬ file.first_chunk_lba_present),
          first_chunk_lba := file.first_chunk_lba,
          key_metadata_preservation_data := FILE_KEY_METADATA_PRESERVATION_DATA,
          metadata_preservation_data_empty := true
        })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        RegularFileWireCore (core.convert.FromSame RaoManifestError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      RegularFileWireCore (core.convert.FromSame RaoManifestError) residual

/-- [rao_manifest_verif::encode_manifest_core]:
    Source: 'src/lib.rs', lines 208:0-230:1
    Visibility: public -/
def encode_manifest_core
  (manifest : ManifestCore) :
  Result (core.result.Result ManifestWireCore RaoManifestError)
  := do
  let r ← validate_manifest_core manifest
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let r1 ← encode_regular_file_core manifest.file manifest.chunk_size
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val =>
      ok (core.result.Result.Ok
        {
          root_map_len := ROOT_MAP_LEN,
          key_object_id := ROOT_KEY_OBJECT_ID,
          object_id := manifest.object_id,
          key_chunk_size := ROOT_KEY_CHUNK_SIZE,
          chunk_size := manifest.chunk_size,
          key_file_entries := ROOT_KEY_FILE_ENTRIES,
          file_entries_len := FILE_ENTRIES_LEN_ONE,
          file := val,
          key_schema_version := ROOT_KEY_SCHEMA_VERSION,
          schema_version := SCHEMA_VERSION,
          key_object_metadata := ROOT_KEY_OBJECT_METADATA,
          object_metadata_empty := true,
          key_caller_object_id := ROOT_KEY_CALLER_OBJECT_ID,
          caller_object_id := manifest.caller_object_id,
          key_external_references := ROOT_KEY_EXTERNAL_REFERENCES,
          external_references_empty := true,
          trailing_data := false
        })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        ManifestWireCore (core.convert.FromSame RaoManifestError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      ManifestWireCore (core.convert.FromSame RaoManifestError) residual

/-- [rao_manifest_verif::decode_regular_file_core]:
    Source: 'src/lib.rs', lines 232:0-284:1
    Visibility: public -/
def decode_regular_file_core
  (wire : RegularFileWireCore) (chunk_size : Std.U64) :
  Result (core.result.Result RegularFileCore RaoManifestError)
  := do
  if wire.map_len != FILE_ENTRY_REGULAR_MAP_LEN
  then
    ok (core.result.Result.Err RaoManifestError.MissingRequiredManifestField)
  else
    if wire.key_path != FILE_KEY_PATH
    then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
    else
      if wire.key_file_id != FILE_KEY_FILE_ID
      then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
      else
        if wire.key_executable != FILE_KEY_EXECUTABLE
        then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
        else
          if wire.key_size_bytes != FILE_KEY_SIZE_BYTES
          then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
          else
            if wire.key_chunk_count != FILE_KEY_CHUNK_COUNT
            then
              ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
            else
              if wire.key_file_sha256 != FILE_KEY_FILE_SHA256
              then
                ok (core.result.Result.Err
                  RaoManifestError.InvalidCborEncoding)
              else
                if wire.key_first_chunk_lba != FILE_KEY_FIRST_CHUNK_LBA
                then
                  ok (core.result.Result.Err
                    RaoManifestError.InvalidCborEncoding)
                else
                  if wire.key_metadata_preservation_data !=
                    FILE_KEY_METADATA_PRESERVATION_DATA
                  then
                    ok (core.result.Result.Err
                      RaoManifestError.InvalidCborEncoding)
                  else
                    if wire.file_sha256_len != DIGEST_BYTE_LEN
                    then
                      ok (core.result.Result.Err
                        RaoManifestError.InvalidManifestField)
                    else
                      if wire.metadata_preservation_data_empty
                      then
                        let r ← chunk_count_core wire.size_bytes chunk_size
                        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
                        match cf with
                        | core.ops.control_flow.ControlFlow.Continue val =>
                          if wire.chunk_count != val
                          then
                            ok (core.result.Result.Err
                              RaoManifestError.InvalidManifestField)
                          else
                            if wire.size_bytes = 0#u64
                            then
                              if wire.first_chunk_lba_is_null
                              then
                                let r1 ←
                                  validate_regular_file_core
                                    {
                                      path_id := wire.path_id,
                                      file_id := wire.file_id,
                                      size_bytes := wire.size_bytes,
                                      file_sha256 := wire.file_sha256,
                                      first_chunk_lba_present := (¬ true),
                                      first_chunk_lba := 0#u64,
                                      executable_tag := wire.executable_tag
                                    } chunk_size
                                let cf1 ←
                                  core.result.Result.Insts.CoreOpsTry.branch r1
                                match cf1 with
                                | core.ops.control_flow.ControlFlow.Continue _
                                  =>
                                  ok (core.result.Result.Ok
                                    {
                                      path_id := wire.path_id,
                                      file_id := wire.file_id,
                                      size_bytes := wire.size_bytes,
                                      file_sha256 := wire.file_sha256,
                                      first_chunk_lba_present := (¬ true),
                                      first_chunk_lba := 0#u64,
                                      executable_tag := wire.executable_tag
                                    })
                                | core.ops.control_flow.ControlFlow.Break
                                  residual =>
                                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                    RegularFileCore (core.convert.FromSame
                                    RaoManifestError) residual
                              else
                                ok (core.result.Result.Err
                                  RaoManifestError.InvalidManifestField)
                            else
                              if wire.first_chunk_lba_is_null
                              then
                                ok (core.result.Result.Err
                                  RaoManifestError.InvalidManifestField)
                              else
                                let r1 ←
                                  validate_regular_file_core
                                    {
                                      path_id := wire.path_id,
                                      file_id := wire.file_id,
                                      size_bytes := wire.size_bytes,
                                      file_sha256 := wire.file_sha256,
                                      first_chunk_lba_present := (¬ false),
                                      first_chunk_lba := wire.first_chunk_lba,
                                      executable_tag := wire.executable_tag
                                    } chunk_size
                                let cf1 ←
                                  core.result.Result.Insts.CoreOpsTry.branch r1
                                match cf1 with
                                | core.ops.control_flow.ControlFlow.Continue _
                                  =>
                                  ok (core.result.Result.Ok
                                    {
                                      path_id := wire.path_id,
                                      file_id := wire.file_id,
                                      size_bytes := wire.size_bytes,
                                      file_sha256 := wire.file_sha256,
                                      first_chunk_lba_present := (¬ false),
                                      first_chunk_lba := wire.first_chunk_lba,
                                      executable_tag := wire.executable_tag
                                    })
                                | core.ops.control_flow.ControlFlow.Break
                                  residual =>
                                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                    RegularFileCore (core.convert.FromSame
                                    RaoManifestError) residual
                        | core.ops.control_flow.ControlFlow.Break residual =>
                          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                            RegularFileCore (core.convert.FromSame
                            RaoManifestError) residual
                      else
                        ok (core.result.Result.Err
                          RaoManifestError.InvalidManifestField)

/-- [rao_manifest_verif::decode_manifest_core]:
    Source: 'src/lib.rs', lines 286:0-328:1
    Visibility: public -/
def decode_manifest_core
  (wire : ManifestWireCore) (reader_chunk_size : Std.U64) :
  Result (core.result.Result ManifestCore RaoManifestError)
  := do
  if wire.trailing_data
  then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
  else
    if wire.root_map_len != ROOT_MAP_LEN
    then
      ok (core.result.Result.Err RaoManifestError.MissingRequiredManifestField)
    else
      if wire.key_object_id != ROOT_KEY_OBJECT_ID
      then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
      else
        if wire.key_chunk_size != ROOT_KEY_CHUNK_SIZE
        then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
        else
          if wire.key_file_entries != ROOT_KEY_FILE_ENTRIES
          then ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
          else
            if wire.key_schema_version != ROOT_KEY_SCHEMA_VERSION
            then
              ok (core.result.Result.Err RaoManifestError.InvalidCborEncoding)
            else
              if wire.key_object_metadata != ROOT_KEY_OBJECT_METADATA
              then
                ok (core.result.Result.Err
                  RaoManifestError.InvalidCborEncoding)
              else
                if wire.key_caller_object_id != ROOT_KEY_CALLER_OBJECT_ID
                then
                  ok (core.result.Result.Err
                    RaoManifestError.InvalidCborEncoding)
                else
                  if wire.key_external_references !=
                    ROOT_KEY_EXTERNAL_REFERENCES
                  then
                    ok (core.result.Result.Err
                      RaoManifestError.InvalidCborEncoding)
                  else
                    if wire.schema_version != SCHEMA_VERSION
                    then
                      ok (core.result.Result.Err
                        RaoManifestError.InvalidManifestField)
                    else
                      if wire.chunk_size != reader_chunk_size
                      then
                        ok (core.result.Result.Err
                          RaoManifestError.InvalidManifestField)
                      else
                        if wire.file_entries_len != FILE_ENTRIES_LEN_ONE
                        then
                          ok (core.result.Result.Err
                            RaoManifestError.InvalidManifestField)
                        else
                          if wire.object_metadata_empty
                          then
                            if wire.external_references_empty
                            then
                              let r ←
                                decode_regular_file_core wire.file
                                  reader_chunk_size
                              let cf ←
                                core.result.Result.Insts.CoreOpsTry.branch r
                              match cf with
                              | core.ops.control_flow.ControlFlow.Continue val
                                =>
                                let r1 ←
                                  validate_manifest_core
                                    {
                                      object_id := wire.object_id,
                                      caller_object_id := wire.caller_object_id,
                                      chunk_size := wire.chunk_size,
                                      file := val
                                    }
                                let cf1 ←
                                  core.result.Result.Insts.CoreOpsTry.branch r1
                                match cf1 with
                                | core.ops.control_flow.ControlFlow.Continue _
                                  =>
                                  ok (core.result.Result.Ok
                                    {
                                      object_id := wire.object_id,
                                      caller_object_id := wire.caller_object_id,
                                      chunk_size := wire.chunk_size,
                                      file := val
                                    })
                                | core.ops.control_flow.ControlFlow.Break
                                  residual =>
                                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                    ManifestCore (core.convert.FromSame
                                    RaoManifestError) residual
                              | core.ops.control_flow.ControlFlow.Break
                                residual =>
                                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                  ManifestCore (core.convert.FromSame
                                  RaoManifestError) residual
                            else
                              ok (core.result.Result.Err
                                RaoManifestError.InvalidManifestField)
                          else
                            ok (core.result.Result.Err
                              RaoManifestError.InvalidManifestField)

end RaoManifest
