-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_manifest_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoManifest

/-- [rao_manifest_verif::RaoManifestError]
    Source: 'src/lib.rs', lines 47:0-52:1
    Visibility: public -/
@[discriminant isize]
inductive RaoManifestError where
| InvalidChunkSize : RaoManifestError
| InvalidManifestField : RaoManifestError
| InvalidCborEncoding : RaoManifestError
| MissingRequiredManifestField : RaoManifestError

/-- [rao_manifest_verif::DigestWords]
    Source: 'src/lib.rs', lines 55:0-60:1
    Visibility: public -/
structure DigestWords where
  w0 : Std.U64
  w1 : Std.U64
  w2 : Std.U64
  w3 : Std.U64

/-- [rao_manifest_verif::RegularFileCore]
    Source: 'src/lib.rs', lines 63:0-71:1
    Visibility: public -/
structure RegularFileCore where
  path_id : Std.U64
  file_id : Std.U64
  size_bytes : Std.U64
  file_sha256 : DigestWords
  first_chunk_lba_present : Bool
  first_chunk_lba : Std.U64
  executable_tag : Std.U8

/-- [rao_manifest_verif::ManifestCore]
    Source: 'src/lib.rs', lines 74:0-79:1
    Visibility: public -/
structure ManifestCore where
  object_id : Std.U64
  caller_object_id : Std.U64
  chunk_size : Std.U64
  file : RegularFileCore

/-- [rao_manifest_verif::RegularFileWireCore]
    Source: 'src/lib.rs', lines 82:0-102:1
    Visibility: public -/
structure RegularFileWireCore where
  map_len : Std.U64
  key_path : Std.U64
  path_id : Std.U64
  key_file_id : Std.U64
  file_id : Std.U64
  key_executable : Std.U64
  executable_tag : Std.U8
  key_size_bytes : Std.U64
  size_bytes : Std.U64
  key_chunk_count : Std.U64
  chunk_count : Std.U64
  key_file_sha256 : Std.U64
  file_sha256_len : Std.U64
  file_sha256 : DigestWords
  key_first_chunk_lba : Std.U64
  first_chunk_lba_is_null : Bool
  first_chunk_lba : Std.U64
  key_metadata_preservation_data : Std.U64
  metadata_preservation_data_empty : Bool

/-- [rao_manifest_verif::ManifestWireCore]
    Source: 'src/lib.rs', lines 105:0-123:1
    Visibility: public -/
structure ManifestWireCore where
  root_map_len : Std.U64
  key_object_id : Std.U64
  object_id : Std.U64
  key_chunk_size : Std.U64
  chunk_size : Std.U64
  key_file_entries : Std.U64
  file_entries_len : Std.U64
  file : RegularFileWireCore
  key_schema_version : Std.U64
  schema_version : Std.U64
  key_object_metadata : Std.U64
  object_metadata_empty : Bool
  key_caller_object_id : Std.U64
  caller_object_id : Std.U64
  key_external_references : Std.U64
  external_references_empty : Bool
  trailing_data : Bool

end RaoManifest
