-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_manifest_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoManifest

/-- [rao_manifest_verif::RaoManifestError]
    Source: 'src/lib.rs', lines 92:0-97:1
    Visibility: public -/
@[discriminant isize]
inductive RaoManifestError where
| InvalidChunkSize : RaoManifestError
| InvalidManifestField : RaoManifestError
| InvalidCborEncoding : RaoManifestError
| MissingRequiredManifestField : RaoManifestError

/-- [rao_manifest_verif::DigestWords]
    Source: 'src/lib.rs', lines 100:0-105:1
    Visibility: public -/
structure DigestWords where
  w0 : Std.U64
  w1 : Std.U64
  w2 : Std.U64
  w3 : Std.U64

/-- [rao_manifest_verif::RegularFileCore]
    Source: 'src/lib.rs', lines 108:0-116:1
    Visibility: public -/
structure RegularFileCore where
  path_id : Std.U64
  file_id : Std.U64
  size_bytes : Std.U64
  file_sha256 : DigestWords
  first_chunk_lba_present : Bool
  first_chunk_lba : Std.U64
  executable_tag : Std.U8

/-- [rao_manifest_verif::ManifestCore]
    Source: 'src/lib.rs', lines 119:0-124:1
    Visibility: public -/
structure ManifestCore where
  object_id : Std.U64
  caller_object_id : Std.U64
  chunk_size : Std.U64
  file : RegularFileCore

/-- [rao_manifest_verif::RegularFileWireCore]
    Source: 'src/lib.rs', lines 127:0-147:1
    Visibility: public -/
structure RegularFileWireCore where
  map_len : Std.U64
  key_path : Std.U64
  path_id : Std.U64
  key_file_id : Std.U64
  file_id : Std.U64
  key_executable : Std.U64
  executable_tag : Std.U8
  key_size_bytes : Std.U64
  size_bytes : Std.U64
  key_chunk_count : Std.U64
  chunk_count : Std.U64
  key_file_sha256 : Std.U64
  file_sha256_len : Std.U64
  file_sha256 : DigestWords
  key_first_chunk_lba : Std.U64
  first_chunk_lba_is_null : Bool
  first_chunk_lba : Std.U64
  key_metadata_preservation_data : Std.U64
  metadata_preservation_data_empty : Bool

/-- [rao_manifest_verif::ManifestWireCore]
    Source: 'src/lib.rs', lines 150:0-168:1
    Visibility: public -/
structure ManifestWireCore where
  root_map_len : Std.U64
  key_object_id : Std.U64
  object_id : Std.U64
  key_chunk_size : Std.U64
  chunk_size : Std.U64
  key_file_entries : Std.U64
  file_entries_len : Std.U64
  file : RegularFileWireCore
  key_schema_version : Std.U64
  schema_version : Std.U64
  key_object_metadata : Std.U64
  object_metadata_empty : Bool
  key_caller_object_id : Std.U64
  caller_object_id : Std.U64
  key_external_references : Std.U64
  external_references_empty : Bool
  trailing_data : Bool

/-- [rao_manifest_verif::RichRegularFileCore]
    Source: 'src/lib.rs', lines 171:0-183:1
    Visibility: public -/
structure RichRegularFileCore where
  path_id : Std.U64
  file_id : Std.U64
  size_bytes : Std.U64
  file_sha256 : DigestWords
  first_chunk_lba_present : Bool
  first_chunk_lba : Std.U64
  executable_tag : Std.U8
  xattr_present : Bool
  xattr_name_id : Std.U64
  xattr_value_len : Std.U64
  xattr_value_id : Std.U64

/-- [rao_manifest_verif::HardlinkEntryCore]
    Source: 'src/lib.rs', lines 186:0-191:1
    Visibility: public -/
structure HardlinkEntryCore where
  path_id : Std.U64
  file_id : Std.U64
  link_target_path_id : Std.U64
  executable_tag : Std.U8

/-- [rao_manifest_verif::SymlinkEntryCore]
    Source: 'src/lib.rs', lines 194:0-199:1
    Visibility: public -/
structure SymlinkEntryCore where
  path_id : Std.U64
  file_id : Std.U64
  link_target_id : Std.U64
  executable_tag : Std.U8

/-- [rao_manifest_verif::DirectoryEntryCore]
    Source: 'src/lib.rs', lines 202:0-206:1
    Visibility: public -/
structure DirectoryEntryCore where
  path_id : Std.U64
  file_id : Std.U64
  executable_tag : Std.U8

/-- [rao_manifest_verif::ManifestEntriesCore]
    Source: 'src/lib.rs', lines 209:0-218:1
    Visibility: public -/
structure ManifestEntriesCore where
  object_id : Std.U64
  caller_object_id : Std.U64
  chunk_size : Std.U64
  nonempty_regular : RichRegularFileCore
  empty_regular : RichRegularFileCore
  hardlink : HardlinkEntryCore
  symlink : SymlinkEntryCore
  directory : DirectoryEntryCore

/-- [rao_manifest_verif::RichRegularFileWireCore]
    Source: 'src/lib.rs', lines 221:0-246:1
    Visibility: public -/
structure RichRegularFileWireCore where
  map_len : Std.U64
  key_path : Std.U64
  path_id : Std.U64
  key_file_id : Std.U64
  file_id : Std.U64
  key_executable : Std.U64
  executable_tag : Std.U8
  key_size_bytes : Std.U64
  size_bytes : Std.U64
  key_chunk_count : Std.U64
  chunk_count : Std.U64
  key_file_sha256 : Std.U64
  file_sha256_len : Std.U64
  file_sha256 : DigestWords
  key_first_chunk_lba : Std.U64
  first_chunk_lba_is_null : Bool
  first_chunk_lba : Std.U64
  key_metadata_preservation_data : Std.U64
  metadata_preservation_data_map_len : Std.U64
  metadata_key_xattrs : Std.U64
  xattrs_map_len : Std.U64
  xattr_name_id : Std.U64
  xattr_value_len : Std.U64
  xattr_value_id : Std.U64

/-- [rao_manifest_verif::LinkEntryWireCore]
    Source: 'src/lib.rs', lines 249:0-270:1
    Visibility: public -/
structure LinkEntryWireCore where
  map_len : Std.U64
  key_path : Std.U64
  path_id : Std.U64
  key_file_id : Std.U64
  file_id : Std.U64
  key_entry_type : Std.U64
  entry_type : Std.U8
  key_executable : Std.U64
  executable_tag : Std.U8
  key_size_bytes : Std.U64
  size_bytes : Std.U64
  key_chunk_count : Std.U64
  chunk_count : Std.U64
  key_link_target : Std.U64
  link_target_id : Std.U64
  key_first_chunk_lba : Std.U64
  first_chunk_lba_is_null : Bool
  key_metadata_preservation_data : Std.U64
  metadata_preservation_data_empty : Bool
  file_sha256_present : Bool

/-- [rao_manifest_verif::DirectoryEntryWireCore]
    Source: 'src/lib.rs', lines 273:0-293:1
    Visibility: public -/
structure DirectoryEntryWireCore where
  map_len : Std.U64
  key_path : Std.U64
  path_id : Std.U64
  key_file_id : Std.U64
  file_id : Std.U64
  key_entry_type : Std.U64
  entry_type : Std.U8
  key_executable : Std.U64
  executable_tag : Std.U8
  key_size_bytes : Std.U64
  size_bytes : Std.U64
  key_chunk_count : Std.U64
  chunk_count : Std.U64
  key_first_chunk_lba : Std.U64
  first_chunk_lba_is_null : Bool
  key_metadata_preservation_data : Std.U64
  metadata_preservation_data_empty : Bool
  file_sha256_present : Bool
  link_target_present : Bool

/-- [rao_manifest_verif::ManifestEntriesWireCore]
    Source: 'src/lib.rs', lines 296:0-318:1
    Visibility: public -/
structure ManifestEntriesWireCore where
  root_map_len : Std.U64
  key_object_id : Std.U64
  object_id : Std.U64
  key_chunk_size : Std.U64
  chunk_size : Std.U64
  key_file_entries : Std.U64
  file_entries_len : Std.U64
  nonempty_regular : RichRegularFileWireCore
  empty_regular : RichRegularFileWireCore
  hardlink : LinkEntryWireCore
  symlink : LinkEntryWireCore
  directory : DirectoryEntryWireCore
  key_schema_version : Std.U64
  schema_version : Std.U64
  key_object_metadata : Std.U64
  object_metadata_empty : Bool
  key_caller_object_id : Std.U64
  caller_object_id : Std.U64
  key_external_references : Std.U64
  external_references_empty : Bool
  trailing_data : Bool

/-- [rao_manifest_verif::PlannerFoldStateCore]
    Source: 'src/lib.rs', lines 321:0-324:1
    Visibility: public -/
structure PlannerFoldStateCore where
  accepted_count : Std.U64
  regular_seen_count : Std.U64

/-- [rao_manifest_verif::PlannerEntryCore]
    Source: 'src/lib.rs', lines 327:0-336:1
    Visibility: public -/
structure PlannerEntryCore where
  entry_type : Std.U8
  path_id : Std.U64
  file_id : Std.U64
  link_target_path_id : Std.U64
  local_entry_valid : Bool
  path_seen_before : Bool
  file_id_seen_before : Bool
  hardlink_target_seen_regular_before : Bool

end RaoManifest
