-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pool_selection_verif]: function definitions
import Aeneas
import PoolSelection.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace PoolSelection

/-- [pool_selection_verif::{impl core::clone::Clone for pool_selection_verif::TapeFitState}::clone]:
    Source: 'src/lib.rs', lines 14:9-14:14
    Visibility: public -/
def TapeFitState.Insts.CoreCloneClone.clone
  (self : TapeFitState) : Result TapeFitState := do
  ok self

/-- Trait implementation: [pool_selection_verif::{impl core::clone::Clone for pool_selection_verif::TapeFitState}]
    Source: 'src/lib.rs', lines 14:9-14:14 -/
@[reducible]
def TapeFitState.Insts.CoreCloneClone : core.clone.Clone TapeFitState := {
  clone := TapeFitState.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pool_selection_verif::{impl core::marker::Copy for pool_selection_verif::TapeFitState}]
    Source: 'src/lib.rs', lines 14:16-14:20 -/
@[reducible]
def TapeFitState.Insts.CoreMarkerCopy : core.marker.Copy TapeFitState := {
  cloneInst := TapeFitState.Insts.CoreCloneClone
}

/-- [pool_selection_verif::loaded_key]:
    Source: 'src/lib.rs', lines 25:0-31:1
    Visibility: public -/
def loaded_key (candidate : TapeFitState) : Result Std.U8 := do
  if candidate.already_loaded
  then ok 0#u8
  else ok 1#u8

/-- [pool_selection_verif::fits]:
    Source: 'src/lib.rs', lines 33:0-38:1
    Visibility: public -/
def fits
  (candidate : TapeFitState) (projected_footprint : Std.U64) :
  Result Bool
  := do
  let o ← lift (U64.checked_sub candidate.usable_bytes candidate.used_bytes)
  match o with
  | none => ok false
  | some remaining => ok (remaining >= projected_footprint)

/-- [pool_selection_verif::completes_tape]:
    Source: 'src/lib.rs', lines 40:0-42:1
    Visibility: public -/
def completes_tape
  (candidate : TapeFitState) (projected_footprint : Std.U64) :
  Result Bool
  := do
  let i ←
    lift (core.num.U64.saturating_add candidate.used_bytes projected_footprint)
  ok (i >= candidate.low_bytes)

/-- [pool_selection_verif::leftover_after_write]:
    Source: 'src/lib.rs', lines 44:0-49:1
    Visibility: public -/
def leftover_after_write
  (candidate : TapeFitState) (projected_footprint : Std.U64) :
  Result Std.U64
  := do
  let i ←
    lift (core.num.U64.saturating_sub candidate.usable_bytes
      candidate.used_bytes)
  ok (core.num.U64.saturating_sub i projected_footprint)

/-- [pool_selection_verif::complete_or_fill_completing_precedes_or_ties]:
    Source: 'src/lib.rs', lines 51:0-82:1
    Visibility: public -/
def complete_or_fill_completing_precedes_or_ties
  (left : TapeFitState) (right : TapeFitState) (projected_footprint : Std.U64)
  :
  Result Bool
  := do
  let left_leftover ← leftover_after_write left projected_footprint
  let right_leftover ← leftover_after_write right projected_footprint
  if left_leftover < right_leftover
  then ok true
  else
    if right_leftover < left_leftover
    then ok false
    else
      let left_loaded_key ← loaded_key left
      let right_loaded_key ← loaded_key right
      if left_loaded_key < right_loaded_key
      then ok true
      else
        if right_loaded_key < left_loaded_key
        then ok false
        else
          if left.barcode_order < right.barcode_order
          then ok true
          else
            if right.barcode_order < left.barcode_order
            then ok false
            else ok (left.tape_uuid <= right.tape_uuid)

/-- [pool_selection_verif::complete_or_fill_fill_precedes_or_ties]:
    Source: 'src/lib.rs', lines 84:0-102:1
    Visibility: public -/
def complete_or_fill_fill_precedes_or_ties
  (left : TapeFitState) (right : TapeFitState) : Result Bool := do
  let left_loaded_key ← loaded_key left
  let right_loaded_key ← loaded_key right
  if left_loaded_key < right_loaded_key
  then ok true
  else
    if right_loaded_key < left_loaded_key
    then ok false
    else
      if left.barcode_order < right.barcode_order
      then ok true
      else
        if right.barcode_order < left.barcode_order
        then ok false
        else ok (left.tape_uuid <= right.tape_uuid)

/-- [pool_selection_verif::fill_oldest_precedes_or_ties]:
    Source: 'src/lib.rs', lines 104:0-122:1
    Visibility: public -/
def fill_oldest_precedes_or_ties
  (left : TapeFitState) (right : TapeFitState) : Result Bool := do
  if left.barcode_order < right.barcode_order
  then ok true
  else
    if right.barcode_order < left.barcode_order
    then ok false
    else
      let left_loaded_key ← loaded_key left
      let right_loaded_key ← loaded_key right
      if left_loaded_key < right_loaded_key
      then ok true
      else
        if right_loaded_key < left_loaded_key
        then ok false
        else ok (left.tape_uuid <= right.tape_uuid)

end PoolSelection
