-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pool_selection_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace PoolSelection

/-- [pool_selection_verif::TapeFitState]
    Source: 'src/lib.rs', lines 16:0-23:1
    Visibility: public -/
structure TapeFitState where
  tape_uuid : Std.U64
  barcode_order : Std.U64
  already_loaded : Bool
  used_bytes : Std.U64
  usable_bytes : Std.U64
  low_bytes : Std.U64

end PoolSelection
