-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pool_selection_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace PoolSelection

/-- [pool_selection_verif::TapeFitState]
    Source: 'src/lib.rs', lines 18:0-25:1
    Visibility: public -/
structure TapeFitState where
  tape_uuid : Std.U64
  barcode_order : Std.U64
  already_loaded : Bool
  used_bytes : Std.U64
  usable_bytes : Std.U64
  low_bytes : Std.U64

/-- [pool_selection_verif::AdmissionDisposition]
    Source: 'src/lib.rs', lines 29:0-34:1
    Visibility: public -/
@[discriminant isize]
inductive AdmissionDisposition where
| AdmitRemainOpen : AdmissionDisposition
| AdmitThenFinalize : AdmissionDisposition
| FinalizePrefixAndRetry : AdmissionDisposition
| RejectInvalidCapacityPolicy : AdmissionDisposition

/-- [pool_selection_verif::CapacityAdmissionInput]
    Source: 'src/lib.rs', lines 38:0-45:1
    Visibility: public -/
structure CapacityAdmissionInput where
  current_used_blocks : Std.U64
  object_commit_charge_blocks : Std.U64
  close_bound_blocks : Std.U64
  capacity_blocks : Std.U64
  low_watermark_blocks : Std.U64
  high_watermark_blocks : Std.U64

end PoolSelection
