-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_archive_verif]: function definitions
import Aeneas
import RaoArchive.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoArchive

/-- [rao_archive_verif::RAO_HEADER_LEN_U16]
    Source: 'src/lib.rs', lines 18:0-18:40
    Visibility: public -/
@[global_simps, irreducible] def RAO_HEADER_LEN_U16 : Std.U16 := 128#u16

/-- [rao_archive_verif::FORMAT_VERSION]
    Source: 'src/lib.rs', lines 19:0-19:33
    Visibility: public -/
@[global_simps, irreducible] def FORMAT_VERSION : Std.U8 := 1#u8

/-- [rao_archive_verif::SUITE_ID_HKDF_SHA256_CHACHA20POLY1305]
    Source: 'src/lib.rs', lines 20:0-20:59
    Visibility: public -/
@[global_simps, irreducible]
def SUITE_ID_HKDF_SHA256_CHACHA20POLY1305 : Std.U8 := 1#u8

/-- [rao_archive_verif::CHUNK_SIZE_GRANULARITY]
    Source: 'src/lib.rs', lines 21:0-21:44
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_SIZE_GRANULARITY : Std.U64 := 512#u64

/-- [rao_archive_verif::RAO_METADATA_FRAME_MIN_LEN]
    Source: 'src/lib.rs', lines 22:0-22:47
    Visibility: public -/
@[global_simps, irreducible] def RAO_METADATA_FRAME_MIN_LEN : Std.U64 := 17#u64

/-- [rao_archive_verif::RAO_MAX_METADATA_FRAME_LEN]
    Source: 'src/lib.rs', lines 23:0-23:55
    Visibility: public -/
@[global_simps, irreducible]
def RAO_MAX_METADATA_FRAME_LEN : Std.U64 := 16777216#u64

/-- [rao_archive_verif::METADATA_VERSION]
    Source: 'src/lib.rs', lines 25:0-25:36
    Visibility: public -/
@[global_simps, irreducible] def METADATA_VERSION : Std.U64 := 1#u64

/-- [rao_archive_verif::METADATA_REQUIRED_MAP_LEN]
    Source: 'src/lib.rs', lines 26:0-26:45
    Visibility: public -/
@[global_simps, irreducible] def METADATA_REQUIRED_MAP_LEN : Std.U64 := 4#u64

/-- [rao_archive_verif::DIGEST_BYTE_LEN]
    Source: 'src/lib.rs', lines 27:0-27:36
    Visibility: public -/
@[global_simps, irreducible] def DIGEST_BYTE_LEN : Std.U64 := 32#u64

/-- [rao_archive_verif::CHACHA20POLY1305_TAG_LEN]
    Source: 'src/lib.rs', lines 28:0-28:45
    Visibility: public -/
@[global_simps, irreducible] def CHACHA20POLY1305_TAG_LEN : Std.U64 := 16#u64

/-- [rao_archive_verif::MANIFEST_ROOT_MAP_LEN]
    Source: 'src/lib.rs', lines 30:0-30:41
    Visibility: public -/
@[global_simps, irreducible] def MANIFEST_ROOT_MAP_LEN : Std.U64 := 7#u64

/-- [rao_archive_verif::MANIFEST_FILE_ENTRIES_LEN]
    Source: 'src/lib.rs', lines 31:0-31:45
    Visibility: public -/
@[global_simps, irreducible] def MANIFEST_FILE_ENTRIES_LEN : Std.U64 := 5#u64

/-- [rao_archive_verif::MANIFEST_SCHEMA_VERSION]
    Source: 'src/lib.rs', lines 32:0-32:43
    Visibility: public -/
@[global_simps, irreducible] def MANIFEST_SCHEMA_VERSION : Std.U64 := 1#u64

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::RaoArchiveError}::clone]:
    Source: 'src/lib.rs', lines 34:9-34:14
    Visibility: public -/
def RaoArchiveError.Insts.CoreCloneClone.clone
  (self : RaoArchiveError) : Result RaoArchiveError := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::RaoArchiveError}]
    Source: 'src/lib.rs', lines 34:9-34:14 -/
@[reducible]
def RaoArchiveError.Insts.CoreCloneClone : core.clone.Clone RaoArchiveError
  := {
  clone := RaoArchiveError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::RaoArchiveError}]
    Source: 'src/lib.rs', lines 34:16-34:20 -/
@[reducible]
def RaoArchiveError.Insts.CoreMarkerCopy : core.marker.Copy RaoArchiveError
  := {
  cloneInst := RaoArchiveError.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::RaoArchiveError}::fmt]:
    Source: 'src/lib.rs', lines 34:22-34:27
    Visibility: public -/
def RaoArchiveError.Insts.CoreFmtDebug.fmt
  (self : RaoArchiveError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | RaoArchiveError.InvalidHeaderField =>
    core.fmt.Formatter.write_str f (toStr "InvalidHeaderField")
  | RaoArchiveError.InvalidMetadataField =>
    core.fmt.Formatter.write_str f (toStr "InvalidMetadataField")
  | RaoArchiveError.InvalidManifestField =>
    core.fmt.Formatter.write_str f (toStr "InvalidManifestField")
  | RaoArchiveError.InvalidArchiveField =>
    core.fmt.Formatter.write_str f (toStr "InvalidArchiveField")
  | RaoArchiveError.InvalidWireShape =>
    core.fmt.Formatter.write_str f (toStr "InvalidWireShape")

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::RaoArchiveError}]
    Source: 'src/lib.rs', lines 34:22-34:27 -/
@[reducible]
def RaoArchiveError.Insts.CoreFmtDebug : core.fmt.Debug RaoArchiveError := {
  fmt := RaoArchiveError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::RaoArchiveError}]
    Source: 'src/lib.rs', lines 34:29-34:38 -/
@[reducible]
def RaoArchiveError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RaoArchiveError := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::RaoArchiveError> for rao_archive_verif::RaoArchiveError}::eq]:
    Source: 'src/lib.rs', lines 34:29-34:38
    Visibility: public -/
def RaoArchiveError.Insts.CoreCmpPartialEqRaoArchiveError.eq
  (self : RaoArchiveError) (other : RaoArchiveError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::RaoArchiveError> for rao_archive_verif::RaoArchiveError}]
    Source: 'src/lib.rs', lines 34:29-34:38 -/
@[reducible]
def RaoArchiveError.Insts.CoreCmpPartialEqRaoArchiveError : core.cmp.PartialEq
  RaoArchiveError RaoArchiveError := {
  eq := RaoArchiveError.Insts.CoreCmpPartialEqRaoArchiveError.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::RaoArchiveError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 34:40-34:42
    Visibility: public -/
def RaoArchiveError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RaoArchiveError) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::RaoArchiveError}]
    Source: 'src/lib.rs', lines 34:40-34:42 -/
@[reducible]
def RaoArchiveError.Insts.CoreCmpEq : core.cmp.Eq RaoArchiveError := {
  partialEqInst := RaoArchiveError.Insts.CoreCmpPartialEqRaoArchiveError
  assert_fields_are_eq := RaoArchiveError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::DigestWords}::clone]:
    Source: 'src/lib.rs', lines 43:9-43:14
    Visibility: public -/
def DigestWords.Insts.CoreCloneClone.clone
  (self : DigestWords) : Result DigestWords := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::DigestWords}]
    Source: 'src/lib.rs', lines 43:9-43:14 -/
@[reducible]
def DigestWords.Insts.CoreCloneClone : core.clone.Clone DigestWords := {
  clone := DigestWords.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::DigestWords}]
    Source: 'src/lib.rs', lines 43:16-43:20 -/
@[reducible]
def DigestWords.Insts.CoreMarkerCopy : core.marker.Copy DigestWords := {
  cloneInst := DigestWords.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::DigestWords}::fmt]:
    Source: 'src/lib.rs', lines 43:22-43:27
    Visibility: public -/
def DigestWords.Insts.CoreFmtDebug.fmt
  (self : DigestWords) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.w0
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.w1
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.w2
  let dyn3 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.w3
  core.fmt.Formatter.debug_struct_field4_finish f (toStr "DigestWords") (toStr
    "w0") dyn (toStr "w1") dyn1 (toStr "w2") dyn2 (toStr "w3") dyn3

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::DigestWords}]
    Source: 'src/lib.rs', lines 43:22-43:27 -/
@[reducible]
def DigestWords.Insts.CoreFmtDebug : core.fmt.Debug DigestWords := {
  fmt := DigestWords.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::DigestWords}]
    Source: 'src/lib.rs', lines 43:29-43:38 -/
@[reducible]
def DigestWords.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq DigestWords := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::DigestWords> for rao_archive_verif::DigestWords}::eq]:
    Source: 'src/lib.rs', lines 43:29-43:38
    Visibility: public -/
def DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
  (self : DigestWords) (other : DigestWords) : Result Bool := do
  if self.w0 = other.w0
  then
    if self.w1 = other.w1
    then if self.w2 = other.w2
         then ok (self.w3 = other.w3)
         else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::DigestWords> for rao_archive_verif::DigestWords}]
    Source: 'src/lib.rs', lines 43:29-43:38 -/
@[reducible]
def DigestWords.Insts.CoreCmpPartialEqDigestWords : core.cmp.PartialEq
  DigestWords DigestWords := {
  eq := DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::DigestWords}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 43:40-43:42
    Visibility: public -/
def DigestWords.Insts.CoreCmpEq.assert_fields_are_eq
  (self : DigestWords) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::DigestWords}]
    Source: 'src/lib.rs', lines 43:40-43:42 -/
@[reducible]
def DigestWords.Insts.CoreCmpEq : core.cmp.Eq DigestWords := {
  partialEqInst := DigestWords.Insts.CoreCmpPartialEqDigestWords
  assert_fields_are_eq := DigestWords.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::HeaderCore}::clone]:
    Source: 'src/lib.rs', lines 51:9-51:14
    Visibility: public -/
def HeaderCore.Insts.CoreCloneClone.clone
  (self : HeaderCore) : Result HeaderCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 51:9-51:14 -/
@[reducible]
def HeaderCore.Insts.CoreCloneClone : core.clone.Clone HeaderCore := {
  clone := HeaderCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 51:16-51:20 -/
@[reducible]
def HeaderCore.Insts.CoreMarkerCopy : core.marker.Copy HeaderCore := {
  cloneInst := HeaderCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::HeaderCore}::fmt]:
    Source: 'src/lib.rs', lines 51:22-51:27
    Visibility: public -/
def HeaderCore.Insts.CoreFmtDebug.fmt
  (self : HeaderCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.object_id
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.chunk_size
  let dyn2 := Dyn.mk _ core.fmt.DebugBool self.key_id_nonzero
  let dyn3 := Dyn.mk _ core.fmt.DebugBool self.hkdf_salt_nonzero
  let dyn4 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.metadata_frame_len
  core.fmt.Formatter.debug_struct_field5_finish f (toStr "HeaderCore") (toStr
    "object_id") dyn (toStr "chunk_size") dyn1 (toStr "key_id_nonzero") dyn2
    (toStr "hkdf_salt_nonzero") dyn3 (toStr "metadata_frame_len") dyn4

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 51:22-51:27 -/
@[reducible]
def HeaderCore.Insts.CoreFmtDebug : core.fmt.Debug HeaderCore := {
  fmt := HeaderCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 51:29-51:38 -/
@[reducible]
def HeaderCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq HeaderCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::HeaderCore> for rao_archive_verif::HeaderCore}::eq]:
    Source: 'src/lib.rs', lines 51:29-51:38
    Visibility: public -/
def HeaderCore.Insts.CoreCmpPartialEqHeaderCore.eq
  (self : HeaderCore) (other : HeaderCore) : Result Bool := do
  if self.object_id = other.object_id
  then
    if self.chunk_size = other.chunk_size
    then
      if self.key_id_nonzero = other.key_id_nonzero
      then
        if self.hkdf_salt_nonzero = other.hkdf_salt_nonzero
        then ok (self.metadata_frame_len = other.metadata_frame_len)
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::HeaderCore> for rao_archive_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 51:29-51:38 -/
@[reducible]
def HeaderCore.Insts.CoreCmpPartialEqHeaderCore : core.cmp.PartialEq HeaderCore
  HeaderCore := {
  eq := HeaderCore.Insts.CoreCmpPartialEqHeaderCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::HeaderCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 51:40-51:42
    Visibility: public -/
def HeaderCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : HeaderCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 51:40-51:42 -/
@[reducible]
def HeaderCore.Insts.CoreCmpEq : core.cmp.Eq HeaderCore := {
  partialEqInst := HeaderCore.Insts.CoreCmpPartialEqHeaderCore
  assert_fields_are_eq := HeaderCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::MetadataCore}::clone]:
    Source: 'src/lib.rs', lines 60:9-60:14
    Visibility: public -/
def MetadataCore.Insts.CoreCloneClone.clone
  (self : MetadataCore) : Result MetadataCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 60:9-60:14 -/
@[reducible]
def MetadataCore.Insts.CoreCloneClone : core.clone.Clone MetadataCore := {
  clone := MetadataCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 60:16-60:20 -/
@[reducible]
def MetadataCore.Insts.CoreMarkerCopy : core.marker.Copy MetadataCore := {
  cloneInst := MetadataCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::MetadataCore}::fmt]:
    Source: 'src/lib.rs', lines 60:22-60:27
    Visibility: public -/
def MetadataCore.Insts.CoreFmtDebug.fmt
  (self : MetadataCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.plaintext_size
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared DigestWords.Insts.CoreFmtDebug) self.digest
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "MetadataCore") (toStr
    "plaintext_size") dyn (toStr "digest") dyn1

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 60:22-60:27 -/
@[reducible]
def MetadataCore.Insts.CoreFmtDebug : core.fmt.Debug MetadataCore := {
  fmt := MetadataCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 60:29-60:38 -/
@[reducible]
def MetadataCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq MetadataCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::MetadataCore> for rao_archive_verif::MetadataCore}::eq]:
    Source: 'src/lib.rs', lines 60:29-60:38
    Visibility: public -/
def MetadataCore.Insts.CoreCmpPartialEqMetadataCore.eq
  (self : MetadataCore) (other : MetadataCore) : Result Bool := do
  if self.plaintext_size = other.plaintext_size
  then
    DigestWords.Insts.CoreCmpPartialEqDigestWords.eq self.digest other.digest
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::MetadataCore> for rao_archive_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 60:29-60:38 -/
@[reducible]
def MetadataCore.Insts.CoreCmpPartialEqMetadataCore : core.cmp.PartialEq
  MetadataCore MetadataCore := {
  eq := MetadataCore.Insts.CoreCmpPartialEqMetadataCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::MetadataCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 60:40-60:42
    Visibility: public -/
def MetadataCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : MetadataCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::MetadataCore}]
    Source: 'src/lib.rs', lines 60:40-60:42 -/
@[reducible]
def MetadataCore.Insts.CoreCmpEq : core.cmp.Eq MetadataCore := {
  partialEqInst := MetadataCore.Insts.CoreCmpPartialEqMetadataCore
  assert_fields_are_eq := MetadataCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ManifestArrayCore}::clone]:
    Source: 'src/lib.rs', lines 66:9-66:14
    Visibility: public -/
def ManifestArrayCore.Insts.CoreCloneClone.clone
  (self : ManifestArrayCore) : Result ManifestArrayCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ManifestArrayCore}]
    Source: 'src/lib.rs', lines 66:9-66:14 -/
@[reducible]
def ManifestArrayCore.Insts.CoreCloneClone : core.clone.Clone ManifestArrayCore
  := {
  clone := ManifestArrayCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::ManifestArrayCore}]
    Source: 'src/lib.rs', lines 66:16-66:20 -/
@[reducible]
def ManifestArrayCore.Insts.CoreMarkerCopy : core.marker.Copy ManifestArrayCore
  := {
  cloneInst := ManifestArrayCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ManifestArrayCore}::fmt]:
    Source: 'src/lib.rs', lines 66:22-66:27
    Visibility: public -/
def ManifestArrayCore.Insts.CoreFmtDebug.fmt
  (self : ManifestArrayCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.object_id
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.caller_object_id
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.chunk_size
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.nonempty_regular_path_id
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.nonempty_regular_file_id
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.nonempty_regular_size_bytes
  let dyn6 :=
    Dyn.mk _ DigestWords.Insts.CoreFmtDebug self.nonempty_regular_sha256
  let dyn7 := Dyn.mk _ core.fmt.DebugU64 self.empty_regular_path_id
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.empty_regular_file_id
  let dyn9 := Dyn.mk _ core.fmt.DebugU64 self.hardlink_path_id
  let dyn10 := Dyn.mk _ core.fmt.DebugU64 self.hardlink_file_id
  let dyn11 := Dyn.mk _ core.fmt.DebugU64 self.hardlink_target_path_id
  let dyn12 := Dyn.mk _ core.fmt.DebugU64 self.symlink_path_id
  let dyn13 := Dyn.mk _ core.fmt.DebugU64 self.symlink_file_id
  let dyn14 := Dyn.mk _ core.fmt.DebugU64 self.symlink_target_id
  let dyn15 := Dyn.mk _ core.fmt.DebugU64 self.directory_path_id
  let dyn16 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.directory_file_id
  let values :=
    Array.to_slice
      (Array.make 17#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15, dyn16
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 17#usize [
        toStr "object_id", toStr "caller_object_id", toStr "chunk_size", toStr
        "nonempty_regular_path_id", toStr "nonempty_regular_file_id", toStr
        "nonempty_regular_size_bytes", toStr "nonempty_regular_sha256", toStr
        "empty_regular_path_id", toStr "empty_regular_file_id", toStr
        "hardlink_path_id", toStr "hardlink_file_id", toStr
        "hardlink_target_path_id", toStr "symlink_path_id", toStr
        "symlink_file_id", toStr "symlink_target_id", toStr
        "directory_path_id", toStr "directory_file_id"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "ManifestArrayCore") s
    values

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ManifestArrayCore}]
    Source: 'src/lib.rs', lines 66:22-66:27 -/
@[reducible]
def ManifestArrayCore.Insts.CoreFmtDebug : core.fmt.Debug ManifestArrayCore
  := {
  fmt := ManifestArrayCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::ManifestArrayCore}]
    Source: 'src/lib.rs', lines 66:29-66:38 -/
@[reducible]
def ManifestArrayCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ManifestArrayCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ManifestArrayCore> for rao_archive_verif::ManifestArrayCore}::eq]:
    Source: 'src/lib.rs', lines 66:29-66:38
    Visibility: public -/
def ManifestArrayCore.Insts.CoreCmpPartialEqManifestArrayCore.eq
  (self : ManifestArrayCore) (other : ManifestArrayCore) : Result Bool := do
  if self.object_id = other.object_id
  then
    if self.caller_object_id = other.caller_object_id
    then
      if self.chunk_size = other.chunk_size
      then
        if self.nonempty_regular_path_id = other.nonempty_regular_path_id
        then
          if self.nonempty_regular_file_id = other.nonempty_regular_file_id
          then
            if self.nonempty_regular_size_bytes =
              other.nonempty_regular_size_bytes
            then
              if self.empty_regular_path_id = other.empty_regular_path_id
              then
                if self.empty_regular_file_id = other.empty_regular_file_id
                then
                  if self.hardlink_path_id = other.hardlink_path_id
                  then
                    if self.hardlink_file_id = other.hardlink_file_id
                    then
                      if self.hardlink_target_path_id =
                        other.hardlink_target_path_id
                      then
                        if self.symlink_path_id = other.symlink_path_id
                        then
                          if self.symlink_file_id = other.symlink_file_id
                          then
                            if self.symlink_target_id = other.symlink_target_id
                            then
                              if self.directory_path_id =
                                other.directory_path_id
                              then
                                if self.directory_file_id =
                                  other.directory_file_id
                                then
                                  DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
                                    self.nonempty_regular_sha256
                                    other.nonempty_regular_sha256
                                else ok false
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ManifestArrayCore> for rao_archive_verif::ManifestArrayCore}]
    Source: 'src/lib.rs', lines 66:29-66:38 -/
@[reducible]
def ManifestArrayCore.Insts.CoreCmpPartialEqManifestArrayCore :
  core.cmp.PartialEq ManifestArrayCore ManifestArrayCore := {
  eq := ManifestArrayCore.Insts.CoreCmpPartialEqManifestArrayCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ManifestArrayCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 66:40-66:42
    Visibility: public -/
def ManifestArrayCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ManifestArrayCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ManifestArrayCore}]
    Source: 'src/lib.rs', lines 66:40-66:42 -/
@[reducible]
def ManifestArrayCore.Insts.CoreCmpEq : core.cmp.Eq ManifestArrayCore := {
  partialEqInst := ManifestArrayCore.Insts.CoreCmpPartialEqManifestArrayCore
  assert_fields_are_eq :=
    ManifestArrayCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ArchiveCore}::clone]:
    Source: 'src/lib.rs', lines 87:9-87:14
    Visibility: public -/
def ArchiveCore.Insts.CoreCloneClone.clone
  (self : ArchiveCore) : Result ArchiveCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ArchiveCore}]
    Source: 'src/lib.rs', lines 87:9-87:14 -/
@[reducible]
def ArchiveCore.Insts.CoreCloneClone : core.clone.Clone ArchiveCore := {
  clone := ArchiveCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::ArchiveCore}]
    Source: 'src/lib.rs', lines 87:16-87:20 -/
@[reducible]
def ArchiveCore.Insts.CoreMarkerCopy : core.marker.Copy ArchiveCore := {
  cloneInst := ArchiveCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ArchiveCore}::fmt]:
    Source: 'src/lib.rs', lines 87:22-87:27
    Visibility: public -/
def ArchiveCore.Insts.CoreFmtDebug.fmt
  (self : ArchiveCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ HeaderCore.Insts.CoreFmtDebug self.header
  let dyn1 := Dyn.mk _ MetadataCore.Insts.CoreFmtDebug self.metadata
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared ManifestArrayCore.Insts.CoreFmtDebug)
      self.manifest
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "ArchiveCore") (toStr
    "header") dyn (toStr "metadata") dyn1 (toStr "manifest") dyn2

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ArchiveCore}]
    Source: 'src/lib.rs', lines 87:22-87:27 -/
@[reducible]
def ArchiveCore.Insts.CoreFmtDebug : core.fmt.Debug ArchiveCore := {
  fmt := ArchiveCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::ArchiveCore}]
    Source: 'src/lib.rs', lines 87:29-87:38 -/
@[reducible]
def ArchiveCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ArchiveCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ArchiveCore> for rao_archive_verif::ArchiveCore}::eq]:
    Source: 'src/lib.rs', lines 87:29-87:38
    Visibility: public -/
def ArchiveCore.Insts.CoreCmpPartialEqArchiveCore.eq
  (self : ArchiveCore) (other : ArchiveCore) : Result Bool := do
  let b ←
    HeaderCore.Insts.CoreCmpPartialEqHeaderCore.eq self.header other.header
  if b
  then
    let b1 ←
      MetadataCore.Insts.CoreCmpPartialEqMetadataCore.eq self.metadata
        other.metadata
    if b1
    then
      ManifestArrayCore.Insts.CoreCmpPartialEqManifestArrayCore.eq
        self.manifest other.manifest
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ArchiveCore> for rao_archive_verif::ArchiveCore}]
    Source: 'src/lib.rs', lines 87:29-87:38 -/
@[reducible]
def ArchiveCore.Insts.CoreCmpPartialEqArchiveCore : core.cmp.PartialEq
  ArchiveCore ArchiveCore := {
  eq := ArchiveCore.Insts.CoreCmpPartialEqArchiveCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ArchiveCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 87:40-87:42
    Visibility: public -/
def ArchiveCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ArchiveCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ArchiveCore}]
    Source: 'src/lib.rs', lines 87:40-87:42 -/
@[reducible]
def ArchiveCore.Insts.CoreCmpEq : core.cmp.Eq ArchiveCore := {
  partialEqInst := ArchiveCore.Insts.CoreCmpPartialEqArchiveCore
  assert_fields_are_eq := ArchiveCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::HeaderWireCore}::clone]:
    Source: 'src/lib.rs', lines 94:9-94:14
    Visibility: public -/
def HeaderWireCore.Insts.CoreCloneClone.clone
  (self : HeaderWireCore) : Result HeaderWireCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::HeaderWireCore}]
    Source: 'src/lib.rs', lines 94:9-94:14 -/
@[reducible]
def HeaderWireCore.Insts.CoreCloneClone : core.clone.Clone HeaderWireCore := {
  clone := HeaderWireCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::HeaderWireCore}]
    Source: 'src/lib.rs', lines 94:16-94:20 -/
@[reducible]
def HeaderWireCore.Insts.CoreMarkerCopy : core.marker.Copy HeaderWireCore := {
  cloneInst := HeaderWireCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::HeaderWireCore}::fmt]:
    Source: 'src/lib.rs', lines 94:22-94:27
    Visibility: public -/
def HeaderWireCore.Insts.CoreFmtDebug.fmt
  (self : HeaderWireCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugBool self.magic_rao1
  let dyn1 := Dyn.mk _ core.fmt.DebugU16 self.header_len
  let dyn2 := Dyn.mk _ core.fmt.DebugU8 self.format_version
  let dyn3 := Dyn.mk _ core.fmt.DebugU8 self.suite_id
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.object_id
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.chunk_size
  let dyn6 := Dyn.mk _ core.fmt.DebugU32 self.flags
  let dyn7 := Dyn.mk _ core.fmt.DebugBool self.key_id_nonzero
  let dyn8 := Dyn.mk _ core.fmt.DebugBool self.hkdf_salt_nonzero
  let dyn9 := Dyn.mk _ core.fmt.DebugU64 self.metadata_frame_len
  let dyn10 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.reserved_zero
  let values :=
    Array.to_slice
      (Array.make 11#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 11#usize [
        toStr "magic_rao1", toStr "header_len", toStr "format_version", toStr
        "suite_id", toStr "object_id", toStr "chunk_size", toStr "flags", toStr
        "key_id_nonzero", toStr "hkdf_salt_nonzero", toStr
        "metadata_frame_len", toStr "reserved_zero"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "HeaderWireCore") s
    values

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::HeaderWireCore}]
    Source: 'src/lib.rs', lines 94:22-94:27 -/
@[reducible]
def HeaderWireCore.Insts.CoreFmtDebug : core.fmt.Debug HeaderWireCore := {
  fmt := HeaderWireCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::HeaderWireCore}]
    Source: 'src/lib.rs', lines 94:29-94:38 -/
@[reducible]
def HeaderWireCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq HeaderWireCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::HeaderWireCore> for rao_archive_verif::HeaderWireCore}::eq]:
    Source: 'src/lib.rs', lines 94:29-94:38
    Visibility: public -/
def HeaderWireCore.Insts.CoreCmpPartialEqHeaderWireCore.eq
  (self : HeaderWireCore) (other : HeaderWireCore) : Result Bool := do
  if self.magic_rao1 = other.magic_rao1
  then
    if self.header_len = other.header_len
    then
      if self.format_version = other.format_version
      then
        if self.suite_id = other.suite_id
        then
          if self.object_id = other.object_id
          then
            if self.chunk_size = other.chunk_size
            then
              if self.flags = other.flags
              then
                if self.key_id_nonzero = other.key_id_nonzero
                then
                  if self.hkdf_salt_nonzero = other.hkdf_salt_nonzero
                  then
                    if self.metadata_frame_len = other.metadata_frame_len
                    then ok (self.reserved_zero = other.reserved_zero)
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::HeaderWireCore> for rao_archive_verif::HeaderWireCore}]
    Source: 'src/lib.rs', lines 94:29-94:38 -/
@[reducible]
def HeaderWireCore.Insts.CoreCmpPartialEqHeaderWireCore : core.cmp.PartialEq
  HeaderWireCore HeaderWireCore := {
  eq := HeaderWireCore.Insts.CoreCmpPartialEqHeaderWireCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::HeaderWireCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 94:40-94:42
    Visibility: public -/
def HeaderWireCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : HeaderWireCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::HeaderWireCore}]
    Source: 'src/lib.rs', lines 94:40-94:42 -/
@[reducible]
def HeaderWireCore.Insts.CoreCmpEq : core.cmp.Eq HeaderWireCore := {
  partialEqInst := HeaderWireCore.Insts.CoreCmpPartialEqHeaderWireCore
  assert_fields_are_eq := HeaderWireCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::MetadataWireCore}::clone]:
    Source: 'src/lib.rs', lines 109:9-109:14
    Visibility: public -/
def MetadataWireCore.Insts.CoreCloneClone.clone
  (self : MetadataWireCore) : Result MetadataWireCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::MetadataWireCore}]
    Source: 'src/lib.rs', lines 109:9-109:14 -/
@[reducible]
def MetadataWireCore.Insts.CoreCloneClone : core.clone.Clone MetadataWireCore
  := {
  clone := MetadataWireCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::MetadataWireCore}]
    Source: 'src/lib.rs', lines 109:16-109:20 -/
@[reducible]
def MetadataWireCore.Insts.CoreMarkerCopy : core.marker.Copy MetadataWireCore
  := {
  cloneInst := MetadataWireCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::MetadataWireCore}::fmt]:
    Source: 'src/lib.rs', lines 109:22-109:27
    Visibility: public -/
def MetadataWireCore.Insts.CoreFmtDebug.fmt
  (self : MetadataWireCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.map_len
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.metadata_version
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.plaintext_size
  let dyn3 := Dyn.mk _ core.fmt.DebugBool self.digest_alg_sha256
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.digest_byte_len
  let dyn5 := Dyn.mk _ DigestWords.Insts.CoreFmtDebug self.digest
  let dyn6 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.trailing_data
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "map_len", toStr "metadata_version", toStr "plaintext_size",
        toStr "digest_alg_sha256", toStr "digest_byte_len", toStr "digest",
        toStr "trailing_data"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "MetadataWireCore") s
    values

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::MetadataWireCore}]
    Source: 'src/lib.rs', lines 109:22-109:27 -/
@[reducible]
def MetadataWireCore.Insts.CoreFmtDebug : core.fmt.Debug MetadataWireCore := {
  fmt := MetadataWireCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::MetadataWireCore}]
    Source: 'src/lib.rs', lines 109:29-109:38 -/
@[reducible]
def MetadataWireCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq MetadataWireCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::MetadataWireCore> for rao_archive_verif::MetadataWireCore}::eq]:
    Source: 'src/lib.rs', lines 109:29-109:38
    Visibility: public -/
def MetadataWireCore.Insts.CoreCmpPartialEqMetadataWireCore.eq
  (self : MetadataWireCore) (other : MetadataWireCore) : Result Bool := do
  if self.map_len = other.map_len
  then
    if self.metadata_version = other.metadata_version
    then
      if self.plaintext_size = other.plaintext_size
      then
        if self.digest_alg_sha256 = other.digest_alg_sha256
        then
          if self.digest_byte_len = other.digest_byte_len
          then
            if self.trailing_data = other.trailing_data
            then
              DigestWords.Insts.CoreCmpPartialEqDigestWords.eq self.digest
                other.digest
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::MetadataWireCore> for rao_archive_verif::MetadataWireCore}]
    Source: 'src/lib.rs', lines 109:29-109:38 -/
@[reducible]
def MetadataWireCore.Insts.CoreCmpPartialEqMetadataWireCore :
  core.cmp.PartialEq MetadataWireCore MetadataWireCore := {
  eq := MetadataWireCore.Insts.CoreCmpPartialEqMetadataWireCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::MetadataWireCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 109:40-109:42
    Visibility: public -/
def MetadataWireCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : MetadataWireCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::MetadataWireCore}]
    Source: 'src/lib.rs', lines 109:40-109:42 -/
@[reducible]
def MetadataWireCore.Insts.CoreCmpEq : core.cmp.Eq MetadataWireCore := {
  partialEqInst := MetadataWireCore.Insts.CoreCmpPartialEqMetadataWireCore
  assert_fields_are_eq := MetadataWireCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ManifestArrayWireCore}::clone]:
    Source: 'src/lib.rs', lines 120:9-120:14
    Visibility: public -/
def ManifestArrayWireCore.Insts.CoreCloneClone.clone
  (self : ManifestArrayWireCore) : Result ManifestArrayWireCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ManifestArrayWireCore}]
    Source: 'src/lib.rs', lines 120:9-120:14 -/
@[reducible]
def ManifestArrayWireCore.Insts.CoreCloneClone : core.clone.Clone
  ManifestArrayWireCore := {
  clone := ManifestArrayWireCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::ManifestArrayWireCore}]
    Source: 'src/lib.rs', lines 120:16-120:20 -/
@[reducible]
def ManifestArrayWireCore.Insts.CoreMarkerCopy : core.marker.Copy
  ManifestArrayWireCore := {
  cloneInst := ManifestArrayWireCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ManifestArrayWireCore}::fmt]:
    Source: 'src/lib.rs', lines 120:22-120:27
    Visibility: public -/
def ManifestArrayWireCore.Insts.CoreFmtDebug.fmt
  (self : ManifestArrayWireCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.root_map_len
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.object_id
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.caller_object_id
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.chunk_size
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.file_entries_len
  let dyn5 := Dyn.mk _ core.fmt.DebugU64 self.schema_version
  let dyn6 := Dyn.mk _ core.fmt.DebugBool self.object_metadata_empty
  let dyn7 := Dyn.mk _ core.fmt.DebugBool self.external_references_empty
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.nonempty_regular_path_id
  let dyn9 := Dyn.mk _ core.fmt.DebugU64 self.nonempty_regular_file_id
  let dyn10 := Dyn.mk _ core.fmt.DebugU64 self.nonempty_regular_size_bytes
  let dyn11 :=
    Dyn.mk _ DigestWords.Insts.CoreFmtDebug self.nonempty_regular_sha256
  let dyn12 := Dyn.mk _ core.fmt.DebugU64 self.empty_regular_path_id
  let dyn13 := Dyn.mk _ core.fmt.DebugU64 self.empty_regular_file_id
  let dyn14 := Dyn.mk _ core.fmt.DebugU64 self.hardlink_path_id
  let dyn15 := Dyn.mk _ core.fmt.DebugU64 self.hardlink_file_id
  let dyn16 := Dyn.mk _ core.fmt.DebugU64 self.hardlink_target_path_id
  let dyn17 := Dyn.mk _ core.fmt.DebugU64 self.symlink_path_id
  let dyn18 := Dyn.mk _ core.fmt.DebugU64 self.symlink_file_id
  let dyn19 := Dyn.mk _ core.fmt.DebugU64 self.symlink_target_id
  let dyn20 := Dyn.mk _ core.fmt.DebugU64 self.directory_path_id
  let dyn21 := Dyn.mk _ core.fmt.DebugU64 self.directory_file_id
  let dyn22 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.trailing_data
  let values :=
    Array.to_slice
      (Array.make 23#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10,
        dyn11, dyn12, dyn13, dyn14, dyn15, dyn16, dyn17, dyn18, dyn19, dyn20,
        dyn21, dyn22
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 23#usize [
        toStr "root_map_len", toStr "object_id", toStr "caller_object_id",
        toStr "chunk_size", toStr "file_entries_len", toStr "schema_version",
        toStr "object_metadata_empty", toStr "external_references_empty", toStr
        "nonempty_regular_path_id", toStr "nonempty_regular_file_id", toStr
        "nonempty_regular_size_bytes", toStr "nonempty_regular_sha256", toStr
        "empty_regular_path_id", toStr "empty_regular_file_id", toStr
        "hardlink_path_id", toStr "hardlink_file_id", toStr
        "hardlink_target_path_id", toStr "symlink_path_id", toStr
        "symlink_file_id", toStr "symlink_target_id", toStr
        "directory_path_id", toStr "directory_file_id", toStr "trailing_data"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr
    "ManifestArrayWireCore") s values

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ManifestArrayWireCore}]
    Source: 'src/lib.rs', lines 120:22-120:27 -/
@[reducible]
def ManifestArrayWireCore.Insts.CoreFmtDebug : core.fmt.Debug
  ManifestArrayWireCore := {
  fmt := ManifestArrayWireCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::ManifestArrayWireCore}]
    Source: 'src/lib.rs', lines 120:29-120:38 -/
@[reducible]
def ManifestArrayWireCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ManifestArrayWireCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ManifestArrayWireCore> for rao_archive_verif::ManifestArrayWireCore}::eq]:
    Source: 'src/lib.rs', lines 120:29-120:38
    Visibility: public -/
def ManifestArrayWireCore.Insts.CoreCmpPartialEqManifestArrayWireCore.eq
  (self : ManifestArrayWireCore) (other : ManifestArrayWireCore) :
  Result Bool
  := do
  if self.root_map_len = other.root_map_len
  then
    if self.object_id = other.object_id
    then
      if self.caller_object_id = other.caller_object_id
      then
        if self.chunk_size = other.chunk_size
        then
          if self.file_entries_len = other.file_entries_len
          then
            if self.schema_version = other.schema_version
            then
              if self.object_metadata_empty = other.object_metadata_empty
              then
                if self.external_references_empty =
                  other.external_references_empty
                then
                  if self.nonempty_regular_path_id =
                    other.nonempty_regular_path_id
                  then
                    if self.nonempty_regular_file_id =
                      other.nonempty_regular_file_id
                    then
                      if self.nonempty_regular_size_bytes =
                        other.nonempty_regular_size_bytes
                      then
                        if self.empty_regular_path_id =
                          other.empty_regular_path_id
                        then
                          if self.empty_regular_file_id =
                            other.empty_regular_file_id
                          then
                            if self.hardlink_path_id = other.hardlink_path_id
                            then
                              if self.hardlink_file_id = other.hardlink_file_id
                              then
                                if self.hardlink_target_path_id =
                                  other.hardlink_target_path_id
                                then
                                  if self.symlink_path_id =
                                    other.symlink_path_id
                                  then
                                    if self.symlink_file_id =
                                      other.symlink_file_id
                                    then
                                      if self.symlink_target_id =
                                        other.symlink_target_id
                                      then
                                        if self.directory_path_id =
                                          other.directory_path_id
                                        then
                                          if self.directory_file_id =
                                            other.directory_file_id
                                          then
                                            if self.trailing_data =
                                              other.trailing_data
                                            then
                                              DigestWords.Insts.CoreCmpPartialEqDigestWords.eq
                                                self.nonempty_regular_sha256
                                                other.nonempty_regular_sha256
                                            else ok false
                                          else ok false
                                        else ok false
                                      else ok false
                                    else ok false
                                  else ok false
                                else ok false
                              else ok false
                            else ok false
                          else ok false
                        else ok false
                      else ok false
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ManifestArrayWireCore> for rao_archive_verif::ManifestArrayWireCore}]
    Source: 'src/lib.rs', lines 120:29-120:38 -/
@[reducible]
def ManifestArrayWireCore.Insts.CoreCmpPartialEqManifestArrayWireCore :
  core.cmp.PartialEq ManifestArrayWireCore ManifestArrayWireCore := {
  eq := ManifestArrayWireCore.Insts.CoreCmpPartialEqManifestArrayWireCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ManifestArrayWireCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 120:40-120:42
    Visibility: public -/
def ManifestArrayWireCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ManifestArrayWireCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ManifestArrayWireCore}]
    Source: 'src/lib.rs', lines 120:40-120:42 -/
@[reducible]
def ManifestArrayWireCore.Insts.CoreCmpEq : core.cmp.Eq ManifestArrayWireCore
  := {
  partialEqInst :=
    ManifestArrayWireCore.Insts.CoreCmpPartialEqManifestArrayWireCore
  assert_fields_are_eq :=
    ManifestArrayWireCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ArchiveWireCore}::clone]:
    Source: 'src/lib.rs', lines 147:9-147:14
    Visibility: public -/
def ArchiveWireCore.Insts.CoreCloneClone.clone
  (self : ArchiveWireCore) : Result ArchiveWireCore := do
  ok self

/-- Trait implementation: [rao_archive_verif::{impl core::clone::Clone for rao_archive_verif::ArchiveWireCore}]
    Source: 'src/lib.rs', lines 147:9-147:14 -/
@[reducible]
def ArchiveWireCore.Insts.CoreCloneClone : core.clone.Clone ArchiveWireCore
  := {
  clone := ArchiveWireCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::Copy for rao_archive_verif::ArchiveWireCore}]
    Source: 'src/lib.rs', lines 147:16-147:20 -/
@[reducible]
def ArchiveWireCore.Insts.CoreMarkerCopy : core.marker.Copy ArchiveWireCore
  := {
  cloneInst := ArchiveWireCore.Insts.CoreCloneClone
}

/-- [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ArchiveWireCore}::fmt]:
    Source: 'src/lib.rs', lines 147:22-147:27
    Visibility: public -/
def ArchiveWireCore.Insts.CoreFmtDebug.fmt
  (self : ArchiveWireCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ HeaderWireCore.Insts.CoreFmtDebug self.header
  let dyn1 := Dyn.mk _ MetadataWireCore.Insts.CoreFmtDebug self.metadata
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared ManifestArrayWireCore.Insts.CoreFmtDebug)
      self.manifest
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "ArchiveWireCore")
    (toStr "header") dyn (toStr "metadata") dyn1 (toStr "manifest") dyn2

/-- Trait implementation: [rao_archive_verif::{impl core::fmt::Debug for rao_archive_verif::ArchiveWireCore}]
    Source: 'src/lib.rs', lines 147:22-147:27 -/
@[reducible]
def ArchiveWireCore.Insts.CoreFmtDebug : core.fmt.Debug ArchiveWireCore := {
  fmt := ArchiveWireCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_archive_verif::{impl core::marker::StructuralPartialEq for rao_archive_verif::ArchiveWireCore}]
    Source: 'src/lib.rs', lines 147:29-147:38 -/
@[reducible]
def ArchiveWireCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ArchiveWireCore := {
}

/-- [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ArchiveWireCore> for rao_archive_verif::ArchiveWireCore}::eq]:
    Source: 'src/lib.rs', lines 147:29-147:38
    Visibility: public -/
def ArchiveWireCore.Insts.CoreCmpPartialEqArchiveWireCore.eq
  (self : ArchiveWireCore) (other : ArchiveWireCore) : Result Bool := do
  let b ←
    HeaderWireCore.Insts.CoreCmpPartialEqHeaderWireCore.eq self.header
      other.header
  if b
  then
    let b1 ←
      MetadataWireCore.Insts.CoreCmpPartialEqMetadataWireCore.eq self.metadata
        other.metadata
    if b1
    then
      ManifestArrayWireCore.Insts.CoreCmpPartialEqManifestArrayWireCore.eq
        self.manifest other.manifest
    else ok false
  else ok false

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::PartialEq<rao_archive_verif::ArchiveWireCore> for rao_archive_verif::ArchiveWireCore}]
    Source: 'src/lib.rs', lines 147:29-147:38 -/
@[reducible]
def ArchiveWireCore.Insts.CoreCmpPartialEqArchiveWireCore : core.cmp.PartialEq
  ArchiveWireCore ArchiveWireCore := {
  eq := ArchiveWireCore.Insts.CoreCmpPartialEqArchiveWireCore.eq
}

/-- [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ArchiveWireCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 147:40-147:42
    Visibility: public -/
def ArchiveWireCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ArchiveWireCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_archive_verif::{impl core::cmp::Eq for rao_archive_verif::ArchiveWireCore}]
    Source: 'src/lib.rs', lines 147:40-147:42 -/
@[reducible]
def ArchiveWireCore.Insts.CoreCmpEq : core.cmp.Eq ArchiveWireCore := {
  partialEqInst := ArchiveWireCore.Insts.CoreCmpPartialEqArchiveWireCore
  assert_fields_are_eq := ArchiveWireCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_archive_verif::checked_add]:
    Source: 'src/lib.rs', lines 154:0-159:1
    Visibility: public -/
def checked_add
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 RaoArchiveError)
  := do
  let o ← lift (U64.checked_add a b)
  match o with
  | none => ok (core.result.Result.Err RaoArchiveError.InvalidMetadataField)
  | some sum => ok (core.result.Result.Ok sum)

/-- [rao_archive_verif::checked_mul]:
    Source: 'src/lib.rs', lines 161:0-166:1
    Visibility: public -/
def checked_mul
  (a : Std.U64) (b : Std.U64) :
  Result (core.result.Result Std.U64 RaoArchiveError)
  := do
  let o ← lift (U64.checked_mul a b)
  match o with
  | none => ok (core.result.Result.Err RaoArchiveError.InvalidMetadataField)
  | some product => ok (core.result.Result.Ok product)

/-- [rao_archive_verif::validate_chunk_size]:
    Source: 'src/lib.rs', lines 168:0-173:1
    Visibility: public -/
def validate_chunk_size
  (chunk_size : Std.U64) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  if chunk_size = 0#u64
  then ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
  else
    let i ← chunk_size % CHUNK_SIZE_GRANULARITY
    if i != 0#u64
    then ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
    else ok (core.result.Result.Ok ())

/-- [rao_archive_verif::validate_header_core]:
    Source: 'src/lib.rs', lines 175:0-190:1
    Visibility: public -/
def validate_header_core
  (header : HeaderCore) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  let r ← validate_chunk_size header.chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if header.object_id = 0#u64
    then ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
    else
      if header.key_id_nonzero
      then
        if header.hkdf_salt_nonzero
        then
          if header.metadata_frame_len < RAO_METADATA_FRAME_MIN_LEN
          then ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
          else
            if header.metadata_frame_len > RAO_MAX_METADATA_FRAME_LEN
            then ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
            else ok (core.result.Result.Ok ())
        else ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
      else ok (core.result.Result.Err RaoArchiveError.InvalidHeaderField)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoArchiveError) residual

/-- [rao_archive_verif::validate_metadata_core]:
    Source: 'src/lib.rs', lines 192:0-204:1
    Visibility: public -/
def validate_metadata_core
  (metadata : MetadataCore) (chunk_size : Std.U64) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  let r ← validate_chunk_size chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if metadata.plaintext_size = 0#u64
    then ok (core.result.Result.Err RaoArchiveError.InvalidMetadataField)
    else
      let i ← metadata.plaintext_size % chunk_size
      if i != 0#u64
      then ok (core.result.Result.Err RaoArchiveError.InvalidMetadataField)
      else
        let chunk_count ← metadata.plaintext_size / chunk_size
        let r1 ← checked_mul CHACHA20POLY1305_TAG_LEN chunk_count
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let r2 ← checked_add metadata.plaintext_size val
          let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            ok (core.result.Result.Ok ())
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Unit (core.convert.FromSame RaoArchiveError) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Unit (core.convert.FromSame RaoArchiveError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoArchiveError) residual

/-- [rao_archive_verif::distinct5_core]:
    Source: 'src/lib.rs', lines 206:0-244:1
    Visibility: public -/
def distinct5_core
  (first : Std.U64) (second : Std.U64) (third : Std.U64) (fourth : Std.U64)
  (fifth : Std.U64) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  if first = second
  then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
  else
    if first = third
    then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
    else
      if first = fourth
      then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
      else
        if first = fifth
        then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
        else
          if second = third
          then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
          else
            if second = fourth
            then
              ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
            else
              if second = fifth
              then
                ok (core.result.Result.Err
                  RaoArchiveError.InvalidManifestField)
              else
                if third = fourth
                then
                  ok (core.result.Result.Err
                    RaoArchiveError.InvalidManifestField)
                else
                  if third = fifth
                  then
                    ok (core.result.Result.Err
                      RaoArchiveError.InvalidManifestField)
                  else
                    if fourth = fifth
                    then
                      ok (core.result.Result.Err
                        RaoArchiveError.InvalidManifestField)
                    else ok (core.result.Result.Ok ())

/-- [rao_archive_verif::hardlink_target_seen_regular_prefix_two_core]:
    Source: 'src/lib.rs', lines 246:0-258:1
    Visibility: public -/
def hardlink_target_seen_regular_prefix_two_core
  (target : Std.U64) (first_regular_path : Std.U64)
  (second_regular_path : Std.U64) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  if target = first_regular_path
  then ok (core.result.Result.Ok ())
  else
    if target = second_regular_path
    then ok (core.result.Result.Ok ())
    else ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)

/-- [rao_archive_verif::validate_manifest_array_core]:
    Source: 'src/lib.rs', lines 260:0-305:1
    Visibility: public -/
def validate_manifest_array_core
  (manifest : ManifestArrayCore) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  let r ← validate_chunk_size manifest.chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if manifest.object_id = 0#u64
    then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
    else
      if manifest.nonempty_regular_path_id = 0#u64
      then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
      else
        if manifest.nonempty_regular_file_id = 0#u64
        then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
        else
          if manifest.empty_regular_path_id = 0#u64
          then ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
          else
            if manifest.empty_regular_file_id = 0#u64
            then
              ok (core.result.Result.Err RaoArchiveError.InvalidManifestField)
            else
              if manifest.hardlink_path_id = 0#u64
              then
                ok (core.result.Result.Err
                  RaoArchiveError.InvalidManifestField)
              else
                if manifest.hardlink_file_id = 0#u64
                then
                  ok (core.result.Result.Err
                    RaoArchiveError.InvalidManifestField)
                else
                  if manifest.symlink_path_id = 0#u64
                  then
                    ok (core.result.Result.Err
                      RaoArchiveError.InvalidManifestField)
                  else
                    if manifest.symlink_file_id = 0#u64
                    then
                      ok (core.result.Result.Err
                        RaoArchiveError.InvalidManifestField)
                    else
                      if manifest.symlink_target_id = 0#u64
                      then
                        ok (core.result.Result.Err
                          RaoArchiveError.InvalidManifestField)
                      else
                        if manifest.directory_path_id = 0#u64
                        then
                          ok (core.result.Result.Err
                            RaoArchiveError.InvalidManifestField)
                        else
                          if manifest.directory_file_id = 0#u64
                          then
                            ok (core.result.Result.Err
                              RaoArchiveError.InvalidManifestField)
                          else
                            if manifest.nonempty_regular_size_bytes = 0#u64
                            then
                              ok (core.result.Result.Err
                                RaoArchiveError.InvalidManifestField)
                            else
                              let i ←
                                manifest.nonempty_regular_size_bytes %
                                  manifest.chunk_size
                              if i != 0#u64
                              then
                                ok (core.result.Result.Err
                                  RaoArchiveError.InvalidManifestField)
                              else
                                let r1 ←
                                  distinct5_core
                                    manifest.nonempty_regular_path_id
                                    manifest.empty_regular_path_id
                                    manifest.hardlink_path_id
                                    manifest.symlink_path_id
                                    manifest.directory_path_id
                                let cf1 ←
                                  core.result.Result.Insts.CoreOpsTry.branch r1
                                match cf1 with
                                | core.ops.control_flow.ControlFlow.Continue _
                                  =>
                                  let r2 ←
                                    distinct5_core
                                      manifest.nonempty_regular_file_id
                                      manifest.empty_regular_file_id
                                      manifest.hardlink_file_id
                                      manifest.symlink_file_id
                                      manifest.directory_file_id
                                  let cf2 ←
                                    core.result.Result.Insts.CoreOpsTry.branch
                                      r2
                                  match cf2 with
                                  | core.ops.control_flow.ControlFlow.Continue
                                    _ =>
                                    let r3 ←
                                      hardlink_target_seen_regular_prefix_two_core
                                        manifest.hardlink_target_path_id
                                        manifest.nonempty_regular_path_id
                                        manifest.empty_regular_path_id
                                    let cf3 ←
                                      core.result.Result.Insts.CoreOpsTry.branch
                                        r3
                                    match cf3 with
                                    |
                                      core.ops.control_flow.ControlFlow.Continue
                                      _ =>
                                      ok (core.result.Result.Ok ())
                                    | core.ops.control_flow.ControlFlow.Break
                                      residual =>
                                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                        Unit (core.convert.FromSame
                                        RaoArchiveError) residual
                                  | core.ops.control_flow.ControlFlow.Break
                                    residual =>
                                    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                      Unit (core.convert.FromSame
                                      RaoArchiveError) residual
                                | core.ops.control_flow.ControlFlow.Break
                                  residual =>
                                  core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                    Unit (core.convert.FromSame
                                    RaoArchiveError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoArchiveError) residual

/-- [rao_archive_verif::validate_archive_core]:
    Source: 'src/lib.rs', lines 307:0-318:1
    Visibility: public -/
def validate_archive_core
  (archive : ArchiveCore) :
  Result (core.result.Result Unit RaoArchiveError)
  := do
  let r ← validate_header_core archive.header
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let r1 ←
      validate_metadata_core archive.metadata archive.header.chunk_size
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      let r2 ← validate_manifest_array_core archive.manifest
      let cf2 ← core.result.Result.Insts.CoreOpsTry.branch r2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        if archive.header.chunk_size != archive.manifest.chunk_size
        then ok (core.result.Result.Err RaoArchiveError.InvalidArchiveField)
        else
          if archive.header.object_id != archive.manifest.object_id
          then ok (core.result.Result.Err RaoArchiveError.InvalidArchiveField)
          else ok (core.result.Result.Ok ())
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame RaoArchiveError) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Unit (core.convert.FromSame RaoArchiveError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoArchiveError) residual

/-- [rao_archive_verif::encode_archive_core]:
    Source: 'src/lib.rs', lines 320:0-371:1
    Visibility: public -/
def encode_archive_core
  (archive : ArchiveCore) :
  Result (core.result.Result ArchiveWireCore RaoArchiveError)
  := do
  let r ← validate_archive_core archive
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    ok (core.result.Result.Ok
      {
        header :=
          {
            magic_rao1 := true,
            header_len := RAO_HEADER_LEN_U16,
            format_version := FORMAT_VERSION,
            suite_id := SUITE_ID_HKDF_SHA256_CHACHA20POLY1305,
            object_id := archive.header.object_id,
            chunk_size := archive.header.chunk_size,
            flags := 0#u32,
            key_id_nonzero := archive.header.key_id_nonzero,
            hkdf_salt_nonzero := archive.header.hkdf_salt_nonzero,
            metadata_frame_len := archive.header.metadata_frame_len,
            reserved_zero := true
          },
        metadata :=
          {
            map_len := METADATA_REQUIRED_MAP_LEN,
            metadata_version := METADATA_VERSION,
            plaintext_size := archive.metadata.plaintext_size,
            digest_alg_sha256 := true,
            digest_byte_len := DIGEST_BYTE_LEN,
            digest := archive.metadata.digest,
            trailing_data := false
          },
        manifest :=
          {
            root_map_len := MANIFEST_ROOT_MAP_LEN,
            object_id := archive.manifest.object_id,
            caller_object_id := archive.manifest.caller_object_id,
            chunk_size := archive.manifest.chunk_size,
            file_entries_len := MANIFEST_FILE_ENTRIES_LEN,
            schema_version := MANIFEST_SCHEMA_VERSION,
            object_metadata_empty := true,
            external_references_empty := true,
            nonempty_regular_path_id :=
              archive.manifest.nonempty_regular_path_id,
            nonempty_regular_file_id :=
              archive.manifest.nonempty_regular_file_id,
            nonempty_regular_size_bytes :=
              archive.manifest.nonempty_regular_size_bytes,
            nonempty_regular_sha256 := archive.manifest.nonempty_regular_sha256,
            empty_regular_path_id := archive.manifest.empty_regular_path_id,
            empty_regular_file_id := archive.manifest.empty_regular_file_id,
            hardlink_path_id := archive.manifest.hardlink_path_id,
            hardlink_file_id := archive.manifest.hardlink_file_id,
            hardlink_target_path_id := archive.manifest.hardlink_target_path_id,
            symlink_path_id := archive.manifest.symlink_path_id,
            symlink_file_id := archive.manifest.symlink_file_id,
            symlink_target_id := archive.manifest.symlink_target_id,
            directory_path_id := archive.manifest.directory_path_id,
            directory_file_id := archive.manifest.directory_file_id,
            trailing_data := false
          }
      })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      ArchiveWireCore (core.convert.FromSame RaoArchiveError) residual

/-- [rao_archive_verif::decode_archive_core]:
    Source: 'src/lib.rs', lines 373:0-435:1
    Visibility: public -/
def decode_archive_core
  (wire : ArchiveWireCore) :
  Result (core.result.Result ArchiveCore RaoArchiveError)
  := do
  if wire.header.magic_rao1
  then
    if wire.header.header_len != RAO_HEADER_LEN_U16
    then ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
    else
      if wire.header.format_version != FORMAT_VERSION
      then ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
      else
        if wire.header.suite_id != SUITE_ID_HKDF_SHA256_CHACHA20POLY1305
        then ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
        else
          if wire.header.flags != 0#u32
          then ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
          else
            if wire.header.reserved_zero
            then
              if wire.metadata.trailing_data
              then ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
              else
                if wire.metadata.map_len != METADATA_REQUIRED_MAP_LEN
                then
                  ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
                else
                  if wire.metadata.metadata_version != METADATA_VERSION
                  then
                    ok (core.result.Result.Err
                      RaoArchiveError.InvalidWireShape)
                  else
                    if wire.metadata.digest_alg_sha256
                    then
                      if wire.metadata.digest_byte_len != DIGEST_BYTE_LEN
                      then
                        ok (core.result.Result.Err
                          RaoArchiveError.InvalidWireShape)
                      else
                        if wire.manifest.trailing_data
                        then
                          ok (core.result.Result.Err
                            RaoArchiveError.InvalidWireShape)
                        else
                          if wire.manifest.root_map_len !=
                            MANIFEST_ROOT_MAP_LEN
                          then
                            ok (core.result.Result.Err
                              RaoArchiveError.InvalidWireShape)
                          else
                            if wire.manifest.file_entries_len !=
                              MANIFEST_FILE_ENTRIES_LEN
                            then
                              ok (core.result.Result.Err
                                RaoArchiveError.InvalidWireShape)
                            else
                              if wire.manifest.schema_version !=
                                MANIFEST_SCHEMA_VERSION
                              then
                                ok (core.result.Result.Err
                                  RaoArchiveError.InvalidWireShape)
                              else
                                if wire.manifest.object_metadata_empty
                                then
                                  if wire.manifest.external_references_empty
                                  then
                                    let r ←
                                      validate_archive_core
                                        {
                                          header :=
                                            {
                                              object_id :=
                                                wire.header.object_id,
                                              chunk_size :=
                                                wire.header.chunk_size,
                                              key_id_nonzero :=
                                                wire.header.key_id_nonzero,
                                              hkdf_salt_nonzero :=
                                                wire.header.hkdf_salt_nonzero,
                                              metadata_frame_len :=
                                                wire.header.metadata_frame_len
                                            },
                                          metadata :=
                                            {
                                              plaintext_size :=
                                                wire.metadata.plaintext_size,
                                              digest := wire.metadata.digest
                                            },
                                          manifest :=
                                            {
                                              object_id :=
                                                wire.manifest.object_id,
                                              caller_object_id :=
                                                wire.manifest.caller_object_id,
                                              chunk_size :=
                                                wire.manifest.chunk_size,
                                              nonempty_regular_path_id :=
                                                wire.manifest.nonempty_regular_path_id,
                                              nonempty_regular_file_id :=
                                                wire.manifest.nonempty_regular_file_id,
                                              nonempty_regular_size_bytes :=
                                                wire.manifest.nonempty_regular_size_bytes,
                                              nonempty_regular_sha256 :=
                                                wire.manifest.nonempty_regular_sha256,
                                              empty_regular_path_id :=
                                                wire.manifest.empty_regular_path_id,
                                              empty_regular_file_id :=
                                                wire.manifest.empty_regular_file_id,
                                              hardlink_path_id :=
                                                wire.manifest.hardlink_path_id,
                                              hardlink_file_id :=
                                                wire.manifest.hardlink_file_id,
                                              hardlink_target_path_id :=
                                                wire.manifest.hardlink_target_path_id,
                                              symlink_path_id :=
                                                wire.manifest.symlink_path_id,
                                              symlink_file_id :=
                                                wire.manifest.symlink_file_id,
                                              symlink_target_id :=
                                                wire.manifest.symlink_target_id,
                                              directory_path_id :=
                                                wire.manifest.directory_path_id,
                                              directory_file_id :=
                                                wire.manifest.directory_file_id
                                            }
                                        }
                                    let cf ←
                                      core.result.Result.Insts.CoreOpsTry.branch
                                        r
                                    match cf with
                                    |
                                      core.ops.control_flow.ControlFlow.Continue
                                      _ =>
                                      ok (core.result.Result.Ok
                                        {
                                          header :=
                                            {
                                              object_id :=
                                                wire.header.object_id,
                                              chunk_size :=
                                                wire.header.chunk_size,
                                              key_id_nonzero :=
                                                wire.header.key_id_nonzero,
                                              hkdf_salt_nonzero :=
                                                wire.header.hkdf_salt_nonzero,
                                              metadata_frame_len :=
                                                wire.header.metadata_frame_len
                                            },
                                          metadata :=
                                            {
                                              plaintext_size :=
                                                wire.metadata.plaintext_size,
                                              digest := wire.metadata.digest
                                            },
                                          manifest :=
                                            {
                                              object_id :=
                                                wire.manifest.object_id,
                                              caller_object_id :=
                                                wire.manifest.caller_object_id,
                                              chunk_size :=
                                                wire.manifest.chunk_size,
                                              nonempty_regular_path_id :=
                                                wire.manifest.nonempty_regular_path_id,
                                              nonempty_regular_file_id :=
                                                wire.manifest.nonempty_regular_file_id,
                                              nonempty_regular_size_bytes :=
                                                wire.manifest.nonempty_regular_size_bytes,
                                              nonempty_regular_sha256 :=
                                                wire.manifest.nonempty_regular_sha256,
                                              empty_regular_path_id :=
                                                wire.manifest.empty_regular_path_id,
                                              empty_regular_file_id :=
                                                wire.manifest.empty_regular_file_id,
                                              hardlink_path_id :=
                                                wire.manifest.hardlink_path_id,
                                              hardlink_file_id :=
                                                wire.manifest.hardlink_file_id,
                                              hardlink_target_path_id :=
                                                wire.manifest.hardlink_target_path_id,
                                              symlink_path_id :=
                                                wire.manifest.symlink_path_id,
                                              symlink_file_id :=
                                                wire.manifest.symlink_file_id,
                                              symlink_target_id :=
                                                wire.manifest.symlink_target_id,
                                              directory_path_id :=
                                                wire.manifest.directory_path_id,
                                              directory_file_id :=
                                                wire.manifest.directory_file_id
                                            }
                                        })
                                    | core.ops.control_flow.ControlFlow.Break
                                      residual =>
                                      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                                        ArchiveCore (core.convert.FromSame
                                        RaoArchiveError) residual
                                  else
                                    ok (core.result.Result.Err
                                      RaoArchiveError.InvalidWireShape)
                                else
                                  ok (core.result.Result.Err
                                    RaoArchiveError.InvalidWireShape)
                    else
                      ok (core.result.Result.Err
                        RaoArchiveError.InvalidWireShape)
            else ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)
  else ok (core.result.Result.Err RaoArchiveError.InvalidWireShape)

end RaoArchive
