-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_header_verif]: function definitions
import Aeneas
import RaoHeader.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoHeader

/-- [rao_header_verif::RAO_HEADER_LEN_U16]
    Source: 'src/lib.rs', lines 12:0-12:40
    Visibility: public -/
@[global_simps, irreducible] def RAO_HEADER_LEN_U16 : Std.U16 := 128#u16

/-- [rao_header_verif::FORMAT_VERSION]
    Source: 'src/lib.rs', lines 13:0-13:33
    Visibility: public -/
@[global_simps, irreducible] def FORMAT_VERSION : Std.U8 := 1#u8

/-- [rao_header_verif::SUITE_ID_HKDF_SHA256_CHACHA20POLY1305]
    Source: 'src/lib.rs', lines 14:0-14:59
    Visibility: public -/
@[global_simps, irreducible]
def SUITE_ID_HKDF_SHA256_CHACHA20POLY1305 : Std.U8 := 1#u8

/-- [rao_header_verif::CHUNK_SIZE_GRANULARITY]
    Source: 'src/lib.rs', lines 15:0-15:44
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_SIZE_GRANULARITY : Std.U32 := 512#u32

/-- [rao_header_verif::RAO_METADATA_FRAME_MIN_LEN]
    Source: 'src/lib.rs', lines 16:0-16:47
    Visibility: public -/
@[global_simps, irreducible] def RAO_METADATA_FRAME_MIN_LEN : Std.U64 := 17#u64

/-- [rao_header_verif::RAO_MAX_METADATA_FRAME_LEN]
    Source: 'src/lib.rs', lines 17:0-17:55
    Visibility: public -/
@[global_simps, irreducible]
def RAO_MAX_METADATA_FRAME_LEN : Std.U64 := 16777216#u64

/-- [rao_header_verif::{impl core::clone::Clone for rao_header_verif::RaoHeaderError}::clone]:
    Source: 'src/lib.rs', lines 19:9-19:14
    Visibility: public -/
def RaoHeaderError.Insts.CoreCloneClone.clone
  (self : RaoHeaderError) : Result RaoHeaderError := do
  ok self

/-- Trait implementation: [rao_header_verif::{impl core::clone::Clone for rao_header_verif::RaoHeaderError}]
    Source: 'src/lib.rs', lines 19:9-19:14 -/
@[reducible]
def RaoHeaderError.Insts.CoreCloneClone : core.clone.Clone RaoHeaderError := {
  clone := RaoHeaderError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_header_verif::{impl core::marker::Copy for rao_header_verif::RaoHeaderError}]
    Source: 'src/lib.rs', lines 19:16-19:20 -/
@[reducible]
def RaoHeaderError.Insts.CoreMarkerCopy : core.marker.Copy RaoHeaderError := {
  cloneInst := RaoHeaderError.Insts.CoreCloneClone
}

/-- [rao_header_verif::{impl core::fmt::Debug for rao_header_verif::RaoHeaderError}::fmt]:
    Source: 'src/lib.rs', lines 19:22-19:27
    Visibility: public -/
def RaoHeaderError.Insts.CoreFmtDebug.fmt
  (self : RaoHeaderError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | RaoHeaderError.InvalidMagicBytes =>
    core.fmt.Formatter.write_str f (toStr "InvalidMagicBytes")
  | RaoHeaderError.InvalidHeaderLength =>
    core.fmt.Formatter.write_str f (toStr "InvalidHeaderLength")
  | RaoHeaderError.UnsupportedFormatVersion =>
    core.fmt.Formatter.write_str f (toStr "UnsupportedFormatVersion")
  | RaoHeaderError.InvalidSuite =>
    core.fmt.Formatter.write_str f (toStr "InvalidSuite")
  | RaoHeaderError.InvalidChunkSize =>
    core.fmt.Formatter.write_str f (toStr "InvalidChunkSize")
  | RaoHeaderError.ReservedBytesNotZero =>
    core.fmt.Formatter.write_str f (toStr "ReservedBytesNotZero")
  | RaoHeaderError.InvalidKeyIdentifier =>
    core.fmt.Formatter.write_str f (toStr "InvalidKeyIdentifier")
  | RaoHeaderError.InvalidSalt =>
    core.fmt.Formatter.write_str f (toStr "InvalidSalt")
  | RaoHeaderError.MetadataFrameLengthInvalid =>
    core.fmt.Formatter.write_str f (toStr "MetadataFrameLengthInvalid")
  | RaoHeaderError.InvalidObjectIdField =>
    core.fmt.Formatter.write_str f (toStr "InvalidObjectIdField")

/-- Trait implementation: [rao_header_verif::{impl core::fmt::Debug for rao_header_verif::RaoHeaderError}]
    Source: 'src/lib.rs', lines 19:22-19:27 -/
@[reducible]
def RaoHeaderError.Insts.CoreFmtDebug : core.fmt.Debug RaoHeaderError := {
  fmt := RaoHeaderError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_header_verif::{impl core::marker::StructuralPartialEq for rao_header_verif::RaoHeaderError}]
    Source: 'src/lib.rs', lines 19:29-19:38 -/
@[reducible]
def RaoHeaderError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RaoHeaderError := {
}

/-- [rao_header_verif::{impl core::cmp::PartialEq<rao_header_verif::RaoHeaderError> for rao_header_verif::RaoHeaderError}::eq]:
    Source: 'src/lib.rs', lines 19:29-19:38
    Visibility: public -/
def RaoHeaderError.Insts.CoreCmpPartialEqRaoHeaderError.eq
  (self : RaoHeaderError) (other : RaoHeaderError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [rao_header_verif::{impl core::cmp::PartialEq<rao_header_verif::RaoHeaderError> for rao_header_verif::RaoHeaderError}]
    Source: 'src/lib.rs', lines 19:29-19:38 -/
@[reducible]
def RaoHeaderError.Insts.CoreCmpPartialEqRaoHeaderError : core.cmp.PartialEq
  RaoHeaderError RaoHeaderError := {
  eq := RaoHeaderError.Insts.CoreCmpPartialEqRaoHeaderError.eq
}

/-- [rao_header_verif::{impl core::cmp::Eq for rao_header_verif::RaoHeaderError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 19:40-19:42
    Visibility: public -/
def RaoHeaderError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RaoHeaderError) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_header_verif::{impl core::cmp::Eq for rao_header_verif::RaoHeaderError}]
    Source: 'src/lib.rs', lines 19:40-19:42 -/
@[reducible]
def RaoHeaderError.Insts.CoreCmpEq : core.cmp.Eq RaoHeaderError := {
  partialEqInst := RaoHeaderError.Insts.CoreCmpPartialEqRaoHeaderError
  assert_fields_are_eq := RaoHeaderError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_header_verif::{impl core::clone::Clone for rao_header_verif::HeaderCore}::clone]:
    Source: 'src/lib.rs', lines 33:9-33:14
    Visibility: public -/
def HeaderCore.Insts.CoreCloneClone.clone
  (self : HeaderCore) : Result HeaderCore := do
  ok self

/-- Trait implementation: [rao_header_verif::{impl core::clone::Clone for rao_header_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 33:9-33:14 -/
@[reducible]
def HeaderCore.Insts.CoreCloneClone : core.clone.Clone HeaderCore := {
  clone := HeaderCore.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_header_verif::{impl core::marker::Copy for rao_header_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 33:16-33:20 -/
@[reducible]
def HeaderCore.Insts.CoreMarkerCopy : core.marker.Copy HeaderCore := {
  cloneInst := HeaderCore.Insts.CoreCloneClone
}

/-- [rao_header_verif::{impl core::fmt::Debug for rao_header_verif::HeaderCore}::fmt]:
    Source: 'src/lib.rs', lines 33:22-33:27
    Visibility: public -/
def HeaderCore.Insts.CoreFmtDebug.fmt
  (self : HeaderCore) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU32 self.chunk_size
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.key_id_nonzero
  let dyn2 := Dyn.mk _ core.fmt.DebugBool self.hkdf_salt_nonzero
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.metadata_frame_len
  let dyn4 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool)
      self.object_id_field_valid
  core.fmt.Formatter.debug_struct_field5_finish f (toStr "HeaderCore") (toStr
    "chunk_size") dyn (toStr "key_id_nonzero") dyn1 (toStr "hkdf_salt_nonzero")
    dyn2 (toStr "metadata_frame_len") dyn3 (toStr "object_id_field_valid") dyn4

/-- Trait implementation: [rao_header_verif::{impl core::fmt::Debug for rao_header_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 33:22-33:27 -/
@[reducible]
def HeaderCore.Insts.CoreFmtDebug : core.fmt.Debug HeaderCore := {
  fmt := HeaderCore.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_header_verif::{impl core::marker::StructuralPartialEq for rao_header_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 33:29-33:38 -/
@[reducible]
def HeaderCore.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq HeaderCore := {
}

/-- [rao_header_verif::{impl core::cmp::PartialEq<rao_header_verif::HeaderCore> for rao_header_verif::HeaderCore}::eq]:
    Source: 'src/lib.rs', lines 33:29-33:38
    Visibility: public -/
def HeaderCore.Insts.CoreCmpPartialEqHeaderCore.eq
  (self : HeaderCore) (other : HeaderCore) : Result Bool := do
  if self.chunk_size = other.chunk_size
  then
    if self.key_id_nonzero = other.key_id_nonzero
    then
      if self.hkdf_salt_nonzero = other.hkdf_salt_nonzero
      then
        if self.metadata_frame_len = other.metadata_frame_len
        then ok (self.object_id_field_valid = other.object_id_field_valid)
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_header_verif::{impl core::cmp::PartialEq<rao_header_verif::HeaderCore> for rao_header_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 33:29-33:38 -/
@[reducible]
def HeaderCore.Insts.CoreCmpPartialEqHeaderCore : core.cmp.PartialEq HeaderCore
  HeaderCore := {
  eq := HeaderCore.Insts.CoreCmpPartialEqHeaderCore.eq
}

/-- [rao_header_verif::{impl core::cmp::Eq for rao_header_verif::HeaderCore}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 33:40-33:42
    Visibility: public -/
def HeaderCore.Insts.CoreCmpEq.assert_fields_are_eq
  (self : HeaderCore) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_header_verif::{impl core::cmp::Eq for rao_header_verif::HeaderCore}]
    Source: 'src/lib.rs', lines 33:40-33:42 -/
@[reducible]
def HeaderCore.Insts.CoreCmpEq : core.cmp.Eq HeaderCore := {
  partialEqInst := HeaderCore.Insts.CoreCmpPartialEqHeaderCore
  assert_fields_are_eq := HeaderCore.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_header_verif::{impl core::clone::Clone for rao_header_verif::HeaderWire}::clone]:
    Source: 'src/lib.rs', lines 42:9-42:14
    Visibility: public -/
def HeaderWire.Insts.CoreCloneClone.clone
  (self : HeaderWire) : Result HeaderWire := do
  ok self

/-- Trait implementation: [rao_header_verif::{impl core::clone::Clone for rao_header_verif::HeaderWire}]
    Source: 'src/lib.rs', lines 42:9-42:14 -/
@[reducible]
def HeaderWire.Insts.CoreCloneClone : core.clone.Clone HeaderWire := {
  clone := HeaderWire.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [rao_header_verif::{impl core::marker::Copy for rao_header_verif::HeaderWire}]
    Source: 'src/lib.rs', lines 42:16-42:20 -/
@[reducible]
def HeaderWire.Insts.CoreMarkerCopy : core.marker.Copy HeaderWire := {
  cloneInst := HeaderWire.Insts.CoreCloneClone
}

/-- [rao_header_verif::{impl core::fmt::Debug for rao_header_verif::HeaderWire}::fmt]:
    Source: 'src/lib.rs', lines 42:22-42:27
    Visibility: public -/
def HeaderWire.Insts.CoreFmtDebug.fmt
  (self : HeaderWire) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugBool self.magic_rao1
  let dyn1 := Dyn.mk _ core.fmt.DebugU16 self.header_len
  let dyn2 := Dyn.mk _ core.fmt.DebugU8 self.format_version
  let dyn3 := Dyn.mk _ core.fmt.DebugU8 self.suite_id
  let dyn4 := Dyn.mk _ core.fmt.DebugU32 self.chunk_size
  let dyn5 := Dyn.mk _ core.fmt.DebugU32 self.flags
  let dyn6 := Dyn.mk _ core.fmt.DebugBool self.key_id_nonzero
  let dyn7 := Dyn.mk _ core.fmt.DebugBool self.hkdf_salt_nonzero
  let dyn8 := Dyn.mk _ core.fmt.DebugU64 self.metadata_frame_len
  let dyn9 := Dyn.mk _ core.fmt.DebugBool self.reserved_0x38_0x40_zero
  let dyn10 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool)
      self.object_id_field_valid
  let values :=
    Array.to_slice
      (Array.make 11#usize [
        dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6, dyn7, dyn8, dyn9, dyn10
        ])
  let s ←
    lift (Array.to_slice
      (Array.make 11#usize [
        toStr "magic_rao1", toStr "header_len", toStr "format_version", toStr
        "suite_id", toStr "chunk_size", toStr "flags", toStr "key_id_nonzero",
        toStr "hkdf_salt_nonzero", toStr "metadata_frame_len", toStr
        "reserved_0x38_0x40_zero", toStr "object_id_field_valid"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "HeaderWire") s values

/-- Trait implementation: [rao_header_verif::{impl core::fmt::Debug for rao_header_verif::HeaderWire}]
    Source: 'src/lib.rs', lines 42:22-42:27 -/
@[reducible]
def HeaderWire.Insts.CoreFmtDebug : core.fmt.Debug HeaderWire := {
  fmt := HeaderWire.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [rao_header_verif::{impl core::marker::StructuralPartialEq for rao_header_verif::HeaderWire}]
    Source: 'src/lib.rs', lines 42:29-42:38 -/
@[reducible]
def HeaderWire.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq HeaderWire := {
}

/-- [rao_header_verif::{impl core::cmp::PartialEq<rao_header_verif::HeaderWire> for rao_header_verif::HeaderWire}::eq]:
    Source: 'src/lib.rs', lines 42:29-42:38
    Visibility: public -/
def HeaderWire.Insts.CoreCmpPartialEqHeaderWire.eq
  (self : HeaderWire) (other : HeaderWire) : Result Bool := do
  if self.magic_rao1 = other.magic_rao1
  then
    if self.header_len = other.header_len
    then
      if self.format_version = other.format_version
      then
        if self.suite_id = other.suite_id
        then
          if self.chunk_size = other.chunk_size
          then
            if self.flags = other.flags
            then
              if self.key_id_nonzero = other.key_id_nonzero
              then
                if self.hkdf_salt_nonzero = other.hkdf_salt_nonzero
                then
                  if self.metadata_frame_len = other.metadata_frame_len
                  then
                    if self.reserved_0x38_0x40_zero =
                      other.reserved_0x38_0x40_zero
                    then
                      ok (self.object_id_field_valid =
                        other.object_id_field_valid)
                    else ok false
                  else ok false
                else ok false
              else ok false
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [rao_header_verif::{impl core::cmp::PartialEq<rao_header_verif::HeaderWire> for rao_header_verif::HeaderWire}]
    Source: 'src/lib.rs', lines 42:29-42:38 -/
@[reducible]
def HeaderWire.Insts.CoreCmpPartialEqHeaderWire : core.cmp.PartialEq HeaderWire
  HeaderWire := {
  eq := HeaderWire.Insts.CoreCmpPartialEqHeaderWire.eq
}

/-- [rao_header_verif::{impl core::cmp::Eq for rao_header_verif::HeaderWire}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 42:40-42:42
    Visibility: public -/
def HeaderWire.Insts.CoreCmpEq.assert_fields_are_eq
  (self : HeaderWire) : Result Unit := do
  ok ()

/-- Trait implementation: [rao_header_verif::{impl core::cmp::Eq for rao_header_verif::HeaderWire}]
    Source: 'src/lib.rs', lines 42:40-42:42 -/
@[reducible]
def HeaderWire.Insts.CoreCmpEq : core.cmp.Eq HeaderWire := {
  partialEqInst := HeaderWire.Insts.CoreCmpPartialEqHeaderWire
  assert_fields_are_eq := HeaderWire.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [rao_header_verif::validate_chunk_size]:
    Source: 'src/lib.rs', lines 57:0-62:1
    Visibility: public -/
def validate_chunk_size
  (chunk_size : Std.U32) :
  Result (core.result.Result Unit RaoHeaderError)
  := do
  if chunk_size = 0#u32
  then ok (core.result.Result.Err RaoHeaderError.InvalidChunkSize)
  else
    let i ← chunk_size % CHUNK_SIZE_GRANULARITY
    if i != 0#u32
    then ok (core.result.Result.Err RaoHeaderError.InvalidChunkSize)
    else ok (core.result.Result.Ok ())

/-- [rao_header_verif::validate_metadata_frame_len]:
    Source: 'src/lib.rs', lines 64:0-72:1
    Visibility: public -/
def validate_metadata_frame_len
  (metadata_frame_len : Std.U64) :
  Result (core.result.Result Unit RaoHeaderError)
  := do
  if metadata_frame_len < RAO_METADATA_FRAME_MIN_LEN
  then ok (core.result.Result.Err RaoHeaderError.MetadataFrameLengthInvalid)
  else
    if metadata_frame_len > RAO_MAX_METADATA_FRAME_LEN
    then ok (core.result.Result.Err RaoHeaderError.MetadataFrameLengthInvalid)
    else ok (core.result.Result.Ok ())

/-- [rao_header_verif::validate_header_core]:
    Source: 'src/lib.rs', lines 74:0-87:1
    Visibility: public -/
def validate_header_core
  (header : HeaderCore) : Result (core.result.Result Unit RaoHeaderError) := do
  let r ← validate_chunk_size header.chunk_size
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    if header.key_id_nonzero
    then
      if header.hkdf_salt_nonzero
      then
        let r1 ← validate_metadata_frame_len header.metadata_frame_len
        let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue _ =>
          if header.object_id_field_valid
          then ok (core.result.Result.Ok ())
          else ok (core.result.Result.Err RaoHeaderError.InvalidObjectIdField)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Unit (core.convert.FromSame RaoHeaderError) residual
      else ok (core.result.Result.Err RaoHeaderError.InvalidSalt)
    else ok (core.result.Result.Err RaoHeaderError.InvalidKeyIdentifier)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame RaoHeaderError) residual

/-- [rao_header_verif::serialize_header_core]:
    Source: 'src/lib.rs', lines 89:0-104:1
    Visibility: public -/
def serialize_header_core
  (header : HeaderCore) :
  Result (core.result.Result HeaderWire RaoHeaderError)
  := do
  let r ← validate_header_core header
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    ok (core.result.Result.Ok
      {
        magic_rao1 := true,
        header_len := RAO_HEADER_LEN_U16,
        format_version := FORMAT_VERSION,
        suite_id := SUITE_ID_HKDF_SHA256_CHACHA20POLY1305,
        chunk_size := header.chunk_size,
        flags := 0#u32,
        key_id_nonzero := header.key_id_nonzero,
        hkdf_salt_nonzero := header.hkdf_salt_nonzero,
        metadata_frame_len := header.metadata_frame_len,
        reserved_0x38_0x40_zero := true,
        object_id_field_valid := header.object_id_field_valid
      })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      HeaderWire (core.convert.FromSame RaoHeaderError) residual

/-- [rao_header_verif::parse_header_core]:
    Source: 'src/lib.rs', lines 106:0-135:1
    Visibility: public -/
def parse_header_core
  (wire : HeaderWire) :
  Result (core.result.Result HeaderCore RaoHeaderError)
  := do
  if wire.magic_rao1
  then
    if wire.header_len != RAO_HEADER_LEN_U16
    then ok (core.result.Result.Err RaoHeaderError.InvalidHeaderLength)
    else
      if wire.format_version != FORMAT_VERSION
      then ok (core.result.Result.Err RaoHeaderError.UnsupportedFormatVersion)
      else
        if wire.suite_id != SUITE_ID_HKDF_SHA256_CHACHA20POLY1305
        then ok (core.result.Result.Err RaoHeaderError.InvalidSuite)
        else
          if wire.flags != 0#u32
          then ok (core.result.Result.Err RaoHeaderError.ReservedBytesNotZero)
          else
            if wire.reserved_0x38_0x40_zero
            then
              let r ←
                validate_header_core
                  {
                    chunk_size := wire.chunk_size,
                    key_id_nonzero := wire.key_id_nonzero,
                    hkdf_salt_nonzero := wire.hkdf_salt_nonzero,
                    metadata_frame_len := wire.metadata_frame_len,
                    object_id_field_valid := wire.object_id_field_valid
                  }
              let cf ← core.result.Result.Insts.CoreOpsTry.branch r
              match cf with
              | core.ops.control_flow.ControlFlow.Continue _ =>
                ok (core.result.Result.Ok
                  {
                    chunk_size := wire.chunk_size,
                    key_id_nonzero := wire.key_id_nonzero,
                    hkdf_salt_nonzero := wire.hkdf_salt_nonzero,
                    metadata_frame_len := wire.metadata_frame_len,
                    object_id_field_valid := wire.object_id_field_valid
                  })
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  HeaderCore (core.convert.FromSame RaoHeaderError) residual
            else
              ok (core.result.Result.Err RaoHeaderError.ReservedBytesNotZero)
  else ok (core.result.Result.Err RaoHeaderError.InvalidMagicBytes)

end RaoHeader
