-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rao_header_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace RaoHeader

/-- [rao_header_verif::RaoHeaderError]
    Source: 'src/lib.rs', lines 20:0-31:1
    Visibility: public -/
@[discriminant isize]
inductive RaoHeaderError where
| InvalidMagicBytes : RaoHeaderError
| InvalidHeaderLength : RaoHeaderError
| UnsupportedFormatVersion : RaoHeaderError
| InvalidSuite : RaoHeaderError
| InvalidChunkSize : RaoHeaderError
| ReservedBytesNotZero : RaoHeaderError
| InvalidKeyIdentifier : RaoHeaderError
| InvalidSalt : RaoHeaderError
| MetadataFrameLengthInvalid : RaoHeaderError
| InvalidObjectIdField : RaoHeaderError

/-- [rao_header_verif::HeaderCore]
    Source: 'src/lib.rs', lines 34:0-40:1
    Visibility: public -/
structure HeaderCore where
  chunk_size : Std.U32
  key_id_nonzero : Bool
  hkdf_salt_nonzero : Bool
  metadata_frame_len : Std.U64
  object_id_field_valid : Bool

/-- [rao_header_verif::HeaderWire]
    Source: 'src/lib.rs', lines 43:0-55:1
    Visibility: public -/
structure HeaderWire where
  magic_rao1 : Bool
  header_len : Std.U16
  format_version : Std.U8
  suite_id : Std.U8
  chunk_size : Std.U32
  flags : Std.U32
  key_id_nonzero : Bool
  hkdf_salt_nonzero : Bool
  metadata_frame_len : Std.U64
  reserved_0x38_0x40_zero : Bool
  object_id_field_valid : Bool

end RaoHeader
