#![no_main]

//! Structure-aware robustness target for the REM-PARITY 1.0 bootstrap block
//! (freeze criterion §18.3).
//!
//! Why this exists alongside `rem_parity_bootstrap_parse`. That target hands
//! raw bytes to `parse_bootstrap_block`, which validates magic, then a
//! CRC-64/XZ over the fixed header, then a CRC-64/XZ over the CBOR payload,
//! and only then decodes the payload, its object rows, scheme record,
//! filemark-map digest and epoch directory. Generated bytes essentially never
//! carry matching CRC-64 values, so generated cases stop at the integrity
//! checks and the decoding logic below is exercised only by the unmodified
//! seed inputs. An 8.5-billion-case campaign moved that target from 903 to
//! 1056 edges while its corpus grew without bound: lots of variety among
//! inputs that stop early, very little progress past the checks.
//!
//! This target instead treats the input as a *description* of a bootstrap
//! block, renders it into a genuinely well-formed frame with both CRCs
//! computed correctly, and then calls the same production
//! `parse_bootstrap_block` the Scanner calls. Nothing in the parser is
//! relaxed: the frames are valid because the harness built them properly, not
//! because validation was skipped.
//!
//! Property is robustness only — no panic, no hang, no unbounded allocation.
//! Most inputs are still expected to be rejected; the point is that they are
//! now rejected deeper in, by the decoding logic rather than by the CRC.

use libfuzzer_sys::fuzz_target;
use remanence_parity::bootstrap::{
    parse_bootstrap_block, BOOTSTRAP_HEADER_LEN, BOOTSTRAP_MAGIC, BOOTSTRAP_SCHEMA_MAJOR,
    FLAG_NO_PARITY,
};
use remanence_parity::crc64_xz;

/// Bound on the rendered CBOR payload so the harness cannot itself allocate
/// without limit; the parser's own bounds are what we are testing.
const MAX_PAYLOAD: usize = 1 << 16;
const PAYLOAD_CRC_LEN: usize = 8;

/// Keys the bootstrap payload map actually defines (§8.1). Unknown keys are
/// drawn from the gaps, to keep the "ignore unknown integer keys" path live.
const PAYLOAD_KEYS: [u64; 7] = [1, 2, 3, 4, 5, 20, 21];
const OBJECT_ROW_KEYS: [u64; 10] = [1, 2, 3, 4, 10, 11, 12, 13, 21, 22];

struct Cursor<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Cursor<'a> {
    fn new(data: &'a [u8]) -> Self {
        Self { data, pos: 0 }
    }

    fn u8(&mut self) -> u8 {
        let v = self.data.get(self.pos).copied().unwrap_or(0);
        self.pos = self.pos.saturating_add(1);
        v
    }

    fn u16(&mut self) -> u16 {
        u16::from(self.u8()) << 8 | u16::from(self.u8())
    }

    fn u32(&mut self) -> u32 {
        u32::from(self.u16()) << 16 | u32::from(self.u16())
    }

    fn take(&mut self, n: usize) -> Vec<u8> {
        let end = self.pos.saturating_add(n).min(self.data.len());
        let mut out = self.data.get(self.pos..end).unwrap_or(&[]).to_vec();
        self.pos = end;
        out.resize(n, 0);
        out
    }

    fn rest(&mut self) -> &'a [u8] {
        let out = self.data.get(self.pos..).unwrap_or(&[]);
        self.pos = self.data.len();
        out
    }

    fn exhausted(&self) -> bool {
        self.pos >= self.data.len()
    }
}

// --- minimal deterministic CBOR writer -----------------------------------
// Shortest-form heads only, which is what §5.3 requires; the harness emits
// canonical encodings so cases reach the semantic checks rather than dying at
// the canonical-form check. Non-canonical framing is already covered by the
// raw-bytes target.

fn head(out: &mut Vec<u8>, major: u8, arg: u64) {
    let initial = major << 5;
    match arg {
        0..=23 => out.push(initial | arg as u8),
        24..=0xff => {
            out.push(initial | 24);
            out.push(arg as u8);
        }
        0x100..=0xffff => {
            out.push(initial | 25);
            out.extend_from_slice(&(arg as u16).to_be_bytes());
        }
        0x1_0000..=0xffff_ffff => {
            out.push(initial | 26);
            out.extend_from_slice(&(arg as u32).to_be_bytes());
        }
        _ => {
            out.push(initial | 27);
            out.extend_from_slice(&arg.to_be_bytes());
        }
    }
}

fn uint(out: &mut Vec<u8>, v: u64) {
    head(out, 0, v);
}

fn bytes(out: &mut Vec<u8>, b: &[u8]) {
    head(out, 2, b.len() as u64);
    out.extend_from_slice(b);
}

fn text(out: &mut Vec<u8>, s: &str) {
    head(out, 3, s.len() as u64);
    out.extend_from_slice(s.as_bytes());
}

fn boolean(out: &mut Vec<u8>, v: bool) {
    out.push(0xe0 | if v { 21 } else { 20 });
}

/// Emit one value whose CBOR shape is selected by the input, so the decoder's
/// type-mismatch arms are reachable as well as its happy paths.
fn value(out: &mut Vec<u8>, cur: &mut Cursor, depth: u8) {
    match cur.u8() % 8 {
        0 => uint(out, u64::from(cur.u32())),
        1 => {
            let n = (cur.u8() % 40) as usize;
            let b = cur.take(n);
            bytes(out, &b);
        }
        2 => bytes(out, &cur.take(32)),
        3 => bytes(out, &cur.take(16)),
        4 => boolean(out, cur.u8() & 1 == 1),
        5 => text(out, if cur.u8() & 1 == 1 { "plaintext" } else { "encrypted" }),
        6 if depth < 2 => {
            let n = (cur.u8() % 4) as usize;
            head(out, 4, n as u64);
            for _ in 0..n {
                value(out, cur, depth + 1);
            }
        }
        _ => uint(out, u64::from(cur.u16())),
    }
}

/// One object row as an ascending-key CBOR map. §5.3 requires ascending keys
/// and the decoder now enforces it, so emitting them sorted is what lets these
/// cases reach the row's semantic validation instead of stopping at the
/// ordering check.
fn object_row(out: &mut Vec<u8>, cur: &mut Cursor) {
    let count = (cur.u8() % (OBJECT_ROW_KEYS.len() as u8 + 1)) as usize;
    let mut keys: Vec<u64> = Vec::with_capacity(count + 1);
    for _ in 0..count {
        keys.push(OBJECT_ROW_KEYS[(cur.u8() as usize) % OBJECT_ROW_KEYS.len()]);
    }
    if cur.u8() % 5 == 0 {
        // An unknown integer key in correct position: the 1.x extension
        // mechanism, which decoders must ignore rather than reject.
        keys.push(u64::from(cur.u8() % 60) + 30);
    }
    keys.sort_unstable();
    keys.dedup();

    head(out, 5, keys.len() as u64);
    for key in keys {
        uint(out, key);
        value(out, cur, 0);
    }
}

fn build_payload(cur: &mut Cursor) -> Vec<u8> {
    let mut out = Vec::new();
    let count = (cur.u8() % (PAYLOAD_KEYS.len() as u8 + 1)) as usize;
    let mut keys: Vec<u64> = Vec::with_capacity(count + 1);
    for _ in 0..count {
        keys.push(PAYLOAD_KEYS[(cur.u8() as usize) % PAYLOAD_KEYS.len()]);
    }
    if cur.u8() % 6 == 0 {
        keys.push(u64::from(cur.u8() % 40) + 40);
    }
    keys.sort_unstable();
    keys.dedup();

    head(&mut out, 5, keys.len() as u64);
    for key in keys {
        uint(&mut out, key);
        match key {
            // Object rows: an array of maps is where the interesting
            // plaintext/encrypted validation lives.
            5 => {
                let rows = (cur.u8() % 5) as usize;
                head(&mut out, 4, rows as u64);
                for _ in 0..rows {
                    object_row(&mut out, cur);
                    if out.len() > MAX_PAYLOAD {
                        break;
                    }
                }
            }
            // Scheme record: a nested ascending-key map.
            1 => {
                let n = (cur.u8() % 6) as usize;
                let mut sub: Vec<u64> = (0..n).map(|_| u64::from(cur.u8() % 8) + 1).collect();
                sub.sort_unstable();
                sub.dedup();
                head(&mut out, 5, sub.len() as u64);
                for k in sub {
                    uint(&mut out, k);
                    value(&mut out, cur, 1);
                }
            }
            _ => value(&mut out, cur, 0),
        }
        if out.len() > MAX_PAYLOAD {
            break;
        }
    }
    out
}

fuzz_target!(|data: &[u8]| {
    if data.len() > 1 << 18 {
        return;
    }
    let mut cur = Cursor::new(data);

    let control = cur.u8();
    let no_parity = control & 1 == 1;
    let raw_payload_mode = control & 2 == 2;
    let trailing_pad = ((control >> 2) % 8) as usize;

    let minor = cur.u16();
    let block_size_bytes = cur.u32();
    let sequence = cur.u32();
    let tape_uuid = cur.take(16);

    let payload: Vec<u8> = if raw_payload_mode {
        // Framing valid, CBOR arbitrary: exercises the CBOR decoder itself.
        let rest = cur.rest();
        rest[..rest.len().min(MAX_PAYLOAD)].to_vec()
    } else {
        // Framing valid, CBOR well-formed and canonical: exercises the
        // semantic layer — object rows, scheme record, epoch directory.
        let mut p = build_payload(&mut cur);
        if !cur.exhausted() && p.len() < MAX_PAYLOAD {
            // Trailing bytes inside the declared payload extent are a
            // nonconformity §5.3 calls out; keep that path reachable.
            let extra = cur.take(2);
            p.extend_from_slice(&extra);
        }
        p.truncate(MAX_PAYLOAD);
        p
    };

    let total = BOOTSTRAP_HEADER_LEN + payload.len() + PAYLOAD_CRC_LEN + trailing_pad;
    let mut buf = vec![0u8; total];

    buf[0..8].copy_from_slice(&BOOTSTRAP_MAGIC);
    buf[8..10].copy_from_slice(&BOOTSTRAP_SCHEMA_MAJOR.to_be_bytes());
    buf[10..12].copy_from_slice(&minor.to_be_bytes());
    let flags: u32 = if no_parity { FLAG_NO_PARITY } else { 0 };
    buf[12..16].copy_from_slice(&flags.to_be_bytes());
    buf[16..32].copy_from_slice(&tape_uuid);
    buf[32..36].copy_from_slice(&block_size_bytes.to_be_bytes());
    buf[36..40].copy_from_slice(&sequence.to_be_bytes());
    buf[40..44].copy_from_slice(&(payload.len() as u32).to_le_bytes());

    // Both integrity checks computed correctly, exactly as the writer does.
    let header_crc = crc64_xz(&buf[0..0x2C]);
    buf[44..52].copy_from_slice(&header_crc.to_le_bytes());

    let cbor_end = BOOTSTRAP_HEADER_LEN + payload.len();
    buf[BOOTSTRAP_HEADER_LEN..cbor_end].copy_from_slice(&payload);
    let payload_crc = crc64_xz(&payload);
    buf[cbor_end..cbor_end + PAYLOAD_CRC_LEN].copy_from_slice(&payload_crc.to_le_bytes());

    let _ = parse_bootstrap_block(&buf);
});
