-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [parity_mapping_verif]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace parity_mapping_verif

/-- [parity_mapping_verif::MappingError]
    Source: 'src/lib.rs', lines 11:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive MappingError where
| DataShardsPerEpochOverflow : MappingError
| DataShardsPerEpochZero : MappingError
| StripeIndexOutsideScheme : MappingError
| DataIndexOutsideScheme : MappingError
| ParityShardHasNoDataOrdinal : MappingError
| DataOrdinalOverflow : MappingError

/-- [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::MappingError}::clone]:
    Source: 'src/lib.rs', lines 10:9-10:14
    Visibility: public -/
def MappingError.Insts.CoreCloneClone.clone
  (self : MappingError) : Result MappingError := do
  ok self

/-- Trait implementation: [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::MappingError}]
    Source: 'src/lib.rs', lines 10:9-10:14 -/
@[reducible]
def MappingError.Insts.CoreCloneClone : core.clone.Clone MappingError := {
  clone := MappingError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::Copy for parity_mapping_verif::MappingError}]
    Source: 'src/lib.rs', lines 10:16-10:20 -/
@[reducible]
def MappingError.Insts.CoreMarkerCopy : core.marker.Copy MappingError := {
  cloneInst := MappingError.Insts.CoreCloneClone
}

/-- [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::MappingError}::fmt]:
    Source: 'src/lib.rs', lines 10:22-10:27
    Visibility: public -/
def MappingError.Insts.CoreFmtDebug.fmt
  (self : MappingError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | MappingError.DataShardsPerEpochOverflow =>
    core.fmt.Formatter.write_str f (toStr "DataShardsPerEpochOverflow")
  | MappingError.DataShardsPerEpochZero =>
    core.fmt.Formatter.write_str f (toStr "DataShardsPerEpochZero")
  | MappingError.StripeIndexOutsideScheme =>
    core.fmt.Formatter.write_str f (toStr "StripeIndexOutsideScheme")
  | MappingError.DataIndexOutsideScheme =>
    core.fmt.Formatter.write_str f (toStr "DataIndexOutsideScheme")
  | MappingError.ParityShardHasNoDataOrdinal =>
    core.fmt.Formatter.write_str f (toStr "ParityShardHasNoDataOrdinal")
  | MappingError.DataOrdinalOverflow =>
    core.fmt.Formatter.write_str f (toStr "DataOrdinalOverflow")

/-- Trait implementation: [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::MappingError}]
    Source: 'src/lib.rs', lines 10:22-10:27 -/
@[reducible]
def MappingError.Insts.CoreFmtDebug : core.fmt.Debug MappingError := {
  fmt := MappingError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::StructuralPartialEq for parity_mapping_verif::MappingError}]
    Source: 'src/lib.rs', lines 10:29-10:38 -/
@[reducible]
def MappingError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq MappingError := {
}

/-- [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::MappingError> for parity_mapping_verif::MappingError}::eq]:
    Source: 'src/lib.rs', lines 10:29-10:38
    Visibility: public -/
def MappingError.Insts.CoreCmpPartialEqMappingError.eq
  (self : MappingError) (other : MappingError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::MappingError> for parity_mapping_verif::MappingError}]
    Source: 'src/lib.rs', lines 10:29-10:38 -/
@[reducible]
def MappingError.Insts.CoreCmpPartialEqMappingError : core.cmp.PartialEq
  MappingError MappingError := {
  eq := MappingError.Insts.CoreCmpPartialEqMappingError.eq
}

/-- [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::MappingError}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 10:40-10:42
    Visibility: public -/
def MappingError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : MappingError) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::MappingError}]
    Source: 'src/lib.rs', lines 10:40-10:42 -/
@[reducible]
def MappingError.Insts.CoreCmpEq : core.cmp.Eq MappingError := {
  partialEqInst := MappingError.Insts.CoreCmpPartialEqMappingError
  assert_fields_are_eq := MappingError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_mapping_verif::StripePosition]
    Source: 'src/lib.rs', lines 21:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive StripePosition where
| Data : Std.U64 → StripePosition
| Parity : Std.U64 → StripePosition

/-- [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::StripePosition}::clone]:
    Source: 'src/lib.rs', lines 20:9-20:14
    Visibility: public -/
def StripePosition.Insts.CoreCloneClone.clone
  (self : StripePosition) : Result StripePosition := do
  ok self

/-- Trait implementation: [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::StripePosition}]
    Source: 'src/lib.rs', lines 20:9-20:14 -/
@[reducible]
def StripePosition.Insts.CoreCloneClone : core.clone.Clone StripePosition := {
  clone := StripePosition.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::Copy for parity_mapping_verif::StripePosition}]
    Source: 'src/lib.rs', lines 20:16-20:20 -/
@[reducible]
def StripePosition.Insts.CoreMarkerCopy : core.marker.Copy StripePosition := {
  cloneInst := StripePosition.Insts.CoreCloneClone
}

/-- [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::StripePosition}::fmt]:
    Source: 'src/lib.rs', lines 20:22-20:27
    Visibility: public -/
def StripePosition.Insts.CoreFmtDebug.fmt
  (self : StripePosition) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | StripePosition.Data __self_0 =>
    let __self_01 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "Data") (toStr
      "index") __self_01
  | StripePosition.Parity __self_0 =>
    let __self_01 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "Parity") (toStr
      "index") __self_01

/-- Trait implementation: [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::StripePosition}]
    Source: 'src/lib.rs', lines 20:22-20:27 -/
@[reducible]
def StripePosition.Insts.CoreFmtDebug : core.fmt.Debug StripePosition := {
  fmt := StripePosition.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::StructuralPartialEq for parity_mapping_verif::StripePosition}]
    Source: 'src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def StripePosition.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq StripePosition := {
}

/-- [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::StripePosition> for parity_mapping_verif::StripePosition}::eq]:
    Source: 'src/lib.rs', lines 20:29-20:38
    Visibility: public -/
def StripePosition.Insts.CoreCmpPartialEqStripePosition.eq
  (self : StripePosition) (other : StripePosition) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | StripePosition.Data __self_0 =>
      match other with
      | StripePosition.Data __arg1_0 =>
        lift (core.cmp.impls.PartialEqU64.eq __self_0 __arg1_0)
      | StripePosition.Parity _ => fail panic
    | StripePosition.Parity __self_0 =>
      match other with
      | StripePosition.Data _ => fail panic
      | StripePosition.Parity __arg1_0 =>
        lift (core.cmp.impls.PartialEqU64.eq __self_0 __arg1_0)
  else ok false

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::StripePosition> for parity_mapping_verif::StripePosition}]
    Source: 'src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def StripePosition.Insts.CoreCmpPartialEqStripePosition : core.cmp.PartialEq
  StripePosition StripePosition := {
  eq := StripePosition.Insts.CoreCmpPartialEqStripePosition.eq
}

/-- [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::StripePosition}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 20:40-20:42
    Visibility: public -/
def StripePosition.Insts.CoreCmpEq.assert_fields_are_eq
  (self : StripePosition) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::StripePosition}]
    Source: 'src/lib.rs', lines 20:40-20:42 -/
@[reducible]
def StripePosition.Insts.CoreCmpEq : core.cmp.Eq StripePosition := {
  partialEqInst := StripePosition.Insts.CoreCmpPartialEqStripePosition
  assert_fields_are_eq := StripePosition.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_mapping_verif::StripeAddress]
    Source: 'src/lib.rs', lines 27:0-31:1
    Visibility: public -/
structure StripeAddress where
  neighborhood : Std.U64
  stripe_index : Std.U64
  position : StripePosition

/-- [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::StripeAddress}::clone]:
    Source: 'src/lib.rs', lines 26:9-26:14
    Visibility: public -/
def StripeAddress.Insts.CoreCloneClone.clone
  (self : StripeAddress) : Result StripeAddress := do
  ok self

/-- Trait implementation: [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::StripeAddress}]
    Source: 'src/lib.rs', lines 26:9-26:14 -/
@[reducible]
def StripeAddress.Insts.CoreCloneClone : core.clone.Clone StripeAddress := {
  clone := StripeAddress.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::Copy for parity_mapping_verif::StripeAddress}]
    Source: 'src/lib.rs', lines 26:16-26:20 -/
@[reducible]
def StripeAddress.Insts.CoreMarkerCopy : core.marker.Copy StripeAddress := {
  cloneInst := StripeAddress.Insts.CoreCloneClone
}

/-- [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::StripeAddress}::fmt]:
    Source: 'src/lib.rs', lines 26:22-26:27
    Visibility: public -/
def StripeAddress.Insts.CoreFmtDebug.fmt
  (self : StripeAddress) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.neighborhood
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.stripe_index
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared StripePosition.Insts.CoreFmtDebug)
      self.position
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "StripeAddress")
    (toStr "neighborhood") dyn (toStr "stripe_index") dyn1 (toStr "position")
    dyn2

/-- Trait implementation: [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::StripeAddress}]
    Source: 'src/lib.rs', lines 26:22-26:27 -/
@[reducible]
def StripeAddress.Insts.CoreFmtDebug : core.fmt.Debug StripeAddress := {
  fmt := StripeAddress.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::StructuralPartialEq for parity_mapping_verif::StripeAddress}]
    Source: 'src/lib.rs', lines 26:29-26:38 -/
@[reducible]
def StripeAddress.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq StripeAddress := {
}

/-- [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::StripeAddress> for parity_mapping_verif::StripeAddress}::eq]:
    Source: 'src/lib.rs', lines 26:29-26:38
    Visibility: public -/
def StripeAddress.Insts.CoreCmpPartialEqStripeAddress.eq
  (self : StripeAddress) (other : StripeAddress) : Result Bool := do
  if self.neighborhood = other.neighborhood
  then
    if self.stripe_index = other.stripe_index
    then
      StripePosition.Insts.CoreCmpPartialEqStripePosition.eq self.position
        other.position
    else ok false
  else ok false

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::StripeAddress> for parity_mapping_verif::StripeAddress}]
    Source: 'src/lib.rs', lines 26:29-26:38 -/
@[reducible]
def StripeAddress.Insts.CoreCmpPartialEqStripeAddress : core.cmp.PartialEq
  StripeAddress StripeAddress := {
  eq := StripeAddress.Insts.CoreCmpPartialEqStripeAddress.eq
}

/-- [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::StripeAddress}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 26:40-26:42
    Visibility: public -/
def StripeAddress.Insts.CoreCmpEq.assert_fields_are_eq
  (self : StripeAddress) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::StripeAddress}]
    Source: 'src/lib.rs', lines 26:40-26:42 -/
@[reducible]
def StripeAddress.Insts.CoreCmpEq : core.cmp.Eq StripeAddress := {
  partialEqInst := StripeAddress.Insts.CoreCmpPartialEqStripeAddress
  assert_fields_are_eq := StripeAddress.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_mapping_verif::ParityScheme]
    Source: 'src/lib.rs', lines 34:0-38:1
    Visibility: public -/
structure ParityScheme where
  data_blocks_per_stripe : Std.U64
  parity_blocks_per_stripe : Std.U64
  stripes_per_neighborhood : Std.U64

/-- [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::ParityScheme}::clone]:
    Source: 'src/lib.rs', lines 33:9-33:14
    Visibility: public -/
def ParityScheme.Insts.CoreCloneClone.clone
  (self : ParityScheme) : Result ParityScheme := do
  ok self

/-- Trait implementation: [parity_mapping_verif::{impl core::clone::Clone for parity_mapping_verif::ParityScheme}]
    Source: 'src/lib.rs', lines 33:9-33:14 -/
@[reducible]
def ParityScheme.Insts.CoreCloneClone : core.clone.Clone ParityScheme := {
  clone := ParityScheme.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::Copy for parity_mapping_verif::ParityScheme}]
    Source: 'src/lib.rs', lines 33:16-33:20 -/
@[reducible]
def ParityScheme.Insts.CoreMarkerCopy : core.marker.Copy ParityScheme := {
  cloneInst := ParityScheme.Insts.CoreCloneClone
}

/-- [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::ParityScheme}::fmt]:
    Source: 'src/lib.rs', lines 33:22-33:27
    Visibility: public -/
def ParityScheme.Insts.CoreFmtDebug.fmt
  (self : ParityScheme) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.data_blocks_per_stripe
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.parity_blocks_per_stripe
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64)
      self.stripes_per_neighborhood
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "ParityScheme") (toStr
    "data_blocks_per_stripe") dyn (toStr "parity_blocks_per_stripe") dyn1
    (toStr "stripes_per_neighborhood") dyn2

/-- Trait implementation: [parity_mapping_verif::{impl core::fmt::Debug for parity_mapping_verif::ParityScheme}]
    Source: 'src/lib.rs', lines 33:22-33:27 -/
@[reducible]
def ParityScheme.Insts.CoreFmtDebug : core.fmt.Debug ParityScheme := {
  fmt := ParityScheme.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [parity_mapping_verif::{impl core::marker::StructuralPartialEq for parity_mapping_verif::ParityScheme}]
    Source: 'src/lib.rs', lines 33:29-33:38 -/
@[reducible]
def ParityScheme.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ParityScheme := {
}

/-- [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::ParityScheme> for parity_mapping_verif::ParityScheme}::eq]:
    Source: 'src/lib.rs', lines 33:29-33:38
    Visibility: public -/
def ParityScheme.Insts.CoreCmpPartialEqParityScheme.eq
  (self : ParityScheme) (other : ParityScheme) : Result Bool := do
  if self.data_blocks_per_stripe = other.data_blocks_per_stripe
  then
    if self.parity_blocks_per_stripe = other.parity_blocks_per_stripe
    then ok (self.stripes_per_neighborhood = other.stripes_per_neighborhood)
    else ok false
  else ok false

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::PartialEq<parity_mapping_verif::ParityScheme> for parity_mapping_verif::ParityScheme}]
    Source: 'src/lib.rs', lines 33:29-33:38 -/
@[reducible]
def ParityScheme.Insts.CoreCmpPartialEqParityScheme : core.cmp.PartialEq
  ParityScheme ParityScheme := {
  eq := ParityScheme.Insts.CoreCmpPartialEqParityScheme.eq
}

/-- [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::ParityScheme}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 33:40-33:42
    Visibility: public -/
def ParityScheme.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ParityScheme) : Result Unit := do
  ok ()

/-- Trait implementation: [parity_mapping_verif::{impl core::cmp::Eq for parity_mapping_verif::ParityScheme}]
    Source: 'src/lib.rs', lines 33:40-33:42 -/
@[reducible]
def ParityScheme.Insts.CoreCmpEq : core.cmp.Eq ParityScheme := {
  partialEqInst := ParityScheme.Insts.CoreCmpPartialEqParityScheme
  assert_fields_are_eq := ParityScheme.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [parity_mapping_verif::data_shards_per_epoch]:
    Source: 'src/lib.rs', lines 40:0-52:1
    Visibility: public -/
def data_shards_per_epoch
  (scheme : ParityScheme) :
  Result (core.result.Result Std.U64 MappingError)
  := do
  let o ←
    lift (U64.checked_mul scheme.stripes_per_neighborhood
      scheme.data_blocks_per_stripe)
  match o with
  | none => ok (core.result.Result.Err MappingError.DataShardsPerEpochOverflow)
  | some count =>
    if count = 0#u64
    then ok (core.result.Result.Err MappingError.DataShardsPerEpochZero)
    else ok (core.result.Result.Ok count)

/-- [parity_mapping_verif::ordinal_to_stripe]:
    Source: 'src/lib.rs', lines 54:0-70:1
    Visibility: public -/
def ordinal_to_stripe
  (ordinal : Std.U64) (scheme : ParityScheme) :
  Result (core.result.Result StripeAddress MappingError)
  := do
  let r ← data_shards_per_epoch scheme
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let epoch ← ordinal / val
    let ordinal_in_epoch ← ordinal % val
    let i ← ordinal_in_epoch % scheme.stripes_per_neighborhood
    let i1 ← ordinal_in_epoch / scheme.stripes_per_neighborhood
    ok (core.result.Result.Ok
      {
        neighborhood := epoch,
        stripe_index := i,
        position := (StripePosition.Data i1)
      })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      StripeAddress (core.convert.FromSame MappingError) residual

/-- [parity_mapping_verif::stripe_data_to_ordinal]:
    Source: 'src/lib.rs', lines 72:0-110:1
    Visibility: public -/
def stripe_data_to_ordinal
  (addr : StripeAddress) (scheme : ParityScheme) :
  Result (core.result.Result Std.U64 MappingError)
  := do
  if addr.stripe_index >= scheme.stripes_per_neighborhood
  then ok (core.result.Result.Err MappingError.StripeIndexOutsideScheme)
  else
    match addr.position with
    | StripePosition.Data index =>
      if index >= scheme.data_blocks_per_stripe
      then ok (core.result.Result.Err MappingError.DataIndexOutsideScheme)
      else
        let r ← data_shards_per_epoch scheme
        let cf ← core.result.Result.Insts.CoreOpsTry.branch r
        match cf with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let o ← lift (U64.checked_mul addr.neighborhood val)
          match o with
          | none =>
            ok (core.result.Result.Err MappingError.DataOrdinalOverflow)
          | some base =>
            let o1 ←
              lift (U64.checked_mul index scheme.stripes_per_neighborhood)
            match o1 with
            | none =>
              ok (core.result.Result.Err MappingError.DataOrdinalOverflow)
            | some offset =>
              let o2 ← lift (U64.checked_add base offset)
              match o2 with
              | none =>
                ok (core.result.Result.Err MappingError.DataOrdinalOverflow)
              | some base1 =>
                let o3 ← lift (U64.checked_add base1 addr.stripe_index)
                match o3 with
                | none =>
                  ok (core.result.Result.Err MappingError.DataOrdinalOverflow)
                | some ordinal => ok (core.result.Result.Ok ordinal)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Std.U64 (core.convert.FromSame MappingError) residual
    | StripePosition.Parity _ =>
      ok (core.result.Result.Err MappingError.ParityShardHasNoDataOrdinal)

end parity_mapping_verif
