-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tape_init_verif]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace TapeInit

/-- [tape_init_verif::TapeInitGeometry]
    Source: 'src/lib.rs', lines 17:0-20:1
    Visibility: public -/
structure TapeInitGeometry where
  block_size_bytes : Std.U64
  parity_mode : Std.U64

/-- [tape_init_verif::BotClassification]
    Source: 'src/lib.rs', lines 24:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive BotClassification where
| BlankCheckEod : BotClassification
| OursBootstrap : Std.U64 → TapeInitGeometry → BotClassification
| ForeignFormat : BotClassification
| ReadError : BotClassification
| UnrecognizedData : BotClassification

/-- [tape_init_verif::BarcodeLifecycleState]
    Source: 'src/lib.rs', lines 37:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive BarcodeLifecycleState where
| Available : BarcodeLifecycleState
| AssignedTo : Std.U64 → BarcodeLifecycleState
| Retired : BarcodeLifecycleState

/-- [tape_init_verif::CatalogBarcodeRelation]
    Source: 'src/lib.rs', lines 45:0-49:1
    Visibility: public -/
@[discriminant isize]
inductive CatalogBarcodeRelation where
| Matches : CatalogBarcodeRelation
| DiffersWithRecordedRelabel : CatalogBarcodeRelation
| DiffersWithoutRelabel : CatalogBarcodeRelation

/-- [tape_init_verif::CatalogRowDisposition]
    Source: 'src/lib.rs', lines 53:0-56:1
    Visibility: public -/
@[discriminant isize]
inductive CatalogRowDisposition where
| Active : CatalogRowDisposition
| Retired : CatalogRowDisposition

/-- [tape_init_verif::CatalogTapeInitRow]
    Source: 'src/lib.rs', lines 60:0-66:1
    Visibility: public -/
structure CatalogTapeInitRow where
  uuid : Std.U64
  geometry : TapeInitGeometry
  catalog_unwritten : Bool
  barcode_relation : CatalogBarcodeRelation
  disposition : CatalogRowDisposition

/-- [tape_init_verif::CommittedCopyState]
    Source: 'src/lib.rs', lines 70:0-75:1
    Visibility: public -/
@[discriminant isize]
inductive CommittedCopyState where
| None : CommittedCopyState
| CurrentPool : CommittedCopyState
| ForeignPool : CommittedCopyState
| UnknownPool : CommittedCopyState

/-- [tape_init_verif::TapeInitError]
    Source: 'src/lib.rs', lines 85:0-99:1
    Visibility: public -/
@[discriminant isize]
inductive TapeInitError where
| BarcodeAssignedToDifferentUuid : TapeInitError
| BarcodeRetired : TapeInitError
| MediaSwapReusedBarcode : TapeInitError
| BarcodeChangedWithoutRelabel : TapeInitError
| BotReadError : TapeInitError
| ForeignFormat : TapeInitError
| UnrecognizedData : TapeInitError
| MissingCatalogRow : TapeInitError
| PhysicalDataPastBootstrap : TapeInitError
| CommittedCopiesPresent : TapeInitError
| TapePoolAssignmentConflict : TapeInitError
| GeometryMismatch : TapeInitError
| CatalogIndicatesWritten : TapeInitError

/-- [tape_init_verif::InitDecision]
    Source: 'src/lib.rs', lines 103:0-110:1
    Visibility: public -/
@[discriminant isize]
inductive InitDecision where
| FreshInit : InitDecision
| IdempotentNoOp : InitDecision
| RequireForce : TapeInitError → InitDecision
| RefuseClobber : TapeInitError → InitDecision
| Anomaly : TapeInitError → InitDecision
| NeedsExplicitRebuild : TapeInitError → InitDecision

end TapeInit
